### ISSUE TITLE
redirectTo query params cut off

### ISSUE THREAD

**Issue by nicgene** [supabase/gotrue-js#116]
# Bug report

## Describe the bug

Setting redirectTo for signUp with query params results in the url being cut off after the first param.

## To Reproduce

Send a POST request to the signup endpoint: `https://xxx.supabase.co/auth/v1/signup?redirect_to=http://localhost:8080?verified&reference=widget-create`

Email confirmation link still contains the query params: `https://xxx.supabase.co/auth/v1/verify?token=xxx&type=signup&redirect_to=http://localhost:8080?verified&reference=widget-create`

Supabase redirects me to: `http://localhost:8080/?verified#`

Everything after the first param is cut off.

## Expected behavior

Preserve the params.

## System information

- OS: Arch/Sway
- Browser: Firefox 90
- Version of supabase-js: @supabase/supabase-js@1.21.0
- Version of Node.js: 16.2.0

**Comment by nicgene** [comment]
If anybody else has this issue, the workaround is to add a slash after the port.

`https://xxx.supabase.co/auth/v1/signup?redirect_to=http://localhost:8080/?verified&reference=widget-create`

**Comment by srossross** [comment]
When I try to add any query params at all `redirectTo` breaks and just goes to my production application, I'm running my app in localhost and pointing to my remote supabase:

Here is the network log:
* `https://xxx.supabase.co/auth/v1/authorize?provider=github&redirect_to=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fcallback%3Fnext%3Dhello-world&code_challenge=xxx&code_challenge_method=s256`
* `https://github.com/login/oauth/authorize?client_id=xxx&redirect_to=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fcallback%3Fnext%3Dhello-world&redirect_uri=https%3A%2F%2Fxxx.supabase.co%2Fauth%2Fv1%2Fcallback&response_type=code&scope=user%3Aemail&state=xxx`
* `https://xxx.supabase.co/auth/v1/callback?code=cf53b2895aefac95dc80&state=xxx`
* `https://my-production-app.com/?code=xxx`


Without the extra `?next=hello-world`  I get back to `localhost:3000/auth/callback`


Can anyone direct me how to proceed?

**Comment by mosnicholas** [comment]
+1 I am seeing this issue.

**Comment by eugenlinde** [comment]
same problem here. I am using email template (supabase->authentication->email templates) where the user clicks a button to confirm their singup. my current sign up link goes to: `https://xyz.supabase.co/auth/v1/verify?token={{ .TokenHash }}&type=signup&redirect_to=https://foo.bar.app/?success=ok&message=something` . when user clicks on the link, they are redirect to `https://foo.bar.app/?code=1234567890&success=ok`. the `message=something` part is missing, indicating that everything after the first query param is omitted.
