### ISSUE TITLE
Phone Auth Verify OTP did not stored in Local Storage

### ISSUE THREAD

**Issue by zernonia** [supabase/gotrue-js#118]
# Bug report

## Describe the bug

Phone auth OTP and verification no problem. But the `supabase.auth.token` is not stored in Local Storage. 

![image](https://user-images.githubusercontent.com/59365435/128035340-105be06b-2404-4d68-80f7-12fd31c7f815.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Your code
```
    let { session, error } = await supabase.auth.signIn({
      phone: phoneNumber
    })
```

```

    let { session, error } = await supabase.auth.verifyOTP({
      phone: phoneNumber,
      token: tokenString,
    })

```

2. Check localstorage / Get session using supabase.auth.user()  `// return null`

## Expected behavior

User token should be stored in localstorage.

## System information

- OS: Window 10
- Browser (if applies) Edge & Chrome
- Version of supabase-js: [e.g. 1.21.0]
- Version of Node.js: [e.g. 14.16.1]

**Comment by unix17** [comment]
Any updates ?

**Comment by unix17** [comment]
the root cause
in session.**expires_at** as verifyMobileOTP do not return **expires_at** you should use **expires_in** instead
```
private _saveSession(session: Session) {
    this.currentSession = session
    this.currentUser = session.user

    const expiresAt = session.expires_at
    if (expiresAt) {
      const timeNow = Math.round(Date.now() / 1000)
      const expiresIn = expiresAt - timeNow
      const refreshDurationBeforeExpires = expiresIn > 60 ? 60 : 0.5
      this._startAutoRefreshToken((expiresIn - refreshDurationBeforeExpires) * 1000)
    }
 
    // Do we need any extra check before persist session
    // access_token or user ?
    
    if (this.persistSession && session.expires_at) { -----> **session.expires_in**
      console.log(this.currentSession, '_persistSession');
      this._persistSession(this.currentSession)
    }
  }
```

**Comment by unix17** [comment]
verifyMobileOTP do not return expires_at

private _saveSession(session: Session) {
    this.currentSession = session
    this.currentUser = session.user

    const expiresAt = session.expires_at
    if (expiresAt) {
      const timeNow = Math.round(Date.now() / 1000)
      const expiresIn = expiresAt - timeNow
      const refreshDurationBeforeExpires = expiresIn > 60 ? 60 : 0.5
      this._startAutoRefreshToken((expiresIn - refreshDurationBeforeExpires) * 1000)
    }

    // Do we need any extra check before persist session
    // access_token or user ?
    if (this.persistSession && session.expires_at ->>>> ⛔️⛔️⛔️ ) { 
      this._persistSession(this.currentSession)
    }
  }

**Comment by statianzo** [comment]
I ran into this yesterday. `user` was null as well. My workaround is to `refreshSession` immediately after `verifyOTP` returns. That response structure includes `expires_at ` as `_saveSession` expects (and `user` was populated).

```ts
await supabase.auth.verifyOTP({phone, token});

// Refresh to work around non-persistent OTP session
const { data, user, error } = await supabase.auth.refreshSession();
```
