### ISSUE TITLE
Migrate to cross-fetch

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue-js#12]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

At the moment this library uses Isomorphic Unfetch. We want to move it to [cross-fetch](https://github.com/lquixada/cross-fetch)

## Details

Bobbie just migrated `postgrest-js` to `cross-fetch`: https://github.com/supabase/postgrest-js/pull/109#issuecomment-701155061

We want to keep all the libraries consistent, so we should migrate this one too.

**Comment by izqalan** [comment]
this should be a quick one. I'll take a look.

**Comment by kiwicopple** [comment]
Closed by https://github.com/supabase/gotrue-js/pull/13
