### ISSUE TITLE
Provide intuitive response for when user needs to verify email address

### ISSUE THREAD

**Issue by dshukertjr** [supabase/gotrue-js#126]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently when a user signs up and if the email confirmation is enabled, the response from `signUp()` method does not contain any indication that the user needs to verify their email address. For someone who is just getting started, this causes a counter intuitive experience where you are receiving user info as a response, but the session is not persisted.

Yes there is a [description in the docs](https://supabase.io/docs/reference/javascript/auth-signup#notes) about this, but I think people might appreciate if the SDK could provide intuitive message or parameter to easily find out that they need to verify the email address. 

So in this issue, I want to discuss two things:
1. Should we implement a parameter or something to indicate that the user needs to verify their email address upon sign up, or is the current situation good enough since it is stated in the docs?
2. If we would to implement something, how should we go about it?

Related https://github.com/supabase/gotrue-dart/issues/32

## Describe the solution you'd like

Possible implementation proposed by @vHanda [here](https://github.com/supabase/gotrue-dart/issues/32#issuecomment-906639397) is to add a `emailVerificationRequired` parameter to the return value of `signUp()`. 

## Describe alternatives you've considered

I guess alternative would be to guide people to reading the documentation. 

## Additional context

N/A

**Comment by kangmingtay** [comment]
this is a good suggestion! we've added this to our internal backlog - currently, the way to tell if a user needs email confirmation is to check the `email_confirmed_at` field in the user object returned. If the `email_confirmed_at` field is missing, then it means that the user has yet to confirm their email.

Going forward, it would be alot more useful to have an explicit status such as `email_verified: false`.
