### ISSUE TITLE
Reset password link broken for expo

### ISSUE THREAD

**Issue by vbylen** [supabase/gotrue-js#144]
# Feature request

## Is your feature request related to a problem? Please describe.

When sending a reset password email:

```jsx
const { data, error } = supabase.auth.api.resetPasswordForEmail('user@email.com')
```

the returned link looks like:

```
https://jwpgcjpssmjfggggeegqlz.supabase.co/auth/v1/verify?token=KqjDGb-JA1xpLbOpI-jyZQ&type=recovery&redirect_to=mymobileapp://resetpassword
```
This  correctly opens the mobile app with path `mymobileapp://resetpassword`.

However, after the app is opened  there is no way to access the query params `token` and `type.`

I'm using the following code to listen to the url:

```jsx
function urlRedirect(url) {
    if(!url) return;
    let { path, queryParams } = Linking.parse(url);
}
Linking.addEventListener('url', event => {
    urlRedirect(event.url);
});
```

`path` returns 'resetpassword',
`queryParams` returns null.

## Describe the solution you'd like

Send a link in the following format:

```
mymobileapp://resetpassword?token=KqjDGb-JA1xpLbOpI-jyZQ&type=recovery
```

**Comment by 10000multiplier** [comment]
@kiwicopple thanks. 

I'm going to try to submit a pull request. 

I really want to use supabase in my react native app.

**Comment by scarsam** [comment]
Did this ever get solved @10000multiplier?

**Comment by 10000multiplier** [comment]
> Did this ever get solved @10000multiplier?

@scarsam No I'm still redirecting to my website and manually transforming the url there.

**Comment by nainglynndw** [comment]
I am OK with that

```
function _handleOpenUrl(event) {
    const url = event.url.replace("#", "?");   // replace # with ?  to use parse
    const obj = Linking.parse(url);              //parse url
    const str = JSON.stringify(obj);            // JSON stringify to store in context storage
    setItem(str)                                          //store in context storage ( in my case I store in asyncstorage )
  }

  useEffect(() => {
    Linking.addEventListener("url", _handleOpenUrl);
    return () => {
      Linking.removeEventListener("url", _handleOpenUrl);
    };
  }, []);
```

**Comment by hf** [comment]
Why do you need access to the token? @nainglynndw 

(Given that this issue has been inactive for a while I'll close it but feel free to continue discussing or re-open it.)

**Comment by gollodev** [comment]
I have this issue now, do you think this could be solved?
