### ISSUE TITLE
Running an app in an iframe when third party cookies are disabled

### ISSUE THREAD

**Issue by baptisteArno** [supabase/gotrue-js#148]
# Bug report

## Describe the bug

When instantiating an app in an iframe when the browser has third party cookies disabled (Chrome incognito mode option), it crashes when calling `new GoTrueClient(...)` with the following error:

```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Embed an app that uses the Gotrue SDK in a website that has a different origin
2. Launch it on a browser that has third party cookies disabled: Brave or Chrome in incognito mode
3. See error

**Comment by homanp** [comment]
Any updates on this? Struggling with the same issue in my Shopify app, needs to work in incognito without the thrid-party cookies activated.

**Comment by baptisteArno** [comment]
Nope... no solution

**Comment by homanp** [comment]
> Nope... no solution

I ended up moving everything to the server side to mitigate this issue.

**Comment by hf** [comment]
Hey this is a bit out-of-scope as there's little point in using Auth in a setting where the user has expressed that they do not want any cookies or storage to be used with them.

A workaround is to detect this situation and initialize the client without a persisted session or implement your own storage provider. See the [`GoTrueClientOptions`](https://supabase.github.io/gotrue-js/v2/modules.html#GoTrueClientOptions) interface for more information.
