### ISSUE TITLE
Update phone number with `auth.update`

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/gotrue-js#154]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm using Supabase for authentication and I don't need a separate `public.users` table so I'm just using `auth.users` (as all the information that I need is stored there). I sign-in users using Google but then I allow them to put in their phone number to receive invite codes. But, I don't want Supabase to send them anything--I want to control sending the invite codes (which are codes that will be submitted by other new users to gain access to my product) myself but still register the phone number with Supabase in `auth.users`.

## Describe the solution you'd like

I should be able to update the `phone` property using the `auth.update()` method:

```javascript
await supabase.auth.update({ phone: '+16508612723' });
```

## Describe alternatives you've considered

I can directly update the row in `auth.users` instead.

**Comment by kangmingtay** [comment]
Hey @nicholaschiang, this has been completed! We've included the `phone` field in the [`UserAttributes`](https://github.com/supabase/gotrue-js/blob/bcf1c73523843403cdf1c5d0ca0482cf289576c1/src/lib/types.ts#L98) type so you should be able to use the `update` method to add / update a user's phone number.
