### ISSUE TITLE
Redirect using `location.assign()` instead of `location.href`

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/gotrue-js#155]
# Feature request

## Is your feature request related to a problem? Please describe.

During testing, it's practically impossible to stub out `location.href` (see [this](https://stackoverflow.com/questions/43568570/how-can-i-get-window-location-pathname-on-my-test-file-using-jest/56651910#56651910) and [this](https://stackoverflow.com/questions/36678302/stubbing-window-location-href-with-sinon) among other resources out there) due to--what I'm guessing--are valid security concerns from browser developers.

## Describe the solution you'd like

I would like to be able to stub out Supabase's OAuth2 redirects so I can ensure that they're happening while not actually visiting the 3rd party website during integration tests.

To do this, Supabase should use [`location.assign()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/assign) instead of `location.href` (it does exactly the same thing and has the same browser support).

## Describe alternatives you've considered

No idea. I'm at a loss here. I can't figure out how to stub `location.href` so this is the best (and only) solution.

**Comment by nicholaschiang** [comment]
@awalias any ideas on how to stub out Supabase's `window.location` redirects during testing?

**Comment by hf** [comment]
Will be fixed with #573. Thanks for this!
