### ISSUE TITLE
Support id_token grant flow

### ISSUE THREAD

**Issue by dshukertjr** [supabase/gotrue-js#169]
# Feature request

## Is your feature request related to a problem? Please describe.

A new way of signing users in via OAuth was introduced with [this](https://github.com/supabase/gotrue/pull/189) PR of gotrue. It would be nice if we could add a way of utilizing this endpoint with this library so that native apps built with react native could utilize it. 

## Describe the solution you'd like

OAuth sign in flow on native apps should use `POST /token?grant_type=id_token` end point to sign in. 

## Describe alternatives you've considered

Currently OAuth sign in is possible by redirecting the user to web view from a native app. 

## Additional context

N/A

**Comment by megacherry** [comment]
@dshukertjr Hi Tyler, do you know when this feature will be integrated? or do you have a rough timeline? thanks in advance, Andy

**Comment by dshukertjr** [comment]
@megacherry Great question! 

@kiwicopple Now that the backend is ready for this, do we have anything else that needs to be in place before we add this feature to the client?

**Comment by phamhieu** [comment]
cc @kangmingtay

**Comment by megacherry** [comment]
@dshukertjr Do you have any new information about this issue? :)

**Comment by koba-ninkigumi** [comment]
@kiwicopple @kangmingtay @phamhieu @dshukertjr @megacherry

I have created a pull request that resolves this issue.
Please review and merge.

**Comment by DanMossa** [comment]
It looks like your pr was merged in ? Should this be closed now?
@koba-ninkigumi

**Comment by hf** [comment]
Closing as this is already supported.
