### ISSUE TITLE
Allow createClient() to use user's jwt without the need for anon key

### ISSUE THREAD

**Issue by kk21** [supabase/gotrue-js#186]
# Feature request

## Is your feature request related to a problem? Please describe.

Allow createClient() to use user's jwt so that the client does not need anon key:
`const supabase = createClient(url, user's jwt);`

Currently this will not work for Realtime which gives repeated WebSocket connection failed errors.

Just to provide more context, my web client gets the user's jwt by signing in indirectly through my own custom API server, so it does not need the anon key to call Supabase API.

## Describe the solution you'd like

Allow createClient() to use user's jwt without the need for anon key.

## Describe alternatives you've considered

Currently the solution is to use anon key for createClient(), followed by:
`supabase.auth.setAuth(user's jwt)`

**Comment by hf** [comment]
Hey @kk21, this was intentional in v1. You can think of the anon key more as an API key rather than a substitute for a user's JWT. We don't plan on changing the behavior to keep it consistent across the other Supabase JS client libraries.
