### ISSUE TITLE
Add the listUser admin endpoint 

### ISSUE THREAD

**Issue by kangmingtay** [supabase/gotrue-js#187]
# Bug report
* Currently, the `supabase.auth.api.getUser('access_token_jwt')` maps to the `GET /user` endpoint in gotrue. However, there is not corresponding method for the `GET /admin/user/<user_id>` endpoint.

# Solution
* We should create a method `supabase.auth.api.listUser()` that requires the `service_role` key. This method should only be used on the server-side since it requires the `service_role` key.
* To prevent confusion between `supabase.auth.api.getUser('access_token_jwt')` and `supabase.auth.api.listUser()`, we can probably move the former to `supabase.auth.getUser('access_token_jwt')` to indicate that this method is safe to call on the client-side. 
* This also makes it consistent with the rest of the server-side methods (i.e. `supabase.auth.api.[...]`) that require the `service_role` key.

**Comment by kangmingtay** [comment]
cc @thorwebdev @awalias

**Comment by thorwebdev** [comment]
Sounds good to me. Seeing the we have `getUserByCookie` should we rather call it `getUserById`? Or would `listUser` also allow me to list all users when I don't provide an ID?

**Comment by dthyresson** [comment]
> Sounds good to me. Seeing the we have `getUserByCookie` should we rather call it `getUserById`? Or would `listUser` also allow me to list all users when I don't provide an ID?

@thorwebdev i prefer `getUserById`   — any method with “list” to me implies an array response with multiple items. 

This opens up other find by’s like by email or by phone number.

Another option following Prisma’s naming info is `findUnique` where options would be if or email or phone; any unique key.

That said, I think I could see a need to list users — say to send everyone an email — but I think I would do that using views with filter conditions or a function to iterate over each.

**Comment by bnjmnt4n** [comment]
FYI there is already an `auth.api.listUsers()` method: https://github.com/supabase/gotrue-js/blob/de87da1f739920e10313c169ef3b4faba459d9c7/src/GoTrueApi.ts#L56-L70
