### ISSUE TITLE
How user can recover password if user is authenticate with phone number?

### ISSUE THREAD

**Issue by Rayyanmaq1** [supabase/gotrue-js#200]
I have authenticate user from phone number and password now I'm facing a issue that I can't recover password if user have forgotten it.

**Comment by kangmingtay** [comment]
Thanks for raising this up @Rayyanmaq1, we should create a function on gotrue-js to handle password resets for phone and password signups. 

Currently, a workaround for this would be to use the `signIn({phone})` method which will send an otp to the user's phone number. From there, you can use the `verifyOTP` [method](https://github.com/supabase/gotrue-js/blob/862996337c38876eaefead036871ea10df2e27bd/src/GoTrueClient.ts#L259) to verify the otp and sign the user in.

Once the user is signed in, they can reset their password by updating it via the [updateUser](https://github.com/supabase/gotrue-js/blob/862996337c38876eaefead036871ea10df2e27bd/src/GoTrueApi.ts#L768) endpoint

**Comment by Rayyanmaq1** [comment]
I know this but if user is authenticated with phone number and password if he want to reset the password how he can do it.

**Comment by kangmingtay** [comment]
Hey @Rayyanmaq1, please let us know if you're still facing this problem, as mentioned, if you wish to reset a user's password through a phone number, these are the following steps:

1. Sign-in the user with phone OTP
2. Redirect the user to a reset password page
3. Call the update method or updateUser (if you're using v2) to update the user's password.
