### ISSUE TITLE
Refresh Token revocation span sessions leading to un-determined authentication states

### ISSUE THREAD

**Issue by dthyresson** [supabase/gotrue-js#201]
# Bug report

First, my understanding about gotrue-js and how refresh tokens work is:

* On login, when an access token is granted a refresh token is generated and provided to the client
* This refresh token is assigned to the user and stored in the `auth.refresh_tokens` table with a `revoked` status (true/false) and some timestamps
* The access token is valid until it expires and that expiration duration interval is set in auth settings, defaults to 3600 seconds (1 hour)
* On login, the client starts a timer to auto refresh the token (there is an `authRefreshToken` config setting on the client and Supabase defaults this to true).
* About 60 seconds before the token expires, the refresh token handler is invoked and a new access token is generated
* The old refresh token is revoked (its status in the table is changed) and a new token is added with a reference to the old (parent)
* Happy path is that the token **can be refreshed** and a new access token is created with an updated expiration such that any subsequent server-side verification of the JWT will consider it valid (unexpired)

But -- what happens if the tokens **cannot** be refreshed ... and how might someone get themselves into this state?

## Scenario 1 - Same Login User, Two Browsers and Multiple "Sessions"

One way this can happen is to login using two browsers: one Chrome and one Safari, then logout from within Chrome and see what happens to the Safari sessions.

### Steps

This assumes you already have a valid signed up Supabase user and know the credentials.

Also, JWT expiration is set to 120 seconds (two minutes for easy testing).

These use RedwoodJS and the latest Supabase gotrue-js in the Auth Playground local dev testing..

For this we'll user User `9cb11b1f-6a3d-4c94-9280-41af55ed1dc9`

![image](https://user-images.githubusercontent.com/1051633/147617758-dac43f35-bce9-4b3c-996a-7a94b645de2d.png)

1. Launch Chrome and login

![image](https://user-images.githubusercontent.com/1051633/147617807-cd6f708a-a7b4-4abc-9d7a-0fa992c426ed.png)

Every 20 seconds of so we make a query using the JWT and can see it return successfully

![image](https://user-images.githubusercontent.com/1051633/147617856-4d62a17b-d10b-413d-96cf-22cfa534d091.png)

After waiting a few minutes you can see we have several refresh tokens for this login and user (some revoked and some active)

![image](https://user-images.githubusercontent.com/1051633/147617913-c4ef5b9a-c2ca-449a-8044-b6aa43ea781a.png)

2. Launch Safari
3. Login with same user in two tabs

![image](https://user-images.githubusercontent.com/1051633/147618468-44495da7-21de-4177-8ac4-9448bee082f7.png)

4. Now we have three active non-revoked tokens
![image](https://user-images.githubusercontent.com/1051633/147617948-c072e29d-dbe7-4dd1-bdde-53438faa2fd3.png)

5. And our server side queries with the token are still valid

![image](https://user-images.githubusercontent.com/1051633/147617981-f7de1c02-c0d1-4df8-9733-bd663e5faf0c.png)

And my get refresh tokens do succeed...

![image](https://user-images.githubusercontent.com/1051633/147618090-95abbb4d-93e9-49ef-8928-bb05bd5ec03d.png)

6. Log out from Chrome

Before -- still 3 un-revoked

![image](https://user-images.githubusercontent.com/1051633/147617994-a89625bf-9566-4fe9-835c-ea46050335b9.png)

But now after I logged out from Chrome, **all** were deleted

![image](https://user-images.githubusercontent.com/1051633/147618008-7666f7f9-1f6d-4ac2-97f4-1fae255b4a9a.png)

7. Looking back in Safari, I am still logged in ... 
But now my refresh token requests are failing

![image](https://user-images.githubusercontent.com/1051633/147618032-951c9e32-83b4-4736-be05-f12fcbd65107.png)

```
{
    "error": "invalid_grant",
    "error_description": "Invalid Refresh Token"
}
```

And now since it has been over two minutes, my Safari session still has an access token .. but it's old.

![image](https://user-images.githubusercontent.com/1051633/147618132-5d31c2ad-ad44-4455-8aa4-bfbc77e2855f.png)

And my server-side verification is failing:

![image](https://user-images.githubusercontent.com/1051633/147618144-6a3b1a0c-c03e-4245-836c-e6c385e171e2.png)

9. There's no way to get my Safari session back working unless I logout and in again/

10. But, if I log out from Tab 1
![image](https://user-images.githubusercontent.com/1051633/147618235-405beadd-5c3e-46c2-851d-ab8106aa4bb1.png)

11. Then I am still logged in with tab 2

![image](https://user-images.githubusercontent.com/1051633/147618252-e0e42ca3-9ea8-4c31-8587-64ba8711151d.png)

#### Mitigation

For Steps 10 and 11 you can using the auth client watch the event

```
  supabaseClient.auth.onAuthStateChange(async (event) => {
    if (
      // event === 'SIGNED_IN' ||
      event === 'SIGNED_OUT'
      // event === 'TOKEN_REFRESHED'
    ) {
      console.debug('>> in onAuthStateChange', event)
      await reauthenticate()
    }
  })
```

And in Redwood reauthenticate and thus log out from multiple tabs. That works.

### Revoke per session

* Store refresh tokens per something associated with a browser session. Maybe some user agent info?
* Revoke individually - so Google logout but Safari is ok.

### Revoke Global

* Since all tokens are deleted then either handle the error on token refresh, warn and sign them out but broadcast some event to the client can clear any auth state

### More events

* Let client subscribe to token refreshed or token revoked event
* Handle auth state

### More documentation

* Docs about how to handle auth state changes with sample code

**Comment by hf** [comment]
Hey @dthyresson, we're planning on adding a proper session control API to GoTrue in the short-term (as we finish up our priorities for MFA and SAML support). With that I believe much of the confusing behavior will get resolved.

Furthermore, we've identified some issues with the refresh token flows especially if used in a server-side or multi-tab use case and are working on a fix. See #445 for that.

Since this issue has been open since Dec 29, 2021 without much activity on it, I'll close it as stale but do comment or re-open it if you feel like this has not been sufficiently fixed.
