### ISSUE TITLE
Recently Visited List on the home screen shows entries even if it is deleted/removed from the history

### ISSUE THREAD

**Issue by MohitMandalia** [supabase/gotrue-js#202]
## Describe the bug

Recently Visited List on home screen shows entries even if it is deleted from the history , whereas recently bookmarked gets removed if you remove from bookmark so a consistent behavior should be applied for all the list on home screen.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Home Page'
1. Visit more than one website.
1. Go back to 'Home Page', observe the 'Recently Visited' List
2. Click on 'Show All'
3. Delete by clicking on 'x' for a particular item.
4. Go Back to Home Page and notice the deleted history for a particular website is still listed.

## Expected behavior

Deleting from history should also delete recently visited entry.

## Screenshots

![f-2](https://user-images.githubusercontent.com/36087806/147640003-bf454d0c-a10f-461a-953b-b140b43f61d2.png)
![f-1](https://user-images.githubusercontent.com/36087806/147640004-8d6befaf-8668-47ec-bf84-84ad1a88d9a4.png)

## System information

- Android 12
- Google Pixel 4a

**Comment by MohitMandalia** [comment]
Hi,

Please let me know if I can work on it.

Thanks

**Comment by leynier** [comment]
@MohitMandalia wrong repo, right?

**Comment by MohitMandalia** [comment]
> @MohitMandalia wrong repo, right?

Yes wrong repo I am sorry @leynier

**Comment by leynier** [comment]
> > @MohitMandalia wrong repo, right?
> 
> Yes wrong repo I am sorry @leynier

No problem at all, regards.
