### ISSUE TITLE
GoTrue JS Client sends incorrect content-type in the request header

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue-js#205]
# Bug report

## Describe the bug

The network requests generated from calls to ```signUp()```, ```signIn()``` and ```generateLink()``` send the following request header:
```
content-type: text/plain;charset=UTF-8
```

However, the payload of the requests is JSON so the content-type header seems incorrect. 

NOTE: I have NOT tested the other methods in the GoTrue JS client (e.g. signOut, etc) - they might suffer from the same issue.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Init supabase js client: 
2. Send a sign-up request via the client: ```await supabase.auth.signUp({ email, password });```

## Expected behavior

The request to ```https://projectid.supabase.co/auth/v1/signup``` contains a request header ```content-type: application/json```

## Actual behavior

The request to ```https://projectid.supabase.co/auth/v1/signup``` contains a request header ```content-type: text/plain;charset=UTF-8```

## System information

- Supabase JS version: 1.28.5
- GoTrue JS version: 1.21.7

**Comment by hf** [comment]
Closing since this has been fixed with PR #429 and already fixed in v2. Thanks @TeeWallz!
