### ISSUE TITLE
Have `setAuthCookie` return void or an error instead of responding to the http request

### ISSUE THREAD

**Issue by kiyadotdev** [supabase/gotrue-js#206]
# Feature request

## Is your feature request related to a problem? Please describe.

The `auth.api.setAuthCookie` method seems to only work for `Next.js` and `Express` as stated in the comment [here](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L376-L380). 

When using other web frameworks, there are a few issues. For example, `Fastify` web framework doesn't have a `res.setHeader` method so [this](https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/lib/cookies.ts#L155) fails. Or if one is to use `Node.js` http server, `res.status` fails [here](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L400)

## Describe the solution you'd like

A solution that I see would work is to not return the http request within the `auth.api.setAuthCookie` method. Rather have it return an error or void and let the developer handle returning the http request. 

This would allow `setAuthCookie` to do its cookie setting/deleting and also allow any web framework to use this method with no issues.

**Comment by thorwebdev** [comment]
Hm, unfortunately that would be a breaking change for `setAuthCookie`. @kiyadotdev what do you think about a new helper method with the following shape? 

```ts
generateAuthCookieString(req, res): string
```

For Fastify you could then do:

```js
fastify.get('/', options, function (request, reply) {
  // Your code
  reply
    .code(200)
    .header('Set-Cookie', generateAuthCookieString(request, reply))
    .send({ hello: 'world' })
})
```

Would that be a good DX for you?

**Comment by kiyadotdev** [comment]
@thorwebdev sorry for the late reply, thats perfect! thanks 💯
