### ISSUE TITLE
Revised state change events

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue-js#224]
# Feature request

When the JWT token is refreshed, 2 separate events are fired: ```SIGNED_IN``` and ```TOKEN_REFRESHED```.

I think it would be better if ONLY the ```TOKEN_REFRESHED``` event is fired when the token is refreshed.

## Is your feature request related to a problem? Please describe.

Firing both ```SIGNED_IN``` and ```TOKEN_REFRESHED``` events is problematic for 2 scenarios:

1. Calling 2 separate callbacks depending on the event - for example, a SPA app might want to implement a client-side redirect for the ```SIGNED_IN``` event but NOT for the ```TOKEN_REFRESHED``` event. Currently, this is NOT possible out of the box, because even when the token is just refreshed, the SIGNED_IN event is still fired.

2. Call the same callback for ```SIGNED_IN``` and ```TOKEN_REFRESHED``` evens, but only do it once per refresh - currently, if you have a callback which needs to take place both on ```SIGNED_IN``` and ```TOKEN_REFRESHED``` events (e.g. updating some user metadata such as permissions), this callback is called twice when the token is refreshed because both events are fired. This leads to unnecessary callback invocations.

## Describe the solution you'd like

Avoid firing the ```SIGNED_IN``` event when the token has been refreshed since there is already a dedicated event for that - ```TOKEN_REFRESHED```.

I assume, the reason for this is backwards compatibility, since originally only the ```SIGNED_IN``` event was dispatched when the token was refreshed and only later the ```TOKEN_REFRESHED``` event was introduced with https://github.com/supabase/gotrue-js/commit/0add6956a22c51c785d9d735edf38cac8a2c2368. However, it seems that in the long term, it's better to separate the 2 events and it makes sense to do the separation now while Supabase is still officially in BETA.

## Describe alternatives you've considered

A workaround would be to keep the signed-in state within a component and ignore any ```SIGNED_IN``` events if the internal state already indicates that the user is signed in.

## Additional context

supabase-js version: 1.28.5
gotrue-js version: 1.21.7

**Comment by hf** [comment]
Hey @chipilov, this is great feedback. Unfortunately a revision of the callbacks did not make it into v2 of this library. 

I'm adding this to our backlog, however I don't think there's much we can do to the existing callback. It is possible though that we introduce a revised version of the events (per your great suggestions) as an opt-in API in v2. For example, something like this:

```typescript
// to receive revised events
client.onAuthStateChanged('v2', () => { ... })

// to receive compatible events
client.onAuthStateChanged(() => { ... })
```

**Comment by chipilov** [comment]
@hf Adding an opt-in option makes sense to me in the short-term.

**Comment by kangmingtay** [comment]
i think we've fixed this in v2 - will close this issue for now!
