### ISSUE TITLE
Token refresh fails silently when offline and never recovers

### ISSUE THREAD

**Issue by jake-nz** [supabase/gotrue-js#226]
# Bug report

## Describe the bug
If the user is offline when their token expires then `_callRefreshToken` will fail. The failure is not handled well so there's no indication that there was a problem (except that the token no longer works) and there's no attempt to refresh again.

`_startAutoRefreshToken` uses `setTimeout(() => this._callRefreshToken(), value)`
`_callRefreshToken` does not throw errors, it returns them so the get ignored here. The token is not refreshed and a new timeout is not set.

Related: #141

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Log in
2. Go offline
3. Wait for token to expire
4. Go online
5. Try to use the token

## Expected behavior

* The error should not be silently swallowed
* There should be another attempt to refresh the token at a later time

**Comment by chipilov** [comment]
I think it would be nice if such failures (regardless of whether it's because you are offline or some other error) trigger a new event type (e.g. TOKEN_REFRESH_FAILED).
