### ISSUE TITLE
Add RedwoodJS example app to gotrue-js examples

### ISSUE THREAD

**Issue by dthyresson** [supabase/gotrue-js#239]
The gotrue-js library has several example apps.

Missing is a RedwoodJS example that uses 1) JWT localStorage 2) upcoming cookie support

The "playground-auth" https://github.com/redwoodjs/playground-auth example can be used as a guide for creating the Supabase example, but the example should be much more straightforward to do.

Additional features could include

* auth helpers
* Supabase UI

But these are not a priority.

**Comment by hf** [comment]
@dthyresson I believe this is done, no?
