### ISSUE TITLE
Allow OAuth signin in a popup window

### ISSUE THREAD

**Issue by PegasisForever** [supabase/gotrue-js#266]
# Feature request

Allow OAuth signin in a popup window

## Is your feature request related to a problem? Please describe.

1. Useful in a SPA where state is presisted only in memory, redirecting will lost all the state.
2. Useful when the webpage is embedded in a small iframe, a popup window is not restricted by the size of the iframe.
3. Useful when the webpage is embedded in a small iframe, some OAuth provider disallows their page to be displayed in an iframe

btw firebase auth already has this.

## Describe the solution you'd like

Add an `popup` option in the `signIn` function, when using an OAuth provider, the auth webpage will open in a popup, instead of redirecting.

**Comment by hf** [comment]
May just become slightly possible after #575 and #566 go in. Leaving open so we see if the API needs more tweaking.

**Comment by hf** [comment]
Actually let's move to #460.
