### ISSUE TITLE
Regression Error in v1.28.0

### ISSUE THREAD

**Issue by steinroe** [supabase/gotrue-js#267]
# Bug report

## Describe the bug

This bug report is to shine light on a probable regression error introduced in https://github.com/supabase/supabase-js/compare/v1.27.0...v1.28.0 which leads to a session invalidation on refresh. The client then defaults to the anon key.

Related issues and discussions:
https://github.com/supabase/supabase/discussions/6080
https://github.com/supabase-community/supabase-auth-helpers/issues/52
https://github.com/supabase/supabase/issues/5852

## To Reproduce

The easiest way to reproduce is to create context that uses the authenticated client to fetch extra user information. Happy to create a repro repo if required.

## Expected behavior

Session should not be invalidated after a refresh and user token should be used.

## Additional context

Since this basically prevents the use of supabase-auth-helpers it would be great if this would get some attention.

**Comment by thorwebdev** [comment]
@steinroe I'm not able to reproduce this with `gotrue-js:1.22.12`. Could you please create a repo to reproduce? This is the code I'm using: https://github.com/vercel/nextjs-subscription-payments/blob/main/utils/useUser.tsx#L43-L59 and it's loading my user data correctly with the user's token.

**Comment by steinroe** [comment]
@thorwebdev We finally got behind our problem. It was entirely on our side: We set the Vercel envs in our cd pipeline using 
`echo ${{ secrets[env.SUPABASE_ANON_KEY_SECRET_NAME] }} | vercel env add. NEXT_PUBLIC_SUPABASE_ANON_KEY $VERCEL_ENVIRONMENT $VERCEL_BRANCH --token=${{ secrets.VERCEL_TOKEN }}`

which lead to a newline character being appended to the env on Vercel. This wasn't a problem so far since we loaded all envs with `.trim()` and forgot about it. To fix it, we simply added the -n option to echo:
`echo -n ${{ secrets[env.SUPABASE_ANON_KEY_SECRET_NAME] }} | vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY $VERCEL_ENVIRONMENT $VERCEL_BRANCH --token=${{ secrets.VERCEL_TOKEN }}`

Once again, sorry for taking your time. Keep up the good work!
