### ISSUE TITLE
Add ability to set non persistent custom claims on JWTs

### ISSUE THREAD

**Issue by mgm1313** [supabase/gotrue-js#268]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm trying to implement multi-tenancy - where a single auth user can belong to multiple tenants - in my app. I want to implement some kind of session state, so that a user can select the context for the single tenant they want to view the data of on a per session basis. 
For this I'm thinking of setting a temporary custom claim in the JWT. With temporary I mean it's not persisted to the auth user object (e.g. stored in the `auth.users` table). 

More details in this discussion https://github.com/supabase/supabase/discussions/6301 

## Describe the solution you'd like

Introduce a new function that operates the same way as the current way we can update the [users's metadata](https://supabase.com/docs/reference/javascript/auth-update#update-a-users-metadata), but in a not persisted manner. 

## Describe alternatives you've considered

I could [mint my own JWT's](https://github.com/supabase/gotrue/issues/277), but since I guess more people might have this use case of this per-session state it might be more convenient if this library would accommodate it.

**Comment by hf** [comment]
Hey @mgm1313 (and :+1:-ers @reyhann, @dinvlad),

Access tokens, which have the form of a JWT, are meant to be very short lived tokens. In the default Supabase Auth setting their expiration time is 1 hour. Industry best practice recommends having them as short as possible, typically 5 or 10 minutes. From that point of view it does not make any sense to customize the access token with data that is not persisted in the database, as the data would only be "around" until the access token expires.

We've already released rudimentary session support, however in the near future the feature set will grow and we'll consider adding session metadata support that will appear in all JWTs so long as the session is valid.

I'll close this issue for now, but feel free to comment or offer suggestions afterwards.

(P.S. This feels like an issue that should live in [gotrue](https://github.com/supabase/gotrue so I'll move it there.)
