### ISSUE TITLE
Make the return type of GoTrueApi functions appropriate

### ISSUE THREAD

**Issue by elpnt** [supabase/gotrue-js#269]
# Feature request

## Is your feature request related to a problem? Please describe.

I need to authorize users on Next.js API Route and use `supabase.auth.api.getUserByCookie` like this

```ts
import { NextApiRequest, NextApiResponse } from 'next';

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  const { user, error } = await supabase.auth.api.getUserByCookie(req);

  if (error) {
    res.status(401).json({ error: error.message });
  } else {
    someFunc(user);  // handle user
  }
}
```

In the `else { ... }` closure `user` must be `User` and `error` is `null`, but in fact `user` is `User | null`.
This comes from the definition of `getUserByCookie` https://github.com/supabase/gotrue-js/blob/50141610ad4b071eee722e9657a0921f41b29a1f/src/GoTrueApi.ts#L692-L700

The return type of `getUserById` in the same file seems ok
https://github.com/supabase/gotrue-js/blob/50141610ad4b071eee722e9657a0921f41b29a1f/src/GoTrueApi.ts#L675-L677 

```ts
const { data, error } = await supabase.auth.api.getUserById('USER_ID')
if (error) {
  // Handle error
} else {
  // Handle data
  // We don't have to worry that `data` might be `null`
  const { email } = data; // `data` is `User`
}
```

## Describe the solution you'd like

Rewrite the code so that expected data and error in the return value of `getUserByCookie` (and some other functions) are mutually exclusive.
Can i work on this?

**Comment by hf** [comment]
Hey @elpnt,

Thanks for the suggestion. We decided to rework the client library and are going to release v2 soon (checkout the `next` branch), where we've completely refactored this method.

Furthermore, we're going to be coming out very soon with a guide on how to properly do server-side rendering with Supabase Auth as this has been a common source of confusion for many users.

I'll close this issue as stale, feel free to reopen it if you're facing the same issue still.
