### ISSUE TITLE
Token refresh does not work

### ISSUE THREAD

**Issue by guido4000** [supabase/gotrue-js#27]
Setting up a nextjs app with supabase based on the example in the supbase repository, I get a functioning app, but the token refresh does not seem to work. After one hour the user is being logged out as the token is not valid anymore.

https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth

**Comment by guido4000** [comment]
This solved the problem half-way for me. After one hour I still get a problem accessing an API route as the auth call in the API route ` await supabase.auth.api.getUser(token);` does fail. Only after reloading the app a token refresh is being triggered.

**Comment by thorwebdev** [comment]
@guido4000 this is something I'm working on as part of https://github.com/supabase/gotrue-js/pull/33. Also, I'd love to get your feedback on the proposed SSR experience there.

**Comment by guido4000** [comment]
@thorwebdev  
The API looks great. 

For the Next.js SSR example it would nice to see the use of SWR in the pages/profile.js route similar to pages/index.js.

https://github.com/vercel/swr#ssr-with-nextjs

**Comment by snax4a** [comment]
I'm also experiencing this issue, after one hour when I call:
```tsx
await supabase.auth.api.getUser(session.access_token)
```

In my UserContext i am subscribing to onAuthStateChange event so when the token is refreshed i should be getting fresh session object.
```tsx
  useEffect(() => {
    const session = supabase.auth.session()

    setSession(session)
    setUser(session?.user ?? null)
    setSessionLoading(false)

    const { data: authListener } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        setSession(session)
        setUser(session?.user ?? null)
      }
    )

    return () => {
      authListener?.unsubscribe()
    }
  }, [])
```

I can't find any info in docs about how can i manually refresh tokens in supabase auth

**Comment by snax4a** [comment]
> > I can't find any info in docs about how can i manually refresh tokens in supabase auth
> 
> Hi @snax4a while I don't see this method documented on the Supabase API reference, perhaps the `refreshSession()` might work for you?
> 
> See:
> 
> https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/GoTrueClient.ts#L310
> 
> You can see a test here:
> 
> ```ts
>  test('refreshSession() forces refreshes the session to get a new refresh token for same user', async () => {
>       const { email, password } = mockUserCredentials()
> 
>       const { error: initialError, session } = await authWithSession.signUp({
>         email,
>         password,
>       })
> 
>       expect(initialError).toBeNull()
>       expect(session).not.toBeNull()
> 
>       const refreshToken = session?.refresh_token
> 
>       const { error, user, data } = await  test('refreshSession() forces refreshes the session to get a new refresh token for same user', async () => {
>       const { email, password } = mockUserCredentials()
> 
>       const { error: initialError, session } = await authWithSession.signUp({
>         email,
>         password,
>       })
> 
>       expect(initialError).toBeNull()
>       expect(session).not.toBeNull()
> 
>       const refreshToken = session?.refresh_token
> 
>       const { error, user, data } = await authWithSession.refreshSession()
> 
>       expect(error).toBeNull()
>       expect(user).not.toBeNull()
>       expect(data).not.toBeNull()
> 
>       expect(user?.email).toEqual(email)
>       expect(data).toHaveProperty('refresh_token')
>       expect(refreshToken).not.toEqual(data?.refresh_token)
>     })()
> 
>       expect(error).toBeNull()
>       expect(user).not.toBeNull()
>       expect(data).not.toBeNull()
> 
>       expect(user?.email).toEqual(email)
>       expect(data).toHaveProperty('refresh_token')
>       expect(refreshToken).not.toEqual(data?.refresh_token)
>     })
> ```
> 
> Demo that `refreshSession()` will create new refresh token on the user's session.
> 
> Could this work for you?

Thanks for your reply, I can successfully refresh session using ```supabase.auth.refreshSession()```
In every supabase query I'm doing the following:
```tsx
  if (error) {
    if (error.message?.includes('JWT expired')) {
      await supabase.auth.refreshSession()
    }
    throw new Error(error.message)
  }
```

However, I wonder why supabase-js library is not refreshing it automatically

**Comment by dthyresson** [comment]
> > > I can't find any info in docs about how can i manually refresh tokens in supabase auth
> > 
> > 
> > Hi @snax4a while I don't see this method documented on the Supabase API reference, perhaps the `refreshSession()` might work for you?
> > See:
> > https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/GoTrueClient.ts#L310
> > 
> > You can see a test here:
> > ```ts
> >  test('refreshSession() forces refreshes the session to get a new refresh token for same user', async () => {
> >       const { email, password } = mockUserCredentials()
> > 
> >       const { error: initialError, session } = await authWithSession.signUp({
> >         email,
> >         password,
> >       })
> > 
> >       expect(initialError).toBeNull()
> >       expect(session).not.toBeNull()
> > 
> >       const refreshToken = session?.refresh_token
> > 
> >       const { error, user, data } = await  test('refreshSession() forces refreshes the session to get a new refresh token for same user', async () => {
> >       const { email, password } = mockUserCredentials()
> > 
> >       const { error: initialError, session } = await authWithSession.signUp({
> >         email,
> >         password,
> >       })
> > 
> >       expect(initialError).toBeNull()
> >       expect(session).not.toBeNull()
> > 
> >       const refreshToken = session?.refresh_token
> > 
> >       const { error, user, data } = await authWithSession.refreshSession()
> > 
> >       expect(error).toBeNull()
> >       expect(user).not.toBeNull()
> >       expect(data).not.toBeNull()
> > 
> >       expect(user?.email).toEqual(email)
> >       expect(data).toHaveProperty('refresh_token')
> >       expect(refreshToken).not.toEqual(data?.refresh_token)
> >     })()
> > 
> >       expect(error).toBeNull()
> >       expect(user).not.toBeNull()
> >       expect(data).not.toBeNull()
> > 
> >       expect(user?.email).toEqual(email)
> >       expect(data).toHaveProperty('refresh_token')
> >       expect(refreshToken).not.toEqual(data?.refresh_token)
> >     })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Demo that `refreshSession()` will create new refresh token on the user's session.
> > Could this work for you?
> 
> Thanks for your reply, I can successfully refresh session using `supabase.auth.refreshSession()` In every supabase query I'm doing the following:
> 
> ```tsx
>   if (error) {
>     if (error.message?.includes('JWT expired')) {
>       await supabase.auth.refreshSession()
>     }
>     throw new Error(error.message)
>   }
> ```
> 
> However, I wonder why supabase-js library is not refreshing it automatically

Hi @snax4a there is a timer that will refresh the token. See

https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/GoTrueClient.ts#L680

If `autoRefreshToken` is true (which should be the default) then when

https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/GoTrueClient.ts#L645

if called a timer starts and should refresh before the session expires -- as long as there is an expires.

But from what I can see `setSession` would start that timer.

**Comment by dthyresson** [comment]
But glad it's working for you. All best.
