### ISSUE TITLE
Export types for use by downstream librarys

### ISSUE THREAD

**Issue by calendee** [supabase/gotrue-js#28]
# Feature request

## Is your feature request related to a problem? Please describe.

Yes. Because the gotrue-js types are not exported, they can't be used in downstream library.

## Describe the solution you'd like

Export all types by default.

## Describe alternatives you've considered

None

## Additional context

This feature requested will be followed by an additional request to the supabase-js library so that all necessary types (gotrue, supabase, realtime) are available in TypeScript projects.

**Comment by kiwicopple** [comment]
Fixed by @calendee here  https://github.com/supabase/gotrue-js/pull/29
