### ISSUE TITLE
`secure` as a `CookieOption`

### ISSUE THREAD

**Issue by Perfecto-always** [supabase/gotrue-js#280]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to have my `sameSite` attribute set to `none` but this is not happening because `CookiesOption` & `GoTrueClient` Api doesn't have a option to set `secure` attribute.

## Describe the solution you'd like

An option to set `secure` attribute

Idk if its already implemented or there is even a work around, if there is any please share. Thanks for help in advance 🙏

**Comment by bhvngt** [comment]
This will be very helpful in passing cookies to the server after 'oAuth' call back. 

Currently, 'same-site' is blank. With [recent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#values) changes, browser treat this as 'lax' and hence are not sending it to cross domain server. 

As of now, 'same-site' can be 'none' only if it is 'secure'.

Without this feature, an extra trip is required from the client side to send the cookies to the server.

**Comment by bhvngt** [comment]
While peeking into the code, I realise that the cookie setting for `oauth callback` is done at [gotrue](https://github.com/supabase/gotrue/blob/c9f1ed5731b102a40bae113e972c0e7674a9195b/api/token.go#L587) repo.

Hence, the oAuth issue that I had raised belongs to `gorue` repo. Will file a separate ticket there.

**Comment by hf** [comment]
We no longer recommend the use of `sb-access-token` and `sb-refresh-token` cookies. Please read our latest [server side rendering](https://supabase.com/docs/guides/auth/server-side-rendering) document to understand best practices for accessing access and refresh tokens on the server.
