### ISSUE TITLE
:label: User missing `email_change_sent_at` and `new_email` properties

### ISSUE THREAD

**Issue by AlbinoGeek** [supabase/gotrue-js#283]
# Bug report

## Describe the bug

The `Session.User` type is missing the following parameters (and possibly more):

`email_change_sent_at`
`new_email`

Thesea are used in the Email Change request flow.

## To Reproduce

1. Use `@supabase/supabase-js`
2. Access `session?.user?.email_change_sent_at`
3. All your builds and tests will now fail.

## Expected behavior

The typings should include these properties, they're necessary for showing user feedback during email change.

## Screenshots

![image](https://user-images.githubusercontent.com/1910461/167275986-7760785f-d9cc-467f-9afe-a8b7fa8af47f.png)

## System information

- OS: Fedora 35 Workstation Linux
- Version of supabase-js: `1.35.2`
- Version of Node.js: `16.14.0`

**Comment by eluce2** [comment]
This issue is not fixed for me. It appears they are added on the types, but if these fields are not included in the JWT, they still may not be accessible.

We are using magic link email login if that helps

**Comment by kangmingtay** [comment]
@eluce2 which fields are you looking for? the `new_email` and `email_change_sent_at` fields will only be present in the JWT if it's an email change request not a magic link email login.

**Comment by eluce2** [comment]
After the user logs in, their email is associated with an account. If they want to change that email, I call the `auth.updateUser()` function. Shouldn't I be able to call `useUser()` and get back enough data to display a message that says "your email address is pending change to newemail@example.com" I want to display this on the edit profile form.

**Comment by kangmingtay** [comment]
@eluce2 Hmm i just checked and the user object returned from `auth.updateUser()` does contain the `new_email` and `email_change_sent_at` fields. It won't be in the JWT because the JWT doesn't get refreshed when you call `updateUser`. Let me know if this helps!
