### ISSUE TITLE
Disable auto send of the "confirm mail" 

### ISSUE THREAD

**Issue by lerayj** [supabase/gotrue-js#290]
# Feature request

Supabase template email does not let a lot of space to make complex email for email confirmation, password change, ...

It's possible to take control of it with `supabase.auth.api.generateLink`, generate a link, then use a mail service like Sendgrid to create confirm mail by yourself. This works perfectly.

Unfortunally, it's not possible to disable the automatic mail from Supabase, resulting on a 2 mail sent to a customer - the custom Sendgrid one, and the auto Supabase one.

The feature would simply consist of an option on the Supabase UI to distinguish "confirm mail required" and "auto send confirmation mail", or simply add an argument option on the signup method to disable the auto sent mail.

**Comment by UngererFabien** [comment]
Also noticed this change. I added password recovery around 2 month ago with the `PASSWORD_RECOVERY` event of `supabase.auth.onAuthStateChange` and now it does not get triggered.

My user is automatically connected.

**Comment by chipilov** [comment]
@lerayj One way to workaround this issue is to setup a dummy SMTP server in the Auth settings of the dashboard so that the emails that are sent by Supabase are NOT actually delivered (one service you can use for this is https://ethereal.email/)

**Comment by lerayj** [comment]
@chipilov This could work, but in this case I need to create specific template for each use case - eg in my situation, resetting password email could stay simple and be handled by Supabase. 

And thanks for the repo redirect, please @maintainers tell me if I need to move this issue!

**Comment by sedhha** [comment]
Hey guys is it possible now or still work in progress?

**Comment by kangmingtay** [comment]
Hey @lerayj and @sedhha, the `generateLink` method shouldn't send an email at all. I suspect that there might be some confusion around how the `generateLink` method works. It will automatically signup / invite / initiate the magiclink / recovery link / email_change auth flow but it won't send out any emails. You should not be calling the `signUp`, `signIn` (with magiclink) or `resetPasswordForEmail`, `inviteUserByEmail` methods if you plan to call `generateLink`.

For reference: @chipilov has kindly explained the issue in more detail [here](https://github.com/supabase/gotrue/issues/304#issuecomment-1185558150) 

Feel free to reopen the issue if i've misunderstood the problem here!

**Comment by stefan-girlich** [comment]
I appreciate @chipilov 's solution to the problem, yet I would strongly suggest to re-open this issue and re-consider integrating an explicit toggle for disabling e-mail sending via Supabase.

- The [`generateLink` method](https://github.com/supabase/gotrue/issues/304#issuecomment-1185558150) requires a middleware service and nullifies one of Supabase's strengths: to directly integrate with a frontend. Switching between built-in and external mailing requires changes to frontend, middleware, backend and the overall app architecture.
- Using an external ["dummy SMTP"](https://github.com/supabase/auth-js/issues/290#issuecomment-1147525275) creates a dependency on an external service which - if I understand this correctly - would receive and temporarily store emails with user credentials that allow for signing in as the corresponding user. If this is the case, using such a service cannot be considered a secure solution.
- Setting up an Inbucket instance as a "dummy SMTP" prevents the aforementioned security issue, but brings additional effort of hosting another service.

Most production-level projects I worked on use an external mailing provider via a REST API (e.g. Brevo) for the sake of easy editing/managing of templates and tracking, so I assume that the lack of an "auto-send" toggle would affect a large number of users or even make teams consider not adopt Supabase (as it is unfortunately the case in my current project).

I will evaluate if I can use deliberately invalid SMTP settings for now. @chipilov @kangmingtay  Please let me know if I can help. I am mostly happy with Supabase and I'd love to contribute where I can.
