### ISSUE TITLE
Removing tokens from the URL's hash fragment should be done via the History.replaceState() API

### ISSUE THREAD

**Issue by chipilov** [supabase/gotrue-js#302]
# Bug report

## Describe the bug

Currently, when a session is recovered from the URL's hash fragment, the token is removed from the hash by setting ```window.location.hash``` explicilty: https://github.com/supabase/gotrue-js/blob/30fb5729a1988dbd7f61d58ec10eb81de63f93c7/src/GoTrueClient.ts#L470

However, if the user uses the Back/Forward buttons they can still get to the tokens in the hash.

In order to avoid that, the tokens should be removed using the ```History.replaceState()``` API.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use a Supabase provided auth link (i.e. a link which contains an access_token in the hash portion, e.g. a magic link);
2. Notice that as soon as the access_token is consumed by the GoTrue-js library, the browser's URL no longer shows the access_token in the hash fragment of the URL;
3. Click on the browser's Back button and then click on the browser's Forward button;

## Expected behavior

The access_token should NOT be visible to the user, even after using the Back/Forward buttons;

## Actual behavior

The access_token is again visible in the browser's URL and the user MIGHT try to re-use it by refreshing the page at the current URL.

## System information

- OS: Windows
- Browser (if applies): Chrome, v102
- Version of supabase-js: 1.35.3
- Version of gotrue-js: 1.22.15

**Comment by hf** [comment]
Will be fixed with #574.
