### ISSUE TITLE
Feature Request - New Ory Hydra OAuth2 Provider Integration

### ISSUE THREAD

**Issue by koakh** [supabase/gotrue-js#316]
# Feature request

I want a new Ory Hydra OAuth2 Provider Integration

## Describe the solution you'd like

Waiting for someone/team/community integrate Ory Hydra OAuth2 Provider

## Describe alternatives you've considered

The alternative is integrate it, and contribute with PR of the Integration with some info how to setup and a online demo of everything working, and a deployed OryHydra server if supabase members wants to test integration without deploy it

## Additional context

This same feature request will be in repos supabase-js and supabase gotrue repos

- [related issue](https://github.com/supabase/gotrue/issues/540)

**Comment by steve-chavez** [comment]
@koakh Some examples are being worked on here: https://github.com/supabase/supabase/discussions/7758

**Comment by koakh** [comment]
Hello this examples 
https://github.com/supabase/supabase/discussions/7758
are about ory kratos and oathkeeper, 

glad to know it, sure I will check it later :)

But I'm talking here is about ory hydra, not kratos or oathkeeper, 
Hydra is another ory project, and the oryhydra provider is just another oauth2 provider on top of gotrue

I admit my english is not good enough but I'm try hard to explain the purpose and motivation, maybe a demo with everything working makes more sense

NextJs > Auth (GoTrue+OryHydraProvider) > NextJs (With access Granted)

I already integrate ory hydrabas as new gotrue provider a few days later, and create the issues to submit the PR  

Now I m waiting to PR, nothing more

Thanks for support

**Comment by vinckr** [comment]
Hello @koakh 
That is correct the current examples are using Kratos to manage identities and Oathkeeper as as identity and access proxy.

We also have some examples upcoming that involve Hydra, and would love to feature an integration with supabase in our docs & example repo as well 👍 feel free to reach out to me.

**Comment by koakh** [comment]
Hello @vinckr 

Glad to know you have interest in supa and hydra integration to, but to use supabase with oryhydra provider I must PR it, and they must deploy a new version of hosted supabase

The other way we can work is using the docker images that I made, but this only work with supabase self hosted, its what i'm using right now

Why: because hosted supabase dont have ory provider and without it we can't use hosted version

Maybe this will take some time, to code review, docs, tests etc

But I will ping you in slack, 
until supa budies respond to PR
And sure we will advance in ory hydra side

**Comment by kangmingtay** [comment]
Hey everyone, we'll be closing this issue since we've added it to the [megathread](https://github.com/supabase/gotrue/issues/451). Thanks for the suggestion!
