### ISSUE TITLE
supabase.auth.signIn fails in local dev with: "Invalid authentication credentials"

### ISSUE THREAD

**Issue by barbalex** [supabase/gotrue-js#317]
# Bug report

## Describe the bug

For a few months I have worked on developing an app.
Suddenly that is not possible any more, as auth ceased working.

This is pretty bad as developing the app is not possible any more!
I will very soon need to switch to a different auth provider as further delay is not tolerable.

This is the code building the supabase client:
```js
import { createClient } from '@supabase/supabase-js'

// https://supabase.com/docs/reference/javascript/initializing#with-additional-parameters
const options = {
  schema: 'public',
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: true,
}

export const supabase = createClient(
  import.meta.env.VITE_PUBLIC_SUPABASE_URL,
  import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY,
  options,
)
```

This is the code used to sign in:
```js
await supabase.auth.signIn({
  email: emailToUse,
})
```

These are the headers of the call initiated:
<img width="424" alt="headers" src="https://user-images.githubusercontent.com/669783/179355857-7a7da962-3df9-47c8-9a68-b97ec56920ff.png">

This the payload:
<img width="417" alt="payload" src="https://user-images.githubusercontent.com/669783/179355867-32f4586a-3390-4afa-9087-4910001835a9.png">

And the response:
<img width="298" alt="response" src="https://user-images.githubusercontent.com/669783/179355869-197390c8-e7d8-4b3d-a450-fae2cfb5f7c2.png">

What I have done:
- emptied chrome cache
- restarted pc, docker, docker servers
- stopped, restarted supabase
- updated service role key, anon key
- updated local supabase: `scoop update supabase`
- tried this all on a MacOS machine beside my usual Windows dev machine

## To Reproduce

I have no idea how to make this reproducable.

## Expected behavior

As it worked for months before: Find a link in http://localhost:54324/m/alex.barbalex, klick it and be logged in.

## System information

- OS: windows 11 up to date
- Browser: Chrome up to date
- Version of supabase-js: 1.35.4
- Version of Node.js: 17.3.1

**Comment by barbalex** [comment]
I finally am finding time to work on this project again. Had to put it aside because of this extremely frustrating issue.

This is - as mentioned - dev. So I am running supabase locally in docker. Thus as you mentioned localhost:54321.

**Comment by barbalex** [comment]
This is not only a hard blow to the project's development. But also makes us wonder if we should depend on a product that seems to be rather brittle.

**Comment by barbalex** [comment]
I am not sure what you meant with reaching out to support - that link is not helpful.

**Comment by hf** [comment]
Hey @barbalex,

One thing I'm noticing on one of the screenshots is the use of double quotes `"` in the `Authorization` and `apikey` headers. Can you please make sure you don't have double quotes anywhere.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/295870/197581431-b6264c29-f30c-4fa8-a30f-2116cc12c228.png">

For example, this should **not include the `"`**:

- After `Bearer ` and at the end of the Authorization string
- Surrounding the `apikey` value

Let me know if this changes anything. Sometimes you can accidentally copy-paste characters and there's not an easy way for our software to correct such errors.

**Comment by barbalex** [comment]
I don't think I'm actively setting quotes anywhere.  All the code does is call:

```js
await supabase.auth.signIn({
  email: emailToUse,
})
```

The rest is done by `@supabase/supabase-js`.

So as far as I understand those keys are set by supabase-js itself.

Am I wrong?

There is a single place in the code that does not use supabase itself to talk to the server. That is where the code checks if the server is reachable i.e. if the user is online:
```js
const session = supabase.auth.session()

const config = {
  timeout: 5000,
  headers: {
    authorization: `Bearer ${session?.access_token}`,
    apikey: import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY,
  },
}

await axios.head(
  `${import.meta.env.VITE_PUBLIC_SUPABASE_URL}/rest/v1/`,
  config,
)
```
Here no quotes are set.

**Comment by barbalex** [comment]
Actually proof that supapase itself is setting these quotes is in the X-Client-info parameter shown in above printscreen.
