### ISSUE TITLE
supabase.auth.signUp returns 200 for existing users

### ISSUE THREAD

**Issue by lanbau** [supabase/gotrue-js#320]
# Bug report

## Describe the bug

```
const { user, error } = await supabase.auth.signUp({
        email,
        password,
      });
```

## To Reproduce

1. submit a signup request to https://xxx.supabase.co/auth/v1/signup with the code above for an existing user

## Expected behavior

Expecting 400 error saying user has already signed up.

**Comment by J0** [comment]
Closing as the issue has gone stale, feel free to re-open if there are still issues.
