### ISSUE TITLE
Confusion on gotrue.js working with redirectTo option for magiclink.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/gotrue-js#321]
# Bug report
This is more clarification is needed and then possibly a document change.

Back in March based on these https://github.com/supabase/gotrue-js/pull/253 , https://github.com/supabase/supabase/issues/5663#issuecomment-1074427708

Implies that gotrue.js can no longer use redirectTo for signIn with magiclink (email only, no password).

Several users in the forums believe it still works, others run into an issue and stop based on the docs.

It seems to still work.

## To Reproduce
Setup signIn with email only and no password, redirectTo set to a subpage in website.  Website URL set to base and approved redirects set to include the entire URL with subpage.
Login and and email is sent with a redirect_to option in the url and does redirect to that subpage in the app...

https://ugccqxxxxxxxxxypbq.supabase.co/auth/v1/verify?token=bF3ZHLRPV9cr9kXWI_NJyQ&type=magiclink&redirect_to=http://mysite.us/page is the URL in the email...

## Expected behavior

If redirectTo is still supported for magiclink Docs need to be updated to reflect that.

## Screenshots

![image](https://user-images.githubusercontent.com/54564956/164814713-32875d19-3423-43b9-b21f-4989b4eae6fc.png)

![image](https://user-images.githubusercontent.com/54564956/164814758-78d95c49-649a-48fd-a0b5-8ef3759b92e7.png)

This user did more specific testing already:

https://github.com/supabase/supabase/issues/5663#issuecomment-1075951729
![image](https://user-images.githubusercontent.com/54564956/164815324-318f5d2d-63dd-4fee-a66a-ce9bc395b595.png)

**Comment by kangmingtay** [comment]
We've updated the docs for this already:

V1: https://supabase.com/docs/reference/javascript/v1/auth-signin
V2: https://supabase.com/docs/reference/javascript/auth-signinwithotp

Gonna close this issue but please feel free to reopen or leave any feedback that if we can improve the docs around this
