### ISSUE TITLE
Not possible to keep user signed in

### ISSUE THREAD

**Issue by nereolopez** [supabase/gotrue-js#323]
# Bug report

## Describe the bug

The issues is that the user gets kicked off the app and needs to sign in again over and over. 
After checking the many threads on this issue, these are the two scenarios we face: 

1. The token gets refreshed when I come back to the application after 1 hour which is the default expiration time (see screenshot below where the event is captured), but the immediate next call (and all subsequent ones) fail with the error message "JWT expired"
![image](https://user-images.githubusercontent.com/5878234/163626568-6479f738-817d-493a-8297-ef29569b7add.png)

2. If I take way longer to come back to the application, the token does not get refreshed an the next request fails with a "invalid_grant Invalid Refresh Token" error. 

## To Reproduce

The project is using supabase-js and Angular installed as PWA

1. Create the `SupabaseClient` with `autoRefreshToken` set to `true`.
2. Sign in a user with `supabase.auth.signIn({ email: email, password: password });`
4. Leave the application idle for a bit more than 1 hour for the first case described, or for several hours for the second one

## Expected behavior

We are porting from Firebase to Supabase, and our understanding was that the `autoRefreshToken` should help achieving keeping the user signed in.
There are some other threads where it is proposed to check the result of every call, and if the error is "JWT expired" then try to sign in the user again in the background and retry the original call, but that would be a workaround more than the solution.

## System information

- Version of supabase-js: 1.33.3

## Additional context

Just to say that we are loving Supabase. It would be great to be able to keep our users signed in automatically, otherwise it will be hard to deploy the version backed by Supabase rather than Firebase. Thanks!

**Comment by anngbaum** [comment]
@J0 I was optimistic that the changes described in PR #285 would alleviate this problem (for us, at least). I have not updated our repo to test the go-true/next branch yet, but if there's any approximate timeline for that release, we would definitely still love to see this handling improved.

**Comment by alaister** [comment]
Hey @anngbaum,
You can try out this version of `gotrue-js` by running `npm install @supabase/supabase-js@next` as it's included there.
It may be a little difficult to upgrade without any docs, so I'd recommend leaning heavily on the typescript typings.

We're aiming to get v2 out next month! 🤞🏻

**Comment by ARMATAV** [comment]
https://supabase.com/blog/supabase-js-v2

> This solves the “getting logged out” issue, which has been a recurring challenge in our GitHub Discussions.

Should be good to go here now, right?

**Comment by nereolopez** [comment]
Hi @ARMATAV, that would be good news. Please allow us few days to test it and revert :)

**Comment by nereolopez** [comment]
@ARMATAV we've been testing with RC3 both on web and installed on phones as PWA in different scenarios and in all the cases the session kept open, first calls to backend after wake up of the app succeeded, so for now, not able to reproduce the issue 🥳. 

Please feel free to close it and thanks again for the fix and support!

**Comment by ARMATAV** [comment]
@nereolopez Ah, now it finally is the best auth experience available. Hopefully they fix the `auth-helpers` repo by including this new update.

I'm not actually a repo contributor my dude - so I can't close the issue - but, hey, good that it works though!

**Comment by nereolopez** [comment]
Sorry @ARMATAV, I am in the middle of my first paternity leave and went straight to test it. As you left the note I did not check and just assumed you were. I am closing the issue then. Thanks!

**Comment by ARMATAV** [comment]
@nereolopez Congratulations on the kid!
