### ISSUE TITLE
Caching and Account Switching for supabase auth

### ISSUE THREAD

**Issue by bossjapzz** [supabase/gotrue-js#324]
# Feature request
Caching and Account Switching for supabase auth. Because nowadays it is a common feature especially on social media where you switch different accounts.

## Describe the solution you'd like
**Facebook:**
![How-to-Switch-multiple-accounts-on-Facebook-on-PC](https://user-images.githubusercontent.com/100037148/154986163-46f767fd-1887-454e-b80e-8684de00b2cf.jpg)

**Gmail:**
![iphone-gmail-tap-avatar-account-switcher](https://user-images.githubusercontent.com/100037148/154986167-92700b48-58af-4408-a1de-316f86e5fb33.jpg)

**Twitter**
![select-the-twitter-account-that-you-want-to-switch-to](https://user-images.githubusercontent.com/100037148/154986174-9947f893-ea5d-4300-aaa8-2740ac53c3aa.png)

We can also benefit with this feature request
https://github.com/supabase/gotrue/issues/967

**Comment by hf** [comment]
Great idea.

**Comment by hf** [comment]
Added this to our internal feedback board. Closing for now as I don't think this is going to be picked up quickly.

If you want to implement this, it should be somewhat easy by overriding the Auth storage option. You just need two different storages -- one for each account. That should be quite easy to do.
