### ISSUE TITLE
onAuthStateChange should fire on initial load

### ISSUE THREAD

**Issue by mikob** [supabase/gotrue-js#326]
# Feature request

## Is your feature request related to a problem? Please describe.
Currently it seems there is no deterministic way to know if a supabase session is done with initial loading.

If the user is signed out,`auth.session()` will return `null` and `onAuthStateChange` won't fire. If the user is signed-in, `auth.session()` will return `null`, but then `onAuthStateChange` will fire soon after with the session data.

Consider this code:
```
        const sess = supabase.auth.session();
        log("session event", sess);

        changeSession(sess);

        supabase.auth.onAuthStateChange((_event, session) => {
            log("session event", _event);
            changeSession(session);
        });
```

### A clear and concise description of what you want and what your use case is.
I need to load certain user history with knowledge of whether the user is signed-in or not. Yes it's possible to first fire assuming they aren't logged in, and then backtracking and firing again (once `onAuthStateChange` is hit) saying actually they are signed in, but it forces me to fire changeSession a function which is resource intensive on my end twice. 

## Describe the solution you'd like

Either `onAuthStateChange` should fire initially by default (how firebase auth works BTW), whether the user is signed in or not (perhaps a special INITIAL event) or should take a parameter {initial: true} to allow this behavior.

**Comment by Stuk** [comment]
I think the best approach is to represent the initial initialization state as a promise. The API would look something like:

```ts
const client = new GoTrueClient(options);

// any time later
await client.initialized();
if (client.user()) {
  // signed in
} else {
  // not signed in
  client.signIn(credentials);
}
```

This avoids race conditions between the the construction of the client and adding event listeners, and allows one to check the initialization state at any point in the future.

I have created a pull request for this here: https://github.com/supabase/gotrue-js/pull/371

**Comment by hf** [comment]
With v2 this is handled. `getSession` will reuse the initial promise so any waiters on it will resolve properly.
