### ISSUE TITLE
Backoff upon error during auto refresh

### ISSUE THREAD

**Issue by pixtron** [supabase/gotrue-js#333]
# Bug report

## Describe the bug

Backoff during auto refresh upon network failure fails in 1.23.0-next.  
 
## To Reproduce

1. clone the [repro](https://github.com/pixtron/supabase-repro)
2. npm install
3. npm start
4. Signup with email and password (or login if you already have an account)
5. Disable all network interfaces
6. Wait 2 minutes until token expires and auto refresh is triggered

The refresh request fails due to the client being offline. The client does not backoff and retry with further requests.
		
## Expected behavior

The client should backoff and retry to refresh the token.

## Suggested fix

This regression seems to have been introduced in 1.23.0-next in `lib/fetch.ts` with [#301](https://github.com/supabase/gotrue-js/pull/301/files#diff-437f2c15df7c90ad8154c5de1677ec0838d51859bcc0a0cefd8a0424b5736f31L17-R27).

1. Introduce a new Error `AuthNetworkFailureError exends AuthError`
2. Throw `AuthNetworkFailureError` instead of [`AuthUnknownError`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/lib/fetch.ts#L30). Fetch only throws on a network error (unfortunately there seems to be no way to distinguish between network errors and CORS though).
3. Replace the check [`error?.message === NETWORK_FAILURE.ERROR_MESSAGE`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L989) with `error instanceof AuthNetworkFailureError`
4. Remove constant [`NETWORK_FAILURE.ERROR_MESSAGE`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/lib/constants.ts#L8)

## System information

- OS: NA
- Browser: NA
- Version of supabase-js: NA
- Version of gotrue-js: 1.23.0-next.6
- Version of Node.js: NA

## Additional context
 
The same mal function can probably be observed in [`_recoverAndRefresh`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L847-L862).

**Comment by kangmingtay** [comment]
closing this since it's been resolved by the PRs above! thanks @pixtron once again :)
