### ISSUE TITLE
Dangling Promises in _callRefreshToken

### ISSUE THREAD

**Issue by pixtron** [supabase/gotrue-js#334]
# Bug report

## Describe the bug

Upon an error the method [`_callRefreshToken`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L887-L923) does not resolve the `refreshingDeferred`, leading to dangling promises. If an error during a refresh token request occurs the deferred is kept for ever, and all subsequent calls to `_callRefreshToken` will [await  the deferred](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L890-L892) for an infinite time as it will never resolve.

## To Reproduce

1. clone the [repro](https://github.com/pixtron/supabase-repro)
2. npm install
3. npm start
4. Set breakpoints on these lines:
	 - [`if (this.refreshingDeferred)`](https://github.com/supabase/gotrue-js/blob/v1.23.0-next.6/src/GoTrueClient.ts#L890)
	 - [`const { session, error } = await this.api.refreshAccessToken(refresh_token)`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L902)
5. Signup with email and password (or login if you already have an account)
6. Disable all network interfaces
7. Wait 2 minutes until token expires and auto refresh is triggered (there will be no retries #333)
8. Enable network again
9. Sign out
10. Sign in again
11. Wait 2 minutes for refresh 

The condition [`if (this.refreshingDeferred)`](https://github.com/supabase/gotrue-js/blob/v1.23.0-next.6/src/GoTrueClient.ts#L890) will be true and `this.refreshingDeferred` from the former refresh request in step 7 is returned and never rejected nor resolved.

## Expected behavior

The deferred should be resolved with the error result and then be reset to null.

## Code sandbox
I created a [sandbox ](https://codesandbox.io/s/current-deferred-m3crnh?file=/src/Client.ts:828-1590) to simulate the behavior.

#### Auth Error 
1. Click two times on the Button "Refresh Auth Error"
2. Wait a second
3. We only get a result for request #1 NOK: we should get a result for req #2 as well
4. Click again on any Button
5. Request #1 is triggered, but never gets a result NOK

#### Generic Error
Same scenario as Auth Error but with Button "Refresh Generic Error", throws the error instead of resolving with an error response. 

#### Success case works as expected
1. Click tow times on the Button "Refresh Success"
2. Wait a second
3. Both requests get resolved with the result of req #1 OK
 
## Suggested Fix

1. Move [`this.refreshingDeferred = null`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L913) into a `finally` block so it gets reset in success and error case.
2. [If the error is an `AuthError`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L917), resolve `this.refreshingDeferred` with the error result in the catch block.
3. [If the error is not an `AuthError`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L921), reject `this.refreshingDeffered` with the thrown error
4. Move [`return await this.refreshingDeferred.promise`](https://github.com/supabase/gotrue-js/blob/fb7fae5d763c7173f16aa8c6a8747013d8ba4d24/src/GoTrueClient.ts#L890-L892) out of the try block and don't await it (`return this.refreshingDeferred.promise`). This is to avoid multiple entries into catch and finally block, when the error is not an `AuthError` and therefore re thrown (see 3).

I created a [sandbox simulation with the suggested fix](https://codesandbox.io/s/fixed-deferred-mghg60?file=/src/Client.ts:828-1933) 

## System information

- OS: NA
- Browser: NA
- Version of supabase-js: NA
- Version of gotrue-js: 1.23.0-next.6
- Version of Node.js: NA

## Additional Context

This regression seems to have been introduced in 1.23.0-next with [#285](https://github.com/supabase/gotrue-js/pull/285/files#diff-3522461172efd6058d6b8da62fc2d30d8b524d2b64894ea2c67218c52f7fdff5R756-R782).

**Comment by kangmingtay** [comment]
Closing this since it seems to have been resolved in the PR above, thanks @pixtron !
