### ISSUE TITLE
using in node context w/policy

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue-js#34]
Jump to the [Solution specification](https://github.com/supabase/gotrue-js/issues/34#issuecomment-823747025)

problem:

tried using RLS in node context, is there a step I'm missing?

```sql
create table public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid
);
alter table posts enable row level security;
create policy "users can insert only own posts" on public.posts for insert with check (auth.uid() = uuid);
```

```javascript
const { createClient } = require("@supabase/supabase-js");
const supabase = createClient(
  "https://REF.supabase.co",
  "KEY"
);
const main = async () => {
  supabase.auth
    .signIn({ email: "ant@supabase.io", password: "11" })
    .then(() => {
      supabase
        .from("posts")
        .insert([{ uuid: supabase.auth.session().user.id }])
        .then(console.log)
        .catch(console.log);
    })
    .catch(console.log);
};
main();
```

but getting:
```javascript
{
  error: {
    hint: null,
    details: null,
    code: '42501',
    message: 'new row violates row-level security policy for table "posts"'
  },
  data: null,
  status: 403,
  statusText: 'Forbidden',
  body: null
}
```

**Comment by awalias** [comment]
ah probably not that relevant to real world use case

**Comment by kiwicopple** [comment]
FYI, if you want to use in Node then you will need to pass the user JWT in the Auth header:

```
const supabase = createClient( "https://REF.supabase.co",  "KEY", {
  headers: {
    Authorization: "Bearer USER_JWT"
  }
});

```

**Comment by awalias** [comment]
Should it send this automatically if there's an active session?

**Comment by kiwicopple** [comment]
There is no "localStorage" on Node, so there isn't a way to keep an active session. Thor is working on a cookie interface though: https://github.com/supabase/gotrue-js/pull/33. If we merge that we could use the cookies server-side

**Comment by kiwicopple** [comment]
Thor and I were discussing some options:
```
const supabase = createClient("XX", "public-anon-key")
  .setUser({ req | jwt })
```

Could also just pass the req to the constructor but it's less explicit

```
const supabase = createClient("https://xyzcompany.supabase.co", "public-anon-key", { req })
```

**Comment by thorwebdev** [comment]
@kiwicopple and I have been discussing this, some options:

1.
```js
const withAuth = supabase
  .setUser(JWT) // Generates a new client  
withAuth
.from('table')
.select()
```

2. Alternatively we could have an option to pass the request object to the createClient
```js
const supabase = createClient("https://xyzcompany.supabase.co", "public-anon-key", { req })
```

not as explicit though. I wonder if new developers will understand what’s going on there?

3.
```js
const supabase = createClient("XX", "public-anon-key")
  .setUser({ req | jwt })
```

**Comment by daalvarado** [comment]
Hi. any updates on how to set the user in Node? If I go the createClient way which is the JWT that should be passed in the headers? is it the JWT received from supabase when signing in?

**Comment by inian** [comment]
Hi @daalvarado, the `storage-api` does something similar. You can take the JWT from the `Authorization` header and pass it to `createClient` like [this](https://github.com/supabase/storage-api/blob/b932e3697c439ef71eabafee504c1910f19e3e65/src/routes/bucket/createBucket.ts#L43)

**Comment by daalvarado** [comment]
Hi, thank you for your help.  I have taken the jwt received when registering/logging in and passed it to a new Supabaseclient function but the client I get back does not show any client or session information. I also cannot see any reference to the jwt I have passed in:

export function createSupabase(jwt: string): SupabaseClient {
  const stuff = new SupabaseClient(supabaseUrl, supabaseKey, {
    headers: {
      apikey: supabaseKey,
      Authorization: `Bearer ${jwt}`,
    },
  });
  return stuff;}

I  get the jwt like this and save it to a cookie in my backend:
const {session} = await supabase.auth.signUp({ email, password })
const jwt =session.access_token

when I get a request with the cookie I try to get the user like this:
let supabaseuser = createSupabase(jwt);

but when I console.log supabaseuser i get no user/session:

SupabaseClient {
  supabaseUrl: 'https://xxxxx.supabase.co',
  supabaseKey: 'xxxxx',
  restUrl: 'https://xxxxx.supabase.co/rest/v1',
  realtimeUrl: 'wss://xxxx.supabase.co/realtime/v1',
  authUrl: 'https://xxxx.supabase.co/auth/v1',
  storageUrl: 'https://xxxx.supabase.co/storage/v1',
  schema: 'public',
  auth: SupabaseAuthClient {
    stateChangeEmitters: Map(0) {},
    **currentUser: null,
    currentSession: null,**
    autoRefreshToken: true,
    persistSession: true,
    localStorage: LocalStorage { localStorage: undefined },
    api: GoTrueApi {
      url: 'https://xxxx.supabase.co/auth/v1',
      headers: [Object],
      cookieOptions: [Object]
    }

Could you help me identify the step I am missing?

**Comment by awalias** [comment]
wrt @thorwebdev 's [comment](https://github.com/supabase/gotrue-js/issues/34#issuecomment-762038518)

2 is awkward because you need to make a new client for each user, you probably want a backend that can switch easily between user contexts.

my preference would be 3 (`supabase.auth.setUser({req|jwt})`)

`setSession` may also be a good name for this?

**Comment by kiwicopple** [comment]
Great, some rough steps to resolve on the gotrue-js side

- Add a new public function to [GoTrueClient](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts) called `setSession()` which receives a JWT as a prop
  - this function should just need to call `_saveSession` [here](https://github.com/supabase/gotrue-js/blob/06d755aec4c6dc19619b6fad55351c6148ce120a/src/GoTrueClient.ts#L487)
- *Out of scope* - passing `req` as a param. This is a bit complicated - let's leave the user to fetch the JWT from their cookies

We can test this by duplicating and modifying this [test](https://github.com/supabase/gotrue-js/blob/master/test/clientWithAutoConfirmEnabled.test.ts). The steps would be:

- sign up a new user
- create a new Supabase client 
- call `auth.setSession` on this new client
- call `auth.update()` - > this should work without any errors

**Comment by nstrelow** [comment]
This would also solve my use-case:

I am sending the session from a Flutter client app to a backend service.
Currently I see no way to set the session myself. In Dart there is the possibility, as the persistence of the session needs to be handled by the implementing developer.

So a `setSession()` method would be much appreciated.

My backend is currently in python, but I consider switching to node, since the js library seems to be your current focus.

**Comment by yummyweb** [comment]
@kiwicopple what would the type of jwt prop be? I am working on this issue.

**Comment by atnegrete** [comment]
> This would also solve my use-case:
> 
> I am sending the session from a Flutter client app to a backend service.
> Currently I see no way to set the session myself. In Dart there is the possibility, as the persistence of the session needs to be handled by the implementing developer.
> 
> So a `setSession()` method would be much appreciated.
> 
> My backend is currently in python, but I consider switching to node, since the js library seems to be your current focus.
> 
> EDIT: Switched to dart, because dart is the only client actually able to restore a session (using recoverSession) in the backend.

@nstrelow Was about to make it private & not have to force the developer to implement persistency, but it's a WIP. Seems a rename is actually in order: `_recoverSession(json)` to `setSession(json)` ? 
see https://github.com/supabase/gotrue-dart/pull/10/files#diff-76e6a8442d6c6fe9f6cae8bfe8c937e3491a017a5889899c0b6e24579c8b7790R219

**Comment by nstrelow** [comment]
@atnegrete Oh please keep it public.
I really need this for a dart server & CLI I working on 🙏
And it is literally the only SDK able to be used that way, without changing things.
setSession seems great (if it has the same functionality: restore and refresh and save)


My current setup involves handling some things in the backend and therefore I am transfering the session (using persistedSession and recoverSession) to the backend and using it to upload things to storage.

Not sure if this is the 100% best way, I am open to hearing other ideas. But it's better than transferring user and password.


Where I am using recoverSession:
CLI: https://github.com/hpi-studyu/studyu/blob/dev/notebook_uploader/bin/uploader.dart#L33
Server: https://github.com/hpi-studyu/studyu/blob/dev/generator/lib/server.dart#L56

**Comment by atnegrete** [comment]
@nstrelow 
Yeah, this is for sure way better than passing around credentials! 

I may end up forking into a Flutter client, keeping it dart only is turning out to be a challenge. I'll make sure to keep that method public if the PR goes through though!

**Comment by kiwicopple** [comment]
to quickly get this out I have put the latest gotrue-js in supabase-js (`1.11.10`)

```js
import { createClient } from '@supabase/supabase-js'

const supabase = createClient("https://xyzcompany.supabase.co", "public-anon-key")

// const JWT = fetch the JWT from the cookie

supabase.auth.setAuth(JWT) 

supabase
  .from('table')
  .select()
```

feel free to drop any problems here (tbh - I only tested on gotrue-js, so would love to hear your feedback).

After I have tested I may add a `setUser/setAuth` function directly to the supabase client (rather than using `.auth.setAuth()`
