### ISSUE TITLE
Email password reset link is invalid for certain emails

### ISSUE THREAD

**Issue by ize8** [supabase/gotrue-js#342]
# Bug report

## Describe the bug

When resetting password via email, the link sent out to certain email addresses (@nhs.net) is invalid/expired. The email arrives, user clicks on the link, and supabase redirects saying "Email link is invalid or has expired". The same process works perfectly well for other addresses (for ex. @gmail.com) making me clueless what the actual problem might be.

The link that arrives in the email (using localhost for dev):
`https://xxxxxxxxxxxxxxxxx.supabase.co/auth/v1/verify?token=b8a61b765b5fc14ab31879697aae9402f617dd581ab744aba54fba25&type=recovery&redirect_to=http://localhost:3000/reset-password`

The redirected page:
`http://localhost:3000/reset-password#error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired`

same problem occurs regardless of initiating the process from the JS Client or from the Supabase console.

## To Reproduce

```javascript
const { data, error } = await supabase.auth.api.resetPasswordForEmail(email, {redirectTo: redirectPage});
```
this returns data:{} error:null

or click "send password recovery" on the Supabase Auth console.

Not sure how to reproduce it without a problematic email address ... so far @nhs.net addresses are the ones that are not working for me.

## Expected behavior

sending out valid reset links to all email addresses

## Additional context

It might be me being a complete noob, but can't get my head around why is it working with gmail and not with any other random address!

**Comment by kangmingtay** [comment]
Hey everyone, 

> I imagine that changing from single-use auth tokens to auth tokens with an expiration date would fix this issue.
Unfortunately, this is not secure since the link will be reusable within the expiration date. Also, it is common for signup / invite / password recovery links to not be clicked immediately within the expiration date after they are being sent out. 

> this returns data:{} error:null
This is expected as well. The `resetPasswordForEmail` will only return an error if there's an issue with sending the email. In this case, the email is being sent but the verification link isn't working because of the email client pre-fetching the link before the user can click on it.

We do recognise that this is a problem and will be working on making it easier for you to workaround this problem. We'll be closing this issue for now since it's more of a gotrue issue than a client library one. Thanks for creating the [corresponding issue](https://github.com/supabase/gotrue-js/issues/330) in gotrue @kylerummens!

**Comment by geniusvale** [comment]
> using `{{ .Token }}` in the Reset Email template, then asking the user to manually enter it into a form seems to be a viable option. ... not as elegant as just clicking on a link, but desperate times :)
> 
> request email with token:
> 
> ```js
>  const { data, error } = await supabase.auth.api.resetPasswordForEmail(email);
> ```
> 
> then you use the token to sign-in:
> 
> ```js
> const {user, session, error} = await supabase.auth.verifyOTP(
>      {
>           email:'xxx.bigbusiness.com', 
>           token:'432742', 
>           type:'recovery'
>      })
> ```
> 
> if successful then this will generate a `'SIGNED_IN'` AuthChange event ...then set up their new password:
> 
> ```js
> await supabase.auth.update({ password: newPassword })
> ```

Thank you very much!!!

**Comment by TaxNowAndrewY** [comment]
Has this issue been addressed?  I think I may be running into this still

**Comment by ollebergkvist** [comment]
@TaxNowAndrewY 

You can solve it by following this guide:
https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr

**Comment by EvanBurbidge** [comment]
Wondering if anyone ever found another way around this, I keep getting 403 errors trying to use the token based approach, at this stages it's making me reconsider supabase auth at all.

**Comment by micheltucker** [comment]
> Wondering if anyone ever found another way around this, I keep getting 403 errors trying to use the token based approach, at this stages it's making me reconsider supabase auth at all.
> 
> ```js
>  if (!email || !token) {
>     return resp.status(400).json({ error: 'no user id provided' });
>   }
> 
>   const { error, data } = await supabase.auth.verifyOtp({
>     email,
>     token,
>     type: 'recovery',
>   });
> 
>   if (error) {
>     return resp.status(500).json({ success: false, error });
>   }
> 
>   if (data.user) {
>     await supabase.auth.updateUser({ password });
>   }
> ```

That seems unrelated to this issue, right?

**Comment by rozabond** [comment]
<h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .SiteURL }}?token_hash={{ .TokenHash }}&type=email&redirectUrl={{ .RedirectTo }}&email={{.Email}}&token={{.Token}}">Reset Password</a></p>
<p>{{ .Token }}</p>

Try to change the change password template, to this and get the token to sign in

**Comment by rozabond** [comment]
> > using `{{ .Token }}` in the Reset Email template, then asking the user to manually enter it into a form seems to be a viable option. ... not as elegant as just clicking on a link, but desperate times :)
> > request email with token:
> > ```js
> >  const { data, error } = await supabase.auth.api.resetPasswordForEmail(email);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then you use the token to sign-in:
> > ```js
> > const {user, session, error} = await supabase.auth.verifyOTP(
> >      {
> >           email:'xxx.bigbusiness.com', 
> >           token:'432742', 
> >           type:'recovery'
> >      })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if successful then this will generate a `'SIGNED_IN'` AuthChange event ...then set up their new password:
> > ```js
> > await supabase.auth.update({ password: newPassword })
> > ```
> 
> Thank you very much!!!

**Comment by bkan36** [comment]
I've encountered this kind of issue with reset-password workflow 

my verify OTP return **Email link is invalid or has expired** every time.

I thought the problem was from supabase or SMTP and I fixed it by calling my function at the mounted step of my component
I use nuxt 3 (3.11.2)

here's my code

```
onMounted(async () => {
        await getUserFromToken()
    })

    async function getUserFromToken() {
        try {
            const tokenHash = route.query.th
            const type = route.query.type

            if (tokenHash && type) {
                const { data, error } = await supabase.auth.verifyOtp({
                    token_hash: tokenHash,
                    type,

                })
                if (error) throw error
                console.log(data)

                email.value = data.user.email

                console.log(email.value)
            }

        } catch (error) {
            console.error(error)
        }
    }
    
```

on supabase dashboard:
Authentication -> Email templates -> reset password

`<p><a href="{{ .SiteURL }}/reset-pwd?th={{ .TokenHash }}&type=recovery">Reset Password</a></p>`


if that's any help.

**Comment by JavascriptMick** [comment]
@bkan36 any reason this approach 

> I've encountered this kind of issue with reset-password workflow
> 
> my verify OTP return **Email link is invalid or has expired** every time.
> 
> I thought the problem was from supabase or SMTP and I fixed it by calling my function at the mounted step of my component I use nuxt 3 (3.11.2)
> 
> here's my code
> 
> ```
> onMounted(async () => {
>         await getUserFromToken()
>     })
> 
>     async function getUserFromToken() {
>         try {
>             const tokenHash = route.query.th
>             const type = route.query.type
> 
>             if (tokenHash && type) {
>                 const { data, error } = await supabase.auth.verifyOtp({
>                     token_hash: tokenHash,
>                     type,
> 
>                 })
>                 if (error) throw error
>                 console.log(data)
> 
>                 email.value = data.user.email
> 
>                 console.log(email.value)
>             }
> 
>         } catch (error) {
>             console.error(error)
>         }
>     }
>     
> ```
> 
> on supabase dashboard: Authentication -> Email templates -> reset password
> 
> `<p><a href="{{ .SiteURL }}/reset-pwd?th={{ .TokenHash }}&type=recovery">Reset Password</a></p>`
> 
> if that's any help.

Any reason this approach would not work for expired email confirmation links (as opposed to password reset) ??

**Comment by austinmw** [comment]
@kangmingtay  Any solution currently for end users besides not using their corporate email?
