### ISSUE TITLE
Add support for transactional email providers

### ISSUE THREAD

**Issue by kasvith** [supabase/gotrue-js#343]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, we can enable SMTP providers with gotrue. This is also available in Supabase Studio.
But there are other transactional email services, which is preferred by lot of users like 

- Mailgun
- AmazonSES
- Sendgrid

It would be awesome if supabase version of gotrue could support these providers. So in the UI it will be simply selecting provider and pasting API Key and Secret

## Describe the solution you'd like

- Implement transactional providers with GoTrue
- Add it to supabase studio

**Comment by RWOverdijk** [comment]
I'm just looking through the issues and this one made me curious. Don't all of those already support using smtp? What would be the difference?

**Comment by kasvith** [comment]
@RWOverdijk Web APIs are faster than SMTP relays. So they have a higher throughput. Almost all providers I mentioned above recommends using Web API instead of SMTP

**Comment by RWOverdijk** [comment]
That's fair, passing off the message does mean less waiting in your own code. I didn't know that was the reasoning behind this issue.

Thanks for taking the time to clarrify.

**Comment by kasvith** [comment]
This also helps to reduce stress on the go-true server as it can simply send a lot of emails in a short time

Also, it will be possible to leverage the templates from these providers, so you only send data and the template ID for the provider and it can do the rest of the work without stressing the go-true server

**Comment by kangmingtay** [comment]
Hey everyone, we don't plan on adding these transactional email providers for now but we do have a `generateLink` method which allows you to generate the confirmation / invite / recovery / email change / magic link for a user. You can then call the API of one of these services and send the link in the body of the email.
