### ISSUE TITLE
Auth returning 406 Status

### ISSUE THREAD

**Issue by TheRealToxicDev** [supabase/gotrue-js#344]
# Bug report

## Describe the bug
Hello im not sure if i should open this issue here or on the actual Supabase Repo but When i attempt to authorize on my website using it returns the following errors:

###### New User
-  `Failed to load resource: the server responded with a status of 406 ()`

###### Existing User
- `GET https://zmsbaentcljnuhzjasbw.supabase.co/rest/v1/profiles?select=id%2Cusername%2Cavatar_url%2Cdisplay_name%2Cbio&id=eq.cf44bcb5-e511-4471-9de3-58a36408cf75 406` This error also return some additional info i will attach a screenshot below.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Click on 'Login'
2. Choose a provider
3. Wait for loading

## Expected behavior
Upon login it should fetch info from the Supabase database such as username etc but for some reason it returns a 406 (For new users) or the error shown in the screenshot if the user already exists (Not their first time authorizing)

## Screenshots
New User: ![Screenshot](https://toxic-is-senpai.wtf/a05f24.png)
Existing User: ![Screenshot](https://toxic-is-senpai.wtf/7d3486.png)

## System information

- OS: Windows
- Browser: chrome
- Version of supabase-js: ^1.28.5
- Version of Node.js: ^16.13.0

## Additional context
I do have the Database configured and all the tables added but im thinking maybe i chose the incorrect column type is that possible to be the cause in this case? otherwise im not sure what the issue is here. Please let me know whatever info you need id be happy to provide it

This error is preventing the auth from being completed so any assistance in resolving it is greatly appreciated 😅

**Comment by kangmingtay** [comment]
Hey @TheRealToxicDev, doesn't `setUser` just set the state? this seems like a problem with your `useLocalStorage` hook

It might be worth posting your question in the [github discussions](https://github.com/supabase/supabase/discussions) as well since this doesn't seem like an error with the client library. Will be closing this issue for now.
