### ISSUE TITLE
setAuth() is not returning { user, error } when called server side

### ISSUE THREAD

**Issue by robinscholz** [supabase/gotrue-js#346]
# Bug report

## Describe the bug

It seems like the documentation for setAuth() is wrong. The express example shows `{ user, error }` as the returned object. However, it seems like this is not implemented: https://github.com/supabase/gotrue-js/blob/edcd2ffde6dfe81d02700a52a79e635a5ab8839d/src/GoTrueClient.ts#L389

As far as I understand it, this is what is used for server side calls, correct?

## Expected behavior

Return `{ user, error }` as documented, also server side.

## System information

- OS: macOS
- Version of supabase-js: v16.1.0^1.31.1
- Version of Node.js: v16.1.0

**Comment by hf** [comment]
There has been a lot of changes with respect to [server side rendering](https://supabase.com/docs/guides/auth/server-side-rendering) in v2 of the library, which should address this issue.
