### ISSUE TITLE
updateUserById - user_id must be an UUID

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/gotrue-js#348]
# Bug report

## Describe the bug

invoke function```user_id must be an UUID``` return  ​```user_id must be an UUID```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a file "test.js" and copy this code:

```js
const {createClient} = require('@supabase/supabase-js')
require('dotenv').config()


const options = {
  schema: 'public',
  headers: {},
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: true
}

const supabase = createClient("http://localhost:8000", process.env.SERVICE_ROLE_KEY, options)

async function createUsers(){
  const { data: admin, errorADMIN } = await supabase.auth.api.createUser({
    email: 'admin@email.com',
    password: 'password',
    data: { name: 'Test Admin' }
  })
  
  if(!errorADMIN){
    console.log('> User: admin@email.com - Created',admin)

    const test = await supabase.auth.api.updateUserById({
      uid: admin.id,
      attributes: { email_confirm: true },
    })

    console.log('##### TEST', test)
  }else{
    console.log(errorADMIN)
  }
  
  
  const { data: user, errorUSER } = await supabase.auth.api.createUser({
    email: 'user@email.com',
    password: 'password',
    data: { name: 'Test User' },
    attributes: { email_confirm: true },
  })
  
  if(!errorUSER){
    console.log('> User: admin@email.com - Created',user)
    const test2 = await supabase.auth.api.updateUserById({
      uid: user.id,
      attributes: { email_confirm: true },
    })
    console.log('##### TEST', test2)
  }else{
    console.log(errorUSER)
  }
}

createUsers()
```

Replace fix env / urls to be in the same page with ur setup

## Expected behavior

I expect to update the user with the uid returned by createUser function

## Screenshots

![image](https://user-images.githubusercontent.com/36926081/153679607-f69bf54f-2175-4ae3-8c73-ab2d04aaa896.png)

## System information

- OS: Windows 11
- Version of supabase-js: 1.30
- Version of Node.js: 14

**Comment by kangmingtay** [comment]
Hey @WilliamFalci, @limmidy, @impactvelocity, @ngerritsen, this isn't a bug with the client library. Based on the example @WilliamFalci provided above, the uid is being passed incorrectly in `updateUserById`. See the `updateUserById` [method](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L777-L780). 

```
// Incorrect
const test = await supabase.auth.api.updateUserById({
      uid: user.id,
      attributes: { email_confirm: true },
    })

// Correct 
const test = await supabase.auth.api.updateUserById(user.id, {
  email_confirm: true,
})
```

Will be closing this issue since it's not an issue with the client library. Please let me know if you guys still have any questions regarding this issue.
