### ISSUE TITLE
signIn() not working!

### ISSUE THREAD

**Issue by vincent-thomas** [supabase/gotrue-js#350]
# Bug report

## Describe the bug

The supabase.auth.signIn({provider: 'google'}); does not work! It just redirects me to this uri: `/[SUPABASE_TOKEN]/auth/v1/authorize?provider=google`

`SUPABASE_TOKEN`  is the token in the dashboard

## To Reproduce

export const signIn = async (client: SupabaseClient) => {
  return await client.auth.signIn(
    { provider: 'google' },
    { redirectTo: `${window.location.host}/auth/callback` }
  );
};

use this in a supabase project, and you will not go to the redirection page. It doesn't display an error so i can't show much here.

## Expected behavior

That i just log in with google as usual

## Screenshots

 `token_in_url` ![Screenshot 2022-02-09 201305](https://user-images.githubusercontent.com/77443389/153273190-6ec9b596-2428-471b-b913-51029e0f65ec.png)

## System information

- OS: [Windows]
- Browser: brave
- Version of supabase-js: 1.30.0
- Version of Node.js: 16.13.1

**Comment by hf** [comment]
Hey @vincent-thomas, I'm not exactly sure what was not working for you. It is typical when using OAuth sign-in to experience a redirect, as that is how the OAuth protocol functions. The `authorize` endpoint you're seeing is how Supabase Auth handles the login request for social login, which would then immediately redirect you to Google's OAuth login page. Finally, you would be redirected back to the URL you specified under `redirectTo`. Make sure you have the correct redirect domain set in the [Supabase Dashboard](https://app.supabase.com/project/_/auth/settings).

I'm closing this issue as stale, but feel free to comment or re-open it again if you are still experiencing the same issue.
