### ISSUE TITLE
IMPROVE SUPABASE by adding this feature.

### ISSUE THREAD

**Issue by Luc069** [supabase/gotrue-js#357]
This feature wil make supabase 10 times better.
Make `onAuthStateChange` better, so it can run even if there is not an event going on. For example: "When page is loaded (in react: useEffect), run the function even if there is no event."

![image](https://user-images.githubusercontent.com/91779803/170571794-a695fd78-0cc3-471f-b833-fe7c4a03747b.png)

**Comment by hf** [comment]
Hey we're going to be considering a change in the API for the next major version. Thank you for the feedback!
