### ISSUE TITLE
Add ability to (read-only) query the auth.users table directly with a service key using supabase.js

### ISSUE THREAD

**Issue by miketromba** [supabase/gotrue-js#359]
# Feature request
I suggest adding the ability to query (read-only) the auth.users table directly with a service key. Many production apps need this ability...

## Describe the solution you'd like

```js
// In my case, I need to add additional users as 'owners' of a record using their email address

// Find user by email
const { data, error } = await supabase
  .from('auth.users') // Not possible now
  .select()
  .eq('email', 'user@gmail.com')

// Then use the user's data for some business logic
```

## Describe alternatives you've considered

Some developers have used workarounds like creating a public.users table which replicates relevant data from the auth.users table using triggers. This feels like a hacky workaround to me... I would much rather avoid this unnecessary redundancy / potential for data inconsistency down the line.

In my case, since I just need to be able to query for users by email, I've considered replicating a .email field to my public.profiles table. The problem is the same... the email field becomes redundant and opens up the possibility of data inconsistencies down the line. (E.g. user updates email with 3rd party provider which updates the auth.users table, but not my public.profiles.email field)

## Additional context

See: https://nikofischer.com/supabase-how-to-query-users-table

**Comment by JhaAman** [comment]
> Seems like this is possible by using a view:
> 
> ```sql
> create view public.users as select * from auth.users;
> revoke all on public.users from anon, authenticated;
> ```
> 
> Then you can `.select()` as usual with your `service_role` key.

This worked but seems like it's only limited to 1000 users - not sure if that's a limitation of views or something else.

**Comment by hf** [comment]
> > Seems like this is possible by using a view:
> > ```sql
> > create view public.users as select * from auth.users;
> > revoke all on public.users from anon, authenticated;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you can `.select()` as usual with your `service_role` key.
> 
> This worked but seems like it's only limited to 1000 users - not sure if that's a limitation of views or something else.

Probably a limitation of PostgREST. Please make sure you're setting correct limit and offset params.

**Comment by hf** [comment]
Closing this issue as we're not going to be exposing `auth.users` to the public at all -- there's some very sensitive data there like the password hash and other things.

You can use some of these workarounds at your own risk.

**Comment by mewc** [comment]
Use the view but only expose data you need. Heres a few, expand as needed

```
create view public.users as select id, email, role, email_confirmed_at, last_sign_in_at, created_at, updated_at, phone, is_sso_user, deleted_at from auth.users;
revoke all on public.users from anon, authenticated;
```

**Comment by Teiem** [comment]
If you start getting the error: `{
   "message": "An invalid response was received from the upstream server"
}`

delete your view and add it again.

(Email from Supabase support: Thank you for contacting Supabase Support. Recently we had to modify the type of the `phone` and `phone_change` columns in `[auth.users](https://github.com/supabase/gotrue-js/issues/auth.users)` which requires any triggers or views dependent on those columns to be recreated. You can fix this problem by recreating (dropping then adding again) the triggers and views that were using these columns.)

**Comment by FabianMontoya** [comment]
> Seems like this is possible by using a view:
> 
> ```sql
> create view public.users as select * from auth.users;
> revoke all on public.users from anon, authenticated;
> ```
> 
> Then you can `.select()` as usual with your `service_role` key.

It's works for me, but in my front I'm getting the error: `{"code":"42501","details":null,"hint":null,"message":"permission denied for view users"}`.
What could be my error?

**Comment by bart** [comment]
Not having the option to join users data (foreign user_id of auth.users) in my opinion is a show stopper. It is a common user case and not being able to that unfortunately puts Supabase into the "no option for a project" corner.

**Comment by FabianMontoya** [comment]
> 

Haha, my mistake, I ran `revoke all on public.users from anon, authenticated;` and it revoke all the permissions, only run `revoke all on public.users from anon;` for allow the access only to auth users

**Comment by eRuaro** [comment]
Hi! I want to send a bulk email but I'm only receiving 50 from calling the function. Is there a programmatic way to retrieve all the emails using the supabase SDK?

**Comment by kaelruland** [comment]
> Hi! I want to send a bulk email but I'm only receiving 50 from calling the function. Is there a programmatic way to retrieve all the emails using the supabase SDK?

You can paginate: `await supabase.auth.api.listUsers({page: 1, perPage: 100)`. The default `perPage` is 50.

**Comment by Picoquio** [comment]
> > Seems like this is possible by using a view:
> > ```sql
> > create view public.users as select * from auth.users;
> > revoke all on public.users from anon, authenticated;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you can `.select()` as usual with your `service_role` key.
> 
> It's works for me, but in my front I'm getting the error: `{"code":"42501","details":null,"hint":null,"message":"permission denied for view users"}`. What could be my error?

Same here. Could you find a fix?

**Comment by JeongJuhyeon** [comment]
Granting "all" to `service_role` or any permissions at all to `anon` or `authenticated` seems very risky. However simply having the ability to check e.g. the existence of a certain email from `service_role` is a common business need.

`GRANT SELECT (email) ON auth.users TO service_role;`

This way, you can keep your permissions as tightly scoped as possible.

**Comment by rkristelijn** [comment]
I think I found another workaround;

We have two use cases:
- we created tables that have system fields like created_by, updated_by that default to auth.uuid(), we would like to see the e-mail of the user using a join
- in the GUI we have a dropdown of the non-archived users

The workaround involves creating a table in the public schema that only holds the id and some identifier, like email or in our case full_name. That can be used to join and select from.

I didn't test when a user is created from our auth provider, but manual inserts result in the custom public.users table to be synced. 

I'm wondering if there are things I don't see in terms of security, maintainability. I don't understand why Supabase doesn't provide for a out of the box solution to be able to join in auth.users or query from it. Seems like functionality a lot of folks need.

```sql
-- create the table
CREATE TABLE public.users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    email VARCHAR NOT NULL,
    full_name TEXT,
    archived BOOLEAN DEFAULT FALSE
);
-- drop table public.users;

-- enable RLS

-- enable RLS Policy
CREATE POLICY "all_authenticated_users_can_select"
ON "public"."users"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
    true -- Allows all authenticated users to select all rows
);

-- load the data
INSERT INTO public.users (id, created_at, email, full_name)
SELECT 
    id, 
    NOW(), 
    email, 
    CASE 
        WHEN POSITION('.' IN SPLIT_PART(email, '@', 1)) > 0 THEN
            INITCAP(SPLIT_PART(SPLIT_PART(email, '@', 1), '.', 1)) || ' ' ||
            INITCAP(SPLIT_PART(SPLIT_PART(email, '@', 1), '.', 2))
        ELSE
            INITCAP(SPLIT_PART(email, '@', 1)) || ' ' || 
            INITCAP(SPLIT_PART(email, '@', 1))
    END
FROM auth.users;

-- sync_users trigger
CREATE OR REPLACE FUNCTION sync_users()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, created_at, email, full_name)
    VALUES (
        NEW.id,
        NOW(),
        NEW.email,
        CASE 
            WHEN POSITION('.' IN SPLIT_PART(NEW.email, '@', 1)) > 0 THEN
                INITCAP(SPLIT_PART(SPLIT_PART(NEW.email, '@', 1), '.', 1)) || ' ' ||
                INITCAP(SPLIT_PART(SPLIT_PART(NEW.email, '@', 1), '.', 2))
            ELSE
                INITCAP(SPLIT_PART(NEW.email, '@', 1)) || ' ' || 
                INITCAP(SPLIT_PART(NEW.email, '@', 1))
        END
    );
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- DROP FUNCTION IF EXISTS sync_users();

-- trigger
CREATE TRIGGER trg_after_user_insert
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION sync_users();
-- DROP TRIGGER IF EXISTS trg_after_user_insert ON auth.users;

-- testing
insert into auth.users (id, email) values (gen_random_uuid(), 'test.kees@domain.com')
-- delete from auth.users where email = 'test.kees@domain.com'
select * from public.users where email = 'test.kees@domain.com'
-- delete from public.users where email = 'test.kees@domain.com'
```
