### ISSUE TITLE
onAuthStateChange function returns SIGNED_IN instead of SIGNED_UP

### ISSUE THREAD

**Issue by HassanIyan** [supabase/gotrue-js#363]
on phone sign up from supabase.auth.onAuthStateChange function it returns signed in instead of signed up.
Please fix ASAP..

**Comment by hf** [comment]
Hey @HassanIyan, @BloxsmithDevelopment,

We want to try and keep the client library as unoppinionated as possible. Sign up is just a special case of a sign in, and it is somewhat difficult for the client library to keep track of state that way. If this is something you need, you can implement it by setting a flag in local storage or some other place. Additionally, you can always inspect the `created_at` property of the user object to see if the sign-up happened not a long time ago.

I'll close this issue as not planned, but feel free to comment if you need to provide more context.
