### ISSUE TITLE
redirectTo option on signUp and signIn not working

### ISSUE THREAD

**Issue by monsonjeremy** [supabase/gotrue-js#364]
# Bug report

## Describe the bug

I am developing on `localhost` of a NextJS app and cannot get redirects to work. 
I have the redirects set up in the auth tab and am using the code as shown in the docs.

## To Reproduce

Setup the redirect rules in the auth section of the project for `http://localhost:3000/access`.

Use the following code:
```javascript
const { error: e } = await supabase.auth.signUp(
  { email, password },
  { redirectTo: 'http://localhost:3000/access' }
);
```

## Expected behavior

Upon success the page should redirect to `/access`

## Screenshots

<img width="864" alt="Screen Shot 2021-12-06 at 10 00 17 PM" src="https://user-images.githubusercontent.com/8846086/144975568-9f0221e9-8f88-48fd-a9c2-5a874ed9c96e.png">

## System information

- Version of supabase-js: [latest]
- Version of Node.js: [e.g. 16]

**Comment by kangmingtay** [comment]
hey everyone, gonna close the issue now that this has been resolved
