### ISSUE TITLE
Better way to handle password resets.

### ISSUE THREAD

**Issue by zdb999** [supabase/gotrue-js#39]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, the Supabase client has an endpoint to request a magic link or a password reset. However, once the user clicks on that link and is redirected back to the application, there is no way to insert that access / refresh token back into the Supabase client. The only way to handle it is to use the GoTrue client, which feels hacky. Additionally, once they have reset their password with the GoTrue client, they will have to log in again with the Supabase client , as I believe they have two separate systems for maintaining a logged in user. (Please correct me if I am wrong here.)

## Describe the solution you'd like

I would like an addition to the Supabase auth api that allows someone to log in directly with an auth token instead of a user name and password. Additionally, it would be nice to have a way to get a new auth token with a refresh token. Basically, a nice wrapper around more of the GoTrue api that integrates with all the things you have built.

## Describe alternatives you've considered

I've thought about just using GoTrue directly for everything. However, I think that might cause problems with PostRest authentication, though I didn't get far enough to find out.

**Comment by kiwicopple** [comment]
> Now the password reset links log me in automatically, but does not do anything to help me actually reset my password.

Hey @zdb999, Can you clarify this one a bit? Maybe a repo or some code which we can see?

Are you using the same auth code as one of our `todo` examples? 
https://github.com/supabase/supabase/tree/master/examples/

**Comment by zdb999** [comment]
I tried to follow the Vue 3 example, though mine is a bit different because I am using a slightly different stack than the the example. I'm using Nuxt.js, and their configured version of Vuex and Vue router. I've stored the client inside of Vuex to centralize the access patterns.

I can successfully generate reset password emails using `supabase.auth.api.resetPasswordForEmail(email)`. When a user (me, for testing purposes) clicks on the link, it redirects to the home page with an url fragment. The client then logs me in automatically. However, I'm not sure how the app can tell the difference between a between a user being logged in by password recovery link, a magic link, or an email invite link. In the case of a recovery link, I would like to send them to a password recovery page, and in case of a email invite link, I would like to send them to a different welcome page. What's the best way to do this?

**Comment by awalias** [comment]
> However, I'm not sure how the app can tell the difference between a between a user being logged in by password recovery link, a magic link, or an email invite link

currently your app would have to detect the `type` in the url fragment, it can be `recovery`, `magiclink`, `invite`, or `signup`

**Comment by zdb999** [comment]
I've tried to do that, but I'm struggling to get the Nuxt middleware to recognize the URL with the fragment before the GoTrue/Supabase client grabs it, logs in, and rewrites the URL path. Will keep experimenting though. It would be extremely helpful if that `type` parameter could be injected into one of the objects provided by the `auth.onAuthStateChange` callback. All the other URL fragment parameters are already in the `session` object, but not that one.

**Comment by ykdojo** [comment]
Related discussion: https://github.com/supabase/supabase/pull/407

I think @kiwicopple's suggestion on that discussion might be helpful for solving this:

> I wonder if it's better to allow the developer to specify routes for actions in the dashboard (eg, you could specify /password_recovery). And if the route isn't provided we default to /?type=recovery

**Comment by thorwebdev** [comment]
I have a PR open that introduces a `PASSWORD_RECOVER` auth event: https://github.com/supabase/gotrue-js/pull/40

When this fires the user will have been logged on and you can now update their password using:

```js
const { error } = await supabaseClient.auth.update({ password })
if (error) setError(error.message)
else setMessage('Your password has been updated.')
```

**Comment by zdb999** [comment]
Thank you so much for this! I really appreciate the rapid response here. I just got the reset redirect working this evening.
