### ISSUE TITLE
Passwordless phone signup failing

### ISSUE THREAD

**Issue by vbylen** [supabase/gotrue-js#396]
# Bug report

## Describe the bug
```jsx
supabase.auth.signUp({
            phone: phone,
            password: password
        })
```
sends an OTP code, but
```jsx
supabase.auth.signUp({
            phone: phone,
        })
```
does not.

## Expected behavior

Allow phone sign up with and without password.

**Comment by kangmingtay** [comment]
hey @vbylen, when the `signIn` method is called with either a phone or email, a user will automatically be created if it doesn't exist. You can pass in the option `shouldCreateUser=false` if you don't want to create a user automatically.
