### ISSUE TITLE
don't send expired JWTs

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue-js#403]
We might want to verify the JWT expiry date locally before sending to the server to query for data, then if there's a `refresh_token` stored locally we might be able to refresh it before making the request, or otherwise triggering a listenable event on the client

related: https://github.com/supabase/supabase/discussions/889
related: https://github.com/supabase/supabase-js/issues/178

**Comment by cohlar** [comment]
I am still experiencing this issue with `"@supabase/supabase-js": "^2.1.4"` - I have only tried locally with `"supabase": "^1.24.0"`, not in production.

**Comment by hf** [comment]
If not fixed, with v2 there should be better behavior. We're not seeing problems on app.supabase.com or many other projects.

With #564 this should become even better. I'll close the issue now, do continue to comment if you have any further issues.

@cohlar Would you mind using the very latest v2 of the library. Do have in mind that if you're doing [server side rendering](https://supabase.com/docs/guides/auth/server-side-rendering) there can be some confusing behavior that looks like this issue.
