### ISSUE TITLE
[Feature Request] Emit a "ready state" event from onAuthStateChange

### ISSUE THREAD

**Issue by prescience-data** [supabase/gotrue-js#404]
# Feature request

## Is your feature request related to a problem?

When bootstrapping a frontend application, it is useful to block the final render until the application knows if it is authenticated or not.

The base `GoTrueClient` instance provides no real method to infer a post-recovery attempt ready state (only emits upon `SIGNED_IN` success event).

## Describe the solution you'd like

Would be awesome to augment the base `GoTrueClient` to emit an event if a session is not auto-recovered at construction.

### References: 
**Triggers the auto-recovery:**
https://github.com/supabase/gotrue-js/blob/4312f53411dc6fdf963f8adb48200cddf9905bd9/src/GoTrueClient.ts#L77
**Only emits an event if the session is successfully recovered:**
https://github.com/supabase/gotrue-js/blob/4312f53411dc6fdf963f8adb48200cddf9905bd9/src/GoTrueClient.ts#L499

If the Supabase `supabase.auth` instance emitted an event in both success _and_ fail cases, then it would be possible to wrap the final render to await a decision:

### No auth state check:
```typescript
// Application mounts too early, meaning downstream route guards redirect to login due to an assumed unauthenticated state.
// Mount the application.
app.mount("#app")
```

### With additional state change event to signal ready state:
```typescript
// Specifics of state inspection can occur within a route guard.
// All we need to know is that the auth system has fully initialized one way or another.
supabase.auth.onAuthStateChange(() => {
  // Mount the application.
  app.mount("#app")
})
```

### Alternative 1
Currently, I am detecting the state change (on success) within the app's central authentication state manager and redirecting if the user is already on the login page, however, this is ugly/bad UX, so a pre-render blocking solution would be preferable.
 
### Alternative 2
A second alternative I tried previously was to race a `Promise` with a timeout, but that felt horribly un-atomic, which is why I landed on the prior alternative:

```typescript
Promise.race([
  () =>
    new Promise<void>((resolve) => {
      setTimeout(resolve, 100)
    }),
  () =>
    new Promise<void>((resolve) => {
      supabase.auth.onAuthStateChange((event) => {
        if (event === "SIGNED_IN") {
          resolve()
        }
      })
    })
]).then(() => {
  app.mount("#app")
})

```

**Comment by hf** [comment]
Hey everyone. We are going to reconsider the behavior of `onAuthStateChange` in the next revision based on this feedback.

For now, please make sure you understand that the very first event (typically when the session is loaded from local storage or the URL fragment) typically fires **before any React hooks run and components are mounted**. For this reason you can't rely solely on the event callback to load the initial state of your components. Always use the `getSession()` method in combination with the callback.

I'll close this issue for now, please re-open if you feel it has not been sufficiently addressed.
