### ISSUE TITLE
Strongly Typed Errors

### ISSUE THREAD

**Issue by malobre** [supabase/gotrue-js#405]
# Feature request

## Is your feature request related to a problem? Please describe.
It is currently impossible to differentiate errors, e.g: when a user signs up there is a multitude of possible errors (network errors, database errors, etc) and although you can easily check if an error occured (`if (res.error !== null) { /**/ }`) it is not possible to know **which** error happened.

## Describe the solution you'd like
Enum error types:
```ts
enum SignUpError {
  InvalidEmail,
  SignUpsDisabled,
  NetworkError,
  /* etc */
}

enum SignInError {
  InvalidCredentials,
  /* etc */
}
```
```ts
export default class GoTrueClient {
  // --snip--
  signUp(credentials: {
      email: string;
      password: string;
  }): Promise<{ /* success object */ } | SignUpError>;
  
  signIn(credentials: {
      email?: string;
      password?: string;
      provider?: Provider;
  }): Promise<{ /* success object */ } | SignInError>;
  // --snip--
}
```

## Describe alternatives you've considered

I am not aware of any alternative.

**Comment by kangmingtay** [comment]
Hey everyone, we've taken this feedback into consideration and this is now available in the `rc` branch (soon to be released in supabase-js/v2)! Will be closing this for now.
