### ISSUE TITLE
Type 'AsyncStorageStatic' is missing the following properties from type 'Storage': length, key

### ISSUE THREAD

**Issue by DarkPonyBee** [supabase/gotrue-js#408]
# Bug report

`localStorage` field in `options` of the `createClient` method doesn't support type for AsyncStorage.

## Describe the bug

I tried to use supabase authentication in the React Native TypeScript mobile application.
In React Native application, it uses the AsyncStorage as a storage.
When I pass the AsyncStorage as a localStorage, it triggers `Type AsyncStorageStatic is missing the following properties from type Storage.` error.

## To Reproduce

```js
import { createClient } from '@supabase/supabase-js'
import AsyncStorage from '@react-native-community/async-storage'

export const supabase = createClient(
  URL, API_KEY, {
    localStorage: AsyncStorage
  }
)
```

## Expected behavior

localStorage should support type for AsyncStorage.

## Screenshots

![Screenshot at Mar 15 23-25-41](https://user-images.githubusercontent.com/68030494/111251524-cee43780-85e5-11eb-9787-e04565175f70.png)

## System information

- OS: macOS
- Version of @supabase/supabase-js: 1.6.0

**Comment by kangmingtay** [comment]
Hey everyone, seems like this is no longer an issue now that we've typed the supported storage to account for RN's async storage. (https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L225) 

Will be closing this issue but feel free to reopen and elaborate if it's still a problem.
