### ISSUE TITLE
Trigger onAuthStateChanged on server side with v2

### ISSUE THREAD

**Issue by bhvngt** [supabase/gotrue-js#413]
# Bug report

## Describe the bug

In `v1` `setAuth` would trigger `onAuthStateChange` handler with `TOKEN_REFRESH` event. `setAuth` has been deprecated in v2 and instead it has been [recommended](https://supabase.com/docs/reference/javascript/next/release-notes#deprecated-setauth) to create new client with `global->headers->Authorization` config. However, with this approach, `onAuthStateChange` will not get triggered. This breaks quiet a few of my test cases. 

An alternate solution would be very much appreciated.

## System information

- OS: macOS
- Version of supabase-js: v2.0.0-rc.5
- Version of Node.js: v18.7.0

**Comment by kangmingtay** [comment]
hey @bhvngt, have you tried using the [`setSession`](https://github.com/supabase/gotrue-js/blob/a15296288d15919d2ec8a64654a545a375fb3a57/src/GoTrueClient.ts#L536) method yet? 

One problem we realised with `setAuth` was that the session being set isn't actually representative of a `TOKEN_REFRESHED` event. This is because `setAuth` just sets the access token provided in the current session without actually checking if the access token and refresh token is valid.

`setSession` aims to solve this problem by taking in a `refresh_token` and always forcing a refresh. This ensures that you will always get back a valid session that contains an `access_token` and a new `refresh_token`

**Comment by bhvngt** [comment]
Thanks @kangmingtay for your explanation. I have been grappling with setting up user session on the server side. I used to use `setAuth` mainly for this purpose.

With v2, here'e the code that I have tried with result annotated in comments

```typescript
const client1 = createClient(supabaseUrl, anonKey);
client1.auth.onAuthStateChange((event) => {
  console.log(`client2 event`, event); // prints SIGN_IN ✅
})
const {data: {session: session1}} = await client1.auth.signInWithPassword({email, password});
console.log("session1?.access_token", session1?.access_token) // prints access_token ✅

const client2 = createClient(supabaseUrl, anonKey, {global: {headers: {Authorization: `Bearer ${session1?.access_token}`}}});
client2.auth.onAuthStateChange((event) => {
  console.log(`client2 event`, event); // does not get called ❌
})
const {data: {session: session2}} = await client2.auth.getSession()
console.log(`session2`, session2); // prints null ❌

const client3 = createClient(supabaseUrl, anonKey);
client3.auth.onAuthStateChange((event) => {
  console.log(`client3 event`, event); // prints TOKEN_REFRESHED ✅
})
const {data: {session: session3, user: user3}} = await client3.auth.setSession(session1?.refresh_token ?? "");
console.log(`session3?.access_token`, session3?.access_token); // prints session access token ✅
console.log(`user3`, user3?.id); // prints user id ✅
```

creating client by sending `bearer access_token` via `global authorization` header does not seems to be working. This has been [reported](https://github.com/supabase/gotrue-js/pull/340#issuecomment-1256124963) by other users also.

So it seems that I should be using `setSession` with refresh_token. Currently, I am using following workflow

1. On successful sign in, I get the session object in the browser
2. Then I send `refresh_token` extracted from the `session` object to my server to conduct user related backend job. 

However my concern is that with this approach I will invalidate the refresh_token that is available to the browser thus `breaking the front-end experience`. Since the refresh_token that was used to get the session information on the server has been invalidated hence the front-end now has an invalid refresh_token. 

Is that a valid concern or I have misunderstood the api call? 

Is this the recommended way to set user session on the server?
