### ISSUE TITLE
V2 getUser with no session and no jwt builds incorrect jwt, incorrect authorization header and gets 401 error

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/gotrue-js#416]
# Bug report
When called without a session and a JWT parameter this code:
https://github.com/supabase/gotrue-js/blob/66cebfad24d77f610a92a88d40f5d9bc025cf7c5/src/GoTrueClient.ts#L479

is incorrect.  It copies "bearer longjwt" to the jwt.
When this happens and the request goes out the header is now:

![image](https://user-images.githubusercontent.com/54564956/187030154-cdef5b09-007b-4d17-9b71-b4914aaef3b4.png)

## To Reproduce

Call getUser() on a browser with no local storage from previous sign in.

## Expected behavior

Correct jwt and header set.

Actually would have preferred getUser just return null with no jwt parameter and no session in local storage instead of wasting time sending the anon jwt to the gotrue server.

I used .user() in v1 to see if there was a user in local storage, in v2 I converted that to getUser, but missed that it will attempt to call the database. Now switched to getSession and then session.user.

## System information
supabase-js rc.6

**Comment by robertn702** [comment]
I wish I saw this earlier. Just spent a lot of time finding the same line of code 😅

**Comment by hf** [comment]
I believe this has been fixed.
