### ISSUE TITLE
output of oAuth signin in v2

### ISSUE THREAD

**Issue by bhvngt** [supabase/gotrue-js#417]
# Improve documentation

## Link 
https://supabase.com/docs/reference/javascript/next/auth-signinwithoauth#examples

## Describe the problem

oAuth signin example in the link above suggest that `signInWithOAuth` returns regular `data` object that contains `session`.For ref: it documents following line in the code snippet.

```javascript
const oAuthToken = data.session.provider_token // use to access provider API
```

In `v1` it used to return `User` and `Session` object.

However while trying to migrate I discovered that [OAuthResponse](https://github.com/supabase/gotrue-js/blob/66cebfad24d77f610a92a88d40f5d9bc025cf7c5/src/lib/types.ts#L66) return provider name and `url` returned by the provider. I am not sure if this is intentional or is it work in progress? Because, it seems inconsistent with other auth methods and `v1` and it is also different from what the `v2` documentation is suggesting.

###Is the documentation missing? Or is it confusing? Why is it confusing?

 It is confusing

## Describe the improvement

Ideally, I would prefer if the `signInWithOAuth` returns `data` object of type [AuthResponse](https://github.com/supabase/gotrue-js/blob/66cebfad24d77f610a92a88d40f5d9bc025cf7c5/src/lib/types.ts#L50) to keep it consistent. If not then the example should describe how one can derive `Session` and `User` object from `OAuthResponse` object.

**Comment by saschwarz** [comment]
I'm trying to migrate to v2 and I also can't figure out how to get the authenticated user when using `signInWithOAuth`

**Comment by ankushg** [comment]
Hi, also curious about this -- are there any examples on how to get a `Session`/`User` object after getting an `OAuthResponse`?

Are we supposed to just call `supabase.auth.getSession()` after we get a non-error `OAuthResponse`?

**Comment by hf** [comment]
If I'm not mistaken [`signInWithOAuth`](https://supabase.github.io/gotrue-js/v2/classes/GoTrueClient.html#signInWithOAuth) will basically never return a `data` object in a browser. (At least not in this form.)

This is because the way OAuth sign-in works is the current window location will be set to the authorization URL for the OAuth provider. If calling from a non-browser environment such as React Native, Flutter or other such environments, since there's no `window.location` there you will receive the URL to open in a browser.

I've added an option that will let you access the data object in #575.

**Comment by saschwarz** [comment]
@hf I looked at #575 but there don't seem to be any examples/documentation on how to use that new option to get the session/user?

**Comment by hf** [comment]
Unfortunately the OAuth flow is very asynchronous and I'm not super keen on adding hacks such as:

```typescript
new Promise((accept, reject) => {
  supabase.auth.onAuthStateChange((event, session) => {
    if (event === 'SIGNED_IN') { accept(session) }
  })
})
```

You kinda have to do this via the `onAuthStateChange` callback for the time being. I'm happy to discuss other ideas if you have any.

**Comment by saschwarz** [comment]
@hf I don't think anyone is asking for the code to change. When you closed this ticket your comment implied the pull request included the documentation requested in this case.  But, when I looked at the pull request it adds a new flag and I didn't see the connection between the flag and the documentation requested by this issue.

In v1 it was clear how you got the user/session. I just re-checked and the current documentation/auth video doesn't have any links or examples (that I could find) about what new devs need to do once they call `signInWithOAuth`. 

So I think this request for documentation is still valid.

**Comment by hf** [comment]
> So I think this request for documentation is still valid.

Yes you're right. Reopening.

**Comment by saschwarz** [comment]
@hf I didn't see any documentation updates as part of #572 ? Is there a documentation of using OAuth in v2 and getting the User and Session?

**Comment by Jpaulsisson** [comment]
Can someone please just explain to me how to get the user and session data from the signInWithOAuth method so I can move on with my life?
