### ISSUE TITLE
2.0.0-rc.8 getSession() return null after login

### ISSUE THREAD

**Issue by SatouKuzuma1** [supabase/gotrue-js#426]
# Bug report
`auth.getSession()` returns null 
## Describe the bug
I'm redirecting to `'/'` when I login but `getSession()` returns null which I'm not sure why is happening. 

## To Reproduce
This is my login function 
`const onSubmit: SubmitHandler<LoginValues> = async (loginValues) => {
    const { data, error } = await supabase.auth.signUp(loginValues);
    if (data.user) {
      router.push("/");
    } else {
      alert(error ? error : "An unknown error ocurred");
    }
  }`

 and on the server  `const { data, error } = await supabase.auth.getSession()`

## Expected behavior
session returns null

## System information

- OS: macOS
- Browser  chrome
- Version of supabase-js: 2.0.0-rc.8
- Version of Node.js: 18.0.0

**Comment by alaister** [comment]
Hey @SatouKuzuma1,

> and on the server `const { data, error } = await supabase.auth.getSession()`

To clarify, are you calling `signUp` in the browser and then calling `getSession` on the server side?

`gotrue-js` uses `localStorage` by default, meaning the session will not be synced to the server. You might like to check out the [auth-helpers](https://github.com/supabase/auth-helpers), which will help keep everything in sync for you. (Although I think you'll have to use the rc version there too at the moment!)

**Comment by SatouKuzuma1** [comment]
@alaister yes, just like you said ‘SignIn’ on the browser and ‘getSession’ on the server.

**Comment by alaister** [comment]
No worries. By the rc version, I mean the next version of the [auth-helpers](https://www.npmjs.com/package/@supabase/auth-helpers-nextjs/v/0.4.0-next.0). For example `npm install @supabase/auth-helpers-nextjs@next`.

I'm going to close this as mentioned in my previous comment this isn't a (first party) supported use case of `gotrue-js`.
If I'm misunderstanding the issue you're having, please feel free to reopen this, and we can work it out.

Thanks!
