### ISSUE TITLE
Fire `onAuthStateChanged` events across multiple tabs

### ISSUE THREAD

**Issue by probablykasper** [supabase/gotrue-js#427]
# Bug report

## Describe the bug

When signing in/out in one window, other windows are not updated. It seems like Supabase only updates when you select/unselect a tab.

When switching between tabs, it also doesn't seem to be called specifically when logging out (this worked on v1)

## To Reproduce

Have a website open in two windows, sign in/out in one of them

## Expected behavior

`onAuthStateChange` should be called on the other windows

## System information

- OS: macOS 10.15
- Browser: Brave
- Version of supabase-js: 2.0.0-rc.8
- Version of Node.js: 16.15.0

## Additional context

Should be fixable using [the Window storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event)

**Comment by hf** [comment]
Will likely be fixed with #566.
