### ISSUE TITLE
supabase-js 2.0rc8: React native support

### ISSUE THREAD

**Issue by alexreyes** [supabase/gotrue-js#431]
# React native support for supabase-js v2

After installing supabase-js 2.0rc8, I get a bunch of errors in my react native (expo managed) project. 

## Describe the bug

Immediately after installing `supabase-js@2.0rc8`: ```Error: URL.hostname is not implemented```

After I installed a polyfill for the URL library ([react-native-url-polyfill](https://www.npmjs.com/package/react-native-url-polyfill)), I started to get a new error: ```undefined is not an object (evaluating 'globalThis.localStorage.getItem')```

## To Reproduce

1) Create a new expo project
2) Install `supabase-js@2.0rc8`
3) Create a supabase client

## Expected behavior

It should work the same was as supabase-js v1 works on react native (seamlessly) 

## System information

- OS: iOS
- Version of supabase-js: v2.0rc8
- Version of Node.js: v16.13.1

## Other context

The reason I'd like to use Supabase v2 on react native is I need the async `getUser()` function which is available only on v2. I need the `getUser()` function because the regular `supabase.auth.user()` function on supabase-js v1 results in a screen flicker when switching between pages since the result is initially `null` when loading.

**Comment by alaister** [comment]
Hey @alexreyes,

It sounds like `react-native-url-polyfill` isn't registering before `createClient` is being called. I was able to get it working properly with the following setup in my `supabase.ts` file:
```typescript
import AsyncStorage from '@react-native-async-storage/async-storage'
import { createClient } from '@supabase/supabase-js'
import { setupURLPolyfill } from 'react-native-url-polyfill'

setupURLPolyfill()

const supabase = createClient(
  'https://yourref.supabase.co',
  'your.anon.key',
  {
    auth: {
      detectSessionInUrl: false,
      storage: AsyncStorage,
    },
  }
)

export default supabase
```

Also, a heads up on `getUser()`, it's not a direct replacement for `user()` in V1, as it makes an HTTP request every time it's called for the user. Here's how I'd get the user in V2:

```typescript
const {
  data: { session },
  error,
} = await supabase.auth.getSession()

if (error) {
  // handle error
}

const user = session?.user
```

I'm going to go ahead and close this, but feel free to reopen it if this doesn't fix it for you!

**Comment by alexreyes** [comment]
Yup, the problem turned out to be that I wasn't calling `createClient()` with the auth object. The updated version that you sent fixed it!

```
const supabase = createClient(
  'https://yourref.supabase.co',
  'your.anon.key',
  {
    auth: {
      detectSessionInUrl: false,
      storage: AsyncStorage,
    },
  }
)
```

**Comment by tyrauber** [comment]
@alaister, thank you for this. Just a quick addition, `react-native-url-polyfill` does not work for expo web - it throws a punycode conflict on new URL in supabase-js.  So, if you need a multi-platform expo solution, you need to initialize the polyfill conditionally.

```
import { Platform } from 'react-native';
import { setupURLPolyfill } from 'react-native-url-polyfill'

if(Platform.OS !=='web'){
  setupURLPolyfill()
}
```
