### ISSUE TITLE
Gotrue server throwing 500 error

### ISSUE THREAD

**Issue by kylerummens** [supabase/gotrue-js#434]
# Bug report

## Describe the bug

On my client API, i have a validation middleware that that takes a JWT from the authorization header and passes it to `supabase.auth.api.getUser(jwt)`.

This has been working for months on our production api, but just today started throwing a 500 error for all requests:

`{ message: 'Internal server error', status: 500 }`

I have already made a ticket in the Supabase dashboard but have not received a response.

**Comment by kylerummens** [comment]
I've been able to do a small amount of debugging from the Supabase Auth logs. It seems like this is the log from GoTrue that is a little more insightful:

```
{
  "component":"api",
  "error":"Session not found",
  "level":"error",
  "method":"GET",
  "msg":"Unhandled server error: Session not found",
  "path":"/user",
  "referer":"",
  "remote_addr":"****************",
  "timestamp":"2022-09-09T04:33:43Z"
}
```

**Comment by hf** [comment]
Please [open a support ticket](https://app.supabase.com/support/new) if you need immediate help with a project.

Issues on this repository are for API bugs and enhancements only.
