### ISSUE TITLE
setSession cannot be used in a multi-tab situation (v2)

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/gotrue-js#441]
# Bug report

## Describe the bug

With two or more tabs running with a shared refresh token from localStorage, setSession will get a new refresh token and invalidate the first shared token if after the reuse window.  Then the 2nd tab will try and refresh with the original shared token and get 400 error.  This will invalidate all tokens and clear localStorage.

## To Reproduce
This is run in two tabs, refreshing the 2nd tab 20 seconds or so after starting, so that it staggers the setSession after the reuse window.
```
var supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY)

async function app () {
    const {data: sessionData} = await supabase.auth.getSession()
    if (!sessionData.session) {
        const {data} = await supabase.auth.signInWithPassword({
                email: 'myemail',
                password: 'mypassword'
        )
    }
           //run setSession after reuse window
    if (sessionData.session) {
        console.log('sessionData', sessionData,sessionData.session.refresh_token)
                setTimeout(function () {
                    supabase.auth.setSession(sessionData.session.refresh_token).then(data => {
                        console.log('set Session',data.data.session.refresh_token)
                    })
                }, 15000)
    }
    const { data: listener } = supabase.auth.onAuthStateChange(
        async (event, session) => {
            console.log(event, session)
        })
```
## Expected behavior
Either document you can't use setSession in a multitab environment or handle refresh token changes like in v1 (or similar method).

## Screenshots

![image](https://user-images.githubusercontent.com/54564956/190514584-a9b7e842-643f-453e-9a20-c57531929d93.png)
1) tab1 starts
2) tab1 runs setSession 15 seconds later
3) tab2 starts 11 seconds later
4) tab 2 runs setSession 15 seconds later (this uses up the shared token)
5) tab 1 runs timer refresh 24 seconds later with invalid now token
## System information

Javascript
supabase-js-2.0.0-rc.10

**Comment by hf** [comment]
I believe this will also be taken care of with #564.
