### ISSUE TITLE
2nd Tab starting 10 seconds before expiration of session can cause 400 error on token refresh and loss of refresh tokens

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/gotrue-js#442]
# Bug report

## Describe the bug
If a tab is running and a second tab starts up with createClient (or possibly becoming visible ... not tested) 10 seconds before expiration of session, a timing rounding error appears to cause refreshing of tokens to fail because of a reuse violation.

This is somewhat random, but by building a timer to delay the createClient call of the second tab to line up with the 10 second expiration time frame it can be made to fail with a "few" trys.

I suspect the failure is due to rounding error and network timing variability right at the 10 second boundary in this code:
https://github.com/supabase/gotrue-js/blob/a15296288d15919d2ec8a64654a545a375fb3a57/src/GoTrueClient.ts#L873
```
    const expiresAt = session.expires_at
    if (expiresAt) {
      const timeNow = Math.round(Date.now() / 1000)
      const expiresIn = expiresAt - timeNow
      const refreshDurationBeforeExpires = expiresIn > EXPIRY_MARGIN ? EXPIRY_MARGIN : 0.5
      this._startAutoRefreshToken((expiresIn - refreshDurationBeforeExpires) * 1000, session)
```

A failing case:
![10secondviolation](https://user-images.githubusercontent.com/54564956/190873852-9477fb26-075f-4d44-938a-464a4e14e85c.JPG)

Note: The 2nd tab starts with 211msec left before the session expires on it's refresh timer based on the above formula in this case.

The refresh timers set up on alternating 10 seconds time frames.

In case #3 one tab uses the refresh token and the next tab tries to refresh the same token 10.116 seconds later and violates the default reuse setting of 10 seconds, resulting in an invalid token error and logout of user.

I suspect the same error could occur on a tab coming back visible right at the 10 second boundary also.

## To Reproduce

This is somewhat difficult to reproduce constantly...
Basically I wrote javascript to init the client and monitor token refresh.  I use a localStorage variable to set the time the first tab starts and use that to delay the start of the client init on the second tab by 20 seconds (with a 30 second token refresh).  The first tab also does a signIn, the second does not and relies on the Supabase session in localStorage.

```
console.log('start')
async function app (supabase1) {
    let supabase = supabase1.createClient(SUPABASE_URL, SUPABASE_KEY)
    if (firstTab) {
        console.log('first tab signin', firstTab)
        const {data} = await supabase.auth.signInWithPassword({
                email: 'email',
                password: 'pass'
            }
        )
    }
    const { data: listener } = supabase.auth.onAuthStateChange(
        (event, session) => {
            console.log(event, session)
            const expiresAt = session.expires_at
            if (expiresAt) {
                const timeNow = Math.round(Date.now() / 1000)
                const expiresInExact = expiresAt - Date.now()/1000
                const expiresIn = expiresAt - timeNow
                const refreshDurationBeforeExpires = expiresIn > 10 ? 10 : 0.5
                const timer = (expiresIn - refreshDurationBeforeExpires) * 1000
                console.log('refresh calc ',expiresIn,expiresInExact,timer)
            }
        })
}
let time = Date.now()
let syncTime = localStorage.getItem("syncTime")
let firstTab = true
console.log('syncTime ',syncTime)
if (syncTime) {
    console.log('second tab ',time)
    localStorage.setItem("syncTime", '')
    startTime = syncTime*1 + 20700 - time
    firstTab = false
}
else {
    console.log('first tab ',time)
    localStorage.setItem("syncTime",time)
    startTime = 1
}
console.log('start time ',startTime)
setTimeout(function () {
    app(supabase)
}, startTime)
```

## Expected behavior
Robust handling of edge cases.
If the reuse interval is increased to 12 seconds this specific problem probably goes away.

But I think the rounding error could also cause a failure to refresh the token in time in other cases.  If there are 9.501 seconds left to expire, gotrue-js sets the timer to 9.5 seconds.  With only .001 seconds margin left in the jwt this could cause an issue if the client makes a call right at that point.  Note I do not know if there is any margin in the expire time on the server.  Edit: in checking this further looks like about a second of margin because jwt expire is in seconds and time needs to be 1 second higher to be expired.

## System information
supabase 2.0.0-rc.10

**Comment by hf** [comment]
Thank you so much for the analysis. This is an issue that I believe #564 will address these issues.
