### ISSUE TITLE
Error: You must provide a OpenID Connect provider with your id token and nonce. 

### ISSUE THREAD

**Issue by ulbqb** [supabase/gotrue-js#452]
# Bug report

## Describe the bug

I want to login with firebase id token by OpenID Connect.  The firebase id token does not have nonce. But `supabase-js` does not support id token without nonce.

## To Reproduce

case 1

```javascript
await supabase.auth.signIn({
  oidc: {
    id_token: firebaseIdToken,
    client_id: OIDC_CLIENT_ID,
    issuer: OIDC_ISSUER,
  },
});
```

```
Error: You must provide a OpenID Connect provider with your id token and nonce.
```

case 2

```javascript
await supabase.auth.signIn({
  oidc: {
    id_token: firebaseIdToken,
    nonce: "",
    client_id: OIDC_CLIENT_ID,
    issuer: OIDC_ISSUER,
  },
});
```

```
Error: You must provide a OpenID Connect provider with your id token and nonce.
```

case 3

```javascript
const res = await supabase.auth.signIn({
  oidc: {
    id_token: firebaseIdToken,
    nonce: "hogehoge",
    client_id: OIDC_CLIENT_ID,
    issuer: OIDC_ISSUER,
  },
});
console.log(res)
```

```
{
  user: null,
  session: null,
  error: {
    message: 'Passed nonce and nonce in id_token should either both exist or not.',
    status: 400
  }
}
```

## Expected behavior

Login with id token without nonce by OpenID Connect.

## System information

- OS: macOS
- Version of supabase-js: 1.35.7
- Version of Node.js: 14.18.0

**Comment by ulbqb** [comment]
workaround

```javascript
await supabase.auth.api.signInWithOpenIDConnect({
  id_token: idToken,
  client_id: OIDC_CLIENT_ID,
  issuer: OIDC_ISSUER,
})
```

**Comment by tlebeitsuk** [comment]
I'm getting the same error and the workaround doesn't work for me.

**Comment by ulbqb** [comment]
@tlebeitsuk 

> ## System information
> 
> - OS: macOS
> - Version of supabase-js: 1.35.7
> - Version of Node.js: 14.18.0

I appended system info into the issue description. Even if the versions are the same, won't workaround work?

**Comment by tlebeitsuk** [comment]
Same but Node 16.

**Comment by ulbqb** [comment]
@tlebeitsuk 
I tryed Node 16, but the workaround work. What is the error?

**Comment by megacherry** [comment]
@ulbqb @tlebeitsuk
There are currently many open points regarding the endpoint, see also here:
https://github.com/supabase/gotrue/issues/434
https://github.com/supabase/gotrue/issues/412

**Comment by hf** [comment]
OIDC with Firebase ID tokens is not supported. Only Google and Apple OIDC sign-ins are supported at this time.

Please re-open this issue if you feel like I'm missing something.
