### ISSUE TITLE
Supabase authentication with discord did not get any result from supabase after successful login

### ISSUE THREAD

**Issue by dheeraj2414** [supabase/gotrue-js#453]
- Angular 13
- Superbase

Getting no data after successful login using suparbase discord method.

https://user-images.githubusercontent.com/103170259/191703096-acc9706f-b702-4c55-b75d-9c62632e5b6f.mp4

**Comment by J0** [comment]
Hey @dheeraj2414,

Can I check if this is still an existing issue? The metadata should be stored in the `raw_user_meta_data` column on `auth.users`

**Comment by J0** [comment]
Closing as the issue seems to have gone stale
