### ISSUE TITLE
`signIn` to open flow in a pop-up or new tab

### ISSUE THREAD

**Issue by Olyno** [supabase/gotrue-js#460]
# Bug report

## Describe the bug

Signin with a provider redirects the user to the associated provider. Problem: because the user didn't accept to login with his provider's account, we can't get the user, and because the redirection is happening after
```js
await client.auth.signIn({ provider: 'google' });
```

So the user still "null"

## To Reproduce

1. Create a new project
2. Adds a provider on a click event
3. See the problem

## Expected behavior

Do not make any redirection. The best is probably to open all redirection in another windows, and when the user signins using the provider, then after that making the redirection if needed.

## System information

- OS: Linux Deepin OS
- Browser (if applies) Chrome
- Version of supabase-js: ^1.18.1
- Version of Node.js: v14.16.1

**Comment by hf** [comment]
I moved this ticket from the GoTrue repo to here, and changed the title to make it clearer. This should be added to the library whenever we can get to it.

**Comment by hf** [comment]
With #566 this is probably going to become somewhat possible. Keeping the issue open as we need a proper API to launch the flow in a new tab / popup.

**Comment by hf** [comment]
Also #575 may make this even more possible.

**Comment by ecancil** [comment]
> closing this issue because you can set `skipBrowserRedirect: true` in the [`signInWithOAuth` method](https://supabase.com/docs/reference/javascript/auth-signinwithoauth) which will return a URL that you can open in the pop-up or a new tab

So we're to implement the closing of the popup window and the communication back to the main window.  Shouldn't this be very basic supported behavior?
