### ISSUE TITLE
[Needs testing] AppData should only be updatable by an admin

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue-js#47]
# Chore

## Describe the chore

It looks like our `updateUser` function accepts an entire user object:
https://github.com/supabase/gotrue-js/blob/8b61cc39df22cf9e1d546df7e1d06e9b27c51556/src/GoTrueApi.ts#L162

Here is the user object:
https://github.com/supabase/gotrue-js/blob/8b61cc39df22cf9e1d546df7e1d06e9b27c51556/src/lib/types.ts#L12

The `app_metadata` field should ideally be updatable by the admin, and not by the user. This means it can be used for things like RBAC (netlify does it here: https://docs.netlify.com/visitor-access/role-based-access-control/)

Note, this is still an inferior system to using Postgres tables, since the user would need to log out/in to refresh their token/roles. 

## Additional context

- Perhaps this  is one which should be enforced on GoTrue server?

**Comment by kangmingtay** [comment]
This will be a breaking change for gotrue-v2 since the current `PUT /user` endpoint allows us to include `{"app_metadata": {...}}` in the request body. Will add it as a task internally for gotrue-v2.
