### ISSUE TITLE
New way of using setSession() gives me ReferenceError: Property 'Buffer' doesn't exist

### ISSUE THREAD

**Issue by lewisd1996** [supabase/gotrue-js#476]
# Bug report

## Describe the bug

In my react native app, I use react natives `Linking` to listen to redirects. This allows a user to log into my react native app via Google (in the mobile web browser).

**Beforehand**, my url listener would work and look like:

```
...
      if (refreshToken) {
        supabase.auth
          .setSession(refreshToken)
          .then(res => {
            console.log({res});
            setCurrentUser(res.data.user);
          })
          .catch(err => console.log({err}));
      }
...
```

**After** updating to `^2.0.0-rc.12`, I got a typescript error saying the `setSession()` method now wants more than just a refresh token:

`Argument of type 'string' is not assignable to parameter of type 'Pick<Session, "access_token" | "refresh_token">'.`

Now, my function looks like:
```
...
      if (accessToken && refreshToken) {
        supabase.auth
          .setSession({
            access_token: accessToken,
            refresh_token: refreshToken,
          })
          .then(res => {
            console.log({res});
            setCurrentUser(res.data.user);
          })
          .catch(err => console.log({err}));
      }
...
```

However now I get:
`[ReferenceError: Property 'Buffer' doesn't exist]`

Im guessing im doing something wrong? Perhaps the way im passing in data? I can confirm I have an access token and refresh token.

## To Reproduce

1. Click login with Google
2. Login with google via a mobile browser
3. Return to app via deep linking
4. Beforehand, the user will be logged in and you will be moved onto the rest of the app, but now you're stuck on the login screen because supabase didn't log you in

## System information

- macOS (using XCode simulator for iPhone app)
- Version of supabase-js: ^2.0.0-rc.12
- Version of Node.js: v16.15.1

**Comment by soedirgo** [comment]
Do you have a stack trace of the `Buffer` error? It's not clear where the error is coming from.

**Comment by lewisd1996** [comment]
Unfortunately not, maybe it's because I am on react native? console logging error just gives me `[ReferenceError: Property 'Buffer' doesn't exist]`

**Comment by lewisd1996** [comment]
`{"_h": 0, "_i": 2, "_j": [ReferenceError: Property 'Buffer' doesn't exist], "_k": null, "_o": 2}`

`ReferenceError: Property 'Buffer' doesn't exist at decodeBase64URL`

I stopped using `catch()` and it gave me these errors instead ^^

**Comment by lewisd1996** [comment]
I've seen the issues going on at #473 and that would explain a lot. Although just using the refresh token works for me, I have seen some weird behaviour, so I should be using `access_token` and `refresh_token`. 

Sorry to bother you @soedirgo, any idea of what could be causing this? Im guessing it might be something to do with React Native?

**Comment by Aerilym** [comment]
As you know, I encountered the same issue (as referenced in the PR #473 ), In a recent reply I was told:

> Hey @Aerilym unfortunately you can't use setSession with a refresh token only. This was fixed in https://github.com/supabase/gotrue-js/pull/445

However, this seems to not line up with the documentation and the usage of setSession() in previous versions of supabase so I'm awaiting a response. Hope this helps.

**Comment by mikitasolo** [comment]
seems like under the hood GoTrue lib has `decodeBase64URL` function which tries to decode access token initially by using `atob` and if `atob` is not found by using `Buffer.from`. both approaches work well in Node.js but RN has no `atob` or `Buffer`. current fixes i've found consist of installing [rn-nodeify](https://www.npmjs.com/package/rn-nodeify)
```
export const decodeBase64URL = (value: string): string => {
  try {
    // atob is present in all browsers and nodejs >= 16
    // but if it is not it will throw a ReferenceError in which case we can try to use Buffer
    // replace are here to convert the Base64-URL into Base64 which is what atob supports
    // replace with //g regex acts like replaceAll
    return atob(value.replace(/[-]/g, '+').replace(/[_]/g, '/'))
  } catch (e) {
    if (e instanceof ReferenceError) {
      // running on nodejs < 16
      // Buffer supports Base64-URL transparently
      return Buffer.from(value, 'base64').toString('utf-8')
    } else {
      throw e
    }
  }
}
```

**Comment by j4w8n** [comment]
I don't know anything about React Native. Saw where a fork of rn-notify has this line in shim.js:

`if (typeof Buffer === 'undefined') global.Buffer = require('buffer').Buffer`

**Comment by sakymar** [comment]
It worked for me with rn-nodeify, I had errors when building on libs using "compile" in their `build.gradle` files so I did those patches: 

`diff --git a/node_modules/react-native-os/android/build.gradle b/node_modules/react-native-os/android/build.gradle
index 7055b60..784681d 100644
--- a/node_modules/react-native-os/android/build.gradle
+++ b/node_modules/react-native-os/android/build.gradle
@@ -44,5 +44,5 @@ repositories {
 }
 
 dependencies {
-    compile 'com.facebook.react:react-native:+'
+    implementation 'com.facebook.react:react-native:+'
 }
`

`diff --git a/node_modules/react-native-tcp/android/build.gradle b/node_modules/react-native-tcp/android/build.gradle
index c582eb7..5785289 100644
--- a/node_modules/react-native-tcp/android/build.gradle
+++ b/node_modules/react-native-tcp/android/build.gradle
@@ -44,6 +44,6 @@ repositories {
 }
 
 dependencies {
-    compile 'com.facebook.react:react-native:+'
-    compile 'com.koushikdutta.async:androidasync:2.1.6'
+    implementation 'com.facebook.react:react-native:+'
+    implementation 'com.koushikdutta.async:androidasync:2.1.6'
 }
diff --git a/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSocketManager.java b/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSocketManager.java
index df2007f..8353cd1 100644
--- a/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSocketManager.java
+++ b/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSocketManager.java
@@ -1,6 +1,6 @@
 package com.peel.react;
 
-import android.support.annotation.Nullable;
+import androidx.annotation.Nullable;
 import android.util.SparseArray;
 
 import com.koushikdutta.async.AsyncNetworkSocket;
diff --git a/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSockets.java b/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSockets.java
index 1bc07d2..8e6d5d5 100644
--- a/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSockets.java
+++ b/node_modules/react-native-tcp/android/src/main/java/com/peel/react/TcpSockets.java
@@ -5,7 +5,7 @@
 
 package com.peel.react;
 
-import android.support.annotation.Nullable;
+import androidx.annotation.Nullable;
 import android.util.Base64;
 
 import com.facebook.common.logging.FLog;
`

**Comment by Nikita-Chernenko** [comment]
I have the same error, when I call `await supabase.auth.setSession({access_token: accessToken, refresh_token:refreshToken})`, I get

[Unhandled promise rejection: ReferenceError: Can't find variable: Buffer]
at node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:408:58 in __awaiter$argument_3
at node_modules/@supabase/gotrue-js/dist/main/lib/errors.js:40:39 in CustomAuthError#constructor
at node_modules/@supabase/gotrue-js/dist/main/lib/errors.js:30:23 in <global>
at node_modules/react-native-rapi-ui/components/Avatar/Avatar.tsx:37:69 in Avatar
at http://192.168.0.9:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:124070:41 in handleDeepLinking
at src/navigation/index.tsx:9:0 in <global>

**Comment by j4w8n** [comment]
Docs have been updated to reflect using this witj RN. @lewisd1996 can you close this issue?

**Comment by Nikita-Chernenko** [comment]
> Docs have been updated to reflect using this witj RN. @lewisd1996 can you close this issue?
For the reference 
https://supabase.com/docs/reference/javascript/auth-setsession
