### ISSUE TITLE
Get user API endpoint returns HTTP 500 with supabase-js v2.0.0

### ISSUE THREAD

**Issue by Nekidev** [supabase/gotrue-js#491]
# Bug report

## Describe the bug

The API returns a 500 status code when fetching the logged in user after signup with discord or other providers.

## To Reproduce

```jsx
import { supabase } from '../utils/supabaseClient.js';

async function signIn(supabaseClient, provider) {
    const { data, error } = await supabaseClient.auth.signInWithOAuth({ provider: provider });
    if (error) console.log(error);
}

export default function Index() {
    const user = supabase.auth.getUser();

    user.then((user) => {
        console.log(user)
    });

    return (
        <button onClick={() => {
            signIn(supabase, "discord")
        }}>Sign in with Discord</button>
    );
}
```

## Expected behavior

It should return the user if successfully logged in, or otherwise return a proper error status code or raise an exception.

## Screenshots

![Console log](https://user-images.githubusercontent.com/84998222/196014344-5ac4bcce-a497-40e3-99e0-fab4782f9395.png)

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js:
```json
"dependencies": {
  "@heroicons/react": "^2.0.12",
  "@supabase/auth-helpers-nextjs": "^0.4.0",
  "@supabase/auth-helpers-react": "^0.3.0",
  "@supabase/supabase-js": "^2.0.0",
  "@supabase/ui": "^0.36.5",
  "@tailwindcss/line-clamp": "^0.4.2",
  "axios": "^1.1.3",
  "framer-motion": "^7.5.3",
  "next": "12.3.1",
  "react": "18.2.0",
  "react-dom": "18.2.0"
},
```
- Version of Node.js: `v16.16.0`

## Additional context

- Project plan: Free
- Database: Yes
- Storage: 1 bucket, 50mb total used space
- User plan: Free
- Server (is it this?): aws | us-east-1
- Providers enabled: Discord, GitHub, Email
- Other API endpoints: Working correctly
- Making the requests from locally-hosted server (localhost:3000)

**Comment by Shevly** [comment]
I too get this error, when I do getUser()

```js
{
  data: { user: null },
  error: AuthApiError: Internal server error
      at C:\Users\Riot\Documents\Project\node_modules\@supabase\gotrue-js\dist\main\lib\fetch.js:41:20
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    __isAuthError: true,
    status: 500
  }
}
```
Also no sign-in cookies are set in the browser.

**Comment by oleg-agapov** [comment]
Having same issue with `supabase.auth.getUser()` method which gives me error `500` because of:

```
/auth/v1/user
```

Also, is it a good replacement for `supabase.auth.user()` from v1? Asking because AFAIR in the first version the user was taken from localstorage, without making any requests. Maybe there is an alternative in v2

**Comment by j4w8n** [comment]
Mine works. I'm on v2.0.2

```js
const { data: { user } } = await supabaseClient.auth.getUser()
if (user) console.log(user)
```

**Comment by kangmingtay** [comment]
Hi @oleg-agapov, @Shevly, @Nekidev, it would be great if you guys can check the network tab to see what the response from `/auth/v1/user` is returning. You should also check the request headers (specifically the "Authorization header") to see if the user's JWT is being sent instead of the anon key.

**Comment by user72356** [comment]
I'm getting the same thing but from a node.js API function.

**Comment by kangmingtay** [comment]
hey @user72356, a claim refers to a key in the JWT object. This error message means that your JWT has no `sub` claim in it. Since every access token returned by gotrue always has a `sub` claim in it, this means that you might be passing another JWT to a gotrue endpoint that requires a user JWT. 

Can you please check the JWT payload being passed to gotrue via your network tab / your own server logs and see if that's the case?

**Comment by hf** [comment]
Closing this. Please reopen if you think this is still an issue.
