### ISSUE TITLE
Optionally pass jwt into `getSession()`

### ISSUE THREAD

**Issue by j4w8n** [supabase/gotrue-js#493]
# Feature request

## Is your feature request related to a problem? Please describe.

There's currently no way to get session info from `getSession()`, on the server-side of an app. Or at least not that I know of. This is because the method relies on the client-side localStorage (`persistSession`), or the Supabase client's `inMemorySession` - which likely wouldn't exist on a server-side Supabase client.

## Describe the solution you'd like

Allow a jwt access token to be passed into `getSession()`, just like `getUser()` allows, in order to return session info. I'm willing to work on a PR if this is a feature the team would consider.

**Comment by kangmingtay** [comment]
hey @j4w8n, have you tried using `setSession` to pass the JWT to a server-side Supabase client?

**Comment by j4w8n** [comment]
See https://github.com/supabase/gotrue-js/issues/496#issuecomment-1283887335 for why this doable, but not convenient.

**Comment by j4w8n** [comment]
After thinking about this more, allowing a jwt to be passed to `getSession()` isn't going to help much. See https://github.com/supabase/gotrue-js/issues/496#issuecomment-1283946941

Would be nice if we could set the session in a central server-side place, then allow the client to still have access to that session in other places on the server-side. My testing, so far, has not allowed this.
