### ISSUE TITLE
Make Subscription work across browser tabs

### ISSUE THREAD

**Issue by ixxie** [supabase/gotrue-js#494]
# Feature request

It would be great if `Subscription` (and thus `supabase.auth.onAuthStateChange`) would work across browser tabs; this was the behavior I actually expected (although maybe I was overly optimistic).

## Usecase

The usecase I am after is to reactively synchronize authentication changes between tabs. If a user signs out on one tab, the second tab should reflect this change of authentication state.

## Describe alternatives you've considered

One alternative is synchronizing authentication state by separate means somehow (e.g. using realtime subscriptions and a dedicated table); but as an app developing this is more effort than it is worth, and I would probably just go with the alternative of not bothering to synch browser tab authentication.

## Prior art

`swr` uses revalidate on focus: https://swr.vercel.app/docs/revalidation#revalidate-on-focus

**Comment by hf** [comment]
Will be addressed with #566.

Closing the issue so it doesn't linger around.
