### ISSUE TITLE
chore: Add "forgotPassword" functionality

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue-js#5]
# Chore

## Describe the chore

- Add `forgotPassword()` to the example: https://github.com/supabase/gotrue-js/blob/6d2ef91f738b8ee5339e4b3724f432acc1665ad2/example/src/App.js#L33

## Additional context

We should give a basic example of how to use `forgotPassword()`

**Comment by niits** [comment]
@kiwicopple Could I take it too?
