### ISSUE TITLE
Unable to sign in with the magic link

### ISSUE THREAD

**Issue by NandiyaLive** [supabase/gotrue-js#503]
# Bug report

## Describe the bug
When I try to authenticate an user with a magic link it redirects to `http://localhost:3000/#error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired`, even if it's a fresh magic link.

Code I'm using for the sign in
```
const { error, data } = await supabase.auth.signIn({
      email,
    });
```

client.js
```
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_API_KEY);

export { supabase };
```

## Screenshots
![image](https://user-images.githubusercontent.com/30690726/194193370-46a02d3d-3b37-412a-9468-418d286852c0.png)

## System information
```
"@supabase/supabase-js": "^1.35.7"
"next": "12.3.1"
"react": "18.2.0"
"react-dom": "18.2.0"
"react-redux": "^8.0.4"
```

**Comment by kangmingtay** [comment]
Hey @NandiyaLive and @DanMossa, this could be because of email client's prefetching the email link before the user has the chance to click on it. We also noticed that some copy-paste tools have a setting that previews links on copy. Since magiclinks are one-time use only, any previewing of the links would invalidate the magiclink when it is actually clicked. 

If this is an issue for you, the current workaround is to use email OTPs instead by including `{{ .Token }}` in your email templates.

**Comment by DanMossa** [comment]
@kangmingtay Ah makes sense. Just to clarify though.

If `{{ .ConfirmationURL }}` is:
`https://custom.supabase.co/auth/v1/verify?token=<TOKEN_ID>&type=signup&redirect_to=https://<DOMAIN>.com/`

What part of that url is `{{ .Token }}`

**Comment by kangmingtay** [comment]
None of it, the token query param found in the `{{ .ConfirmationURL }}` is hashed whereas the `{{ .Token }}` returns the raw, unhashed token 

We have plans to add a new template variable `{{ .HashedToken }}` which will make to the `<TOKEN_ID>` field above

**Comment by DanMossa** [comment]
Ah I see. I guess I'm having trouble understanding how and where sending the unhashedToken would help in this case?

**Comment by kangmingtay** [comment]
@DanMossa when you want to send email OTPs instead, the user will be passing the unhashed token into `verifyOTP` which sends it as a `POST /otp` request to gotrue

**Comment by NandiyaLive** [comment]
@kangmingtay Now it works perfectly fine without doing anything. Thanx for the help tho :)

**Comment by zlocker01** [comment]
I got the same problem
