### ISSUE TITLE
Add a client method to manually refresh tokens before they expire

### ISSUE THREAD

**Issue by j4w8n** [supabase/gotrue-js#504]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, there's no proper way to "manually" refresh tokens before they expire. Calling `getSession()` or `setSession()` will refresh them after they've expired. I believe setting the `autoRefreshToken` client option to `true` will attempt a refresh once the time-until-expiration is less than 10 seconds. Some people may want to proactively get new tokens before the current ones expire, without using the `autoRefreshToken` client option.

## Describe the solution you'd like

A new client method which you can call to refresh tokens (aka a Session), no matter the expiry status of the current tokens.

## Describe alternatives you've considered

Currently, there's a bug in `setSession()` where you can pass in an empty string for `access_token` and you can refresh tokens whenever you'd like. This is what I've been doing.

**Comment by meznaric** [comment]
Just dealt with the same issue this morning, this is a temporary solution I came up with: 

`refreshAccessToken` was available in 1.x version.
```
    const {
      data: { session: data },
      error,
    }: // @ts-expect-error this is a private method that used to be public
    AuthResponse = await this.supabaseClient.auth._refreshAccessToken(
      refreshToken
    );
```

**Comment by j4w8n** [comment]
I've submitted PR #505 to get this added.

**Comment by j4w8n** [comment]
@meznaric you can now use the `refreshSession()` client method, as of supabase-js version 2.0.4.

Server-side usage:
`supabaseClient.auth.refreshSession({ refresh_token: 'token' })`

Client-side usage:
`supabaseClient.auth.refreshSession()`
