### ISSUE TITLE
How to access the currently logged in user on the server

### ISSUE THREAD

**Issue by danvoyce** [supabase/gotrue-js#507]
# Bug report

## Describe the bug

I'm using the supabase-js `Auth` api in a Next.js app and am trying to create a nice email sign in / up experience. 

With v1 of the api it seems the `sb-access-token` cookie is removed when the user refreshes the page, so to work around this I set it manually when the user logs in. Then I'm able to access the user on the server by doing `supabase.auth.api.getUserByCookie(req)`

I'm trying out v2 of the api to see if I can achieve this a bit more elegantly, but it seems I can't. The session is only saved to local storage meaning it can't be accessed on the server. Also, there's no `getUserByCookie` method with v2.

I've also tried `getUser` on the server, again with no avail.

Thanks in advance for any suggestions or help!

## Expected behaviour

Access the currently logged user on the server, e.g when using `getServerSideProps`

## System information

- Version of supabase-js: 1.35.7 / 2.0.0-rc.10

**Comment by j4w8n** [comment]
@danvoyce did you pass in the access_token when using `getUser()`? That'd be the way to do it on the server-side.

**Comment by danvoyce** [comment]
Apologies for the lack of response. Life getting in the way of me looking into this further! 

I have managed to get this working. [These docs](https://supabase.com/docs/guides/auth/server-side-rendering#bringing-it-together) gave me the answer.

So you do have to set cookies with the tokens when authenticating on the client, and then use `supabase.auth.setSession` on the server to read them.

For my specific use case I'm using next.js 13 with the new `app` directory structure. Once authenticated on the client and the cookies set, I call `router.refresh();`, [which seems to be the only current solution to (sorta) triggering a rerender](https://beta.nextjs.org/docs/data-fetching/mutating). You can then read the cookies and get the user data like so

```typescript
const getUser = async (): Promise<User | undefined> => {
  const nextCookies = cookies();
  const refreshToken = nextCookies.get("my-refresh-token")?.value;
  const accessToken = nextCookies.get("my-access-token")?.value;

  let response;

  if (refreshToken && accessToken) {
    response = await supabase.auth.setSession({
      refresh_token: refreshToken,
      access_token: accessToken,
    });
  } else {
    console.log("User not authenticated.");
  }

  const { data, error } = response || {};

  if (error) {
    console.error(error);
  }

  return data?.session?.user;
};
```

Bit messy but it actually works quite well

**Comment by hf** [comment]
Please refer to the [Server Side Rendering](https://supabase.com/docs/guides/auth/server-side-rendering) docs which should make the flow a bit clearer on how you can achieve this. We recommend you use the helpers if possible as they do a lot of the heavy lifting for you.
