### ISSUE TITLE
onAuthStateChange sometimes skips firing after OAuth

### ISSUE THREAD

**Issue by simpautus** [supabase/gotrue-js#518]
# Bug report

I have a Remix app with `useEffect` hook in the app root component. In the hook I set a `onAuthStateChange` subscription to fire a form submission on `SIGNED_IN` event. This sometimes fires and sometimes not. It might work 5 times in a row and the just skip the next time like there was no event. When it happens I visit another browser tab and the event is fired after I focus back on the app tab. Not sure if the tab cycling would fire events anyway, but it also does the form submission with the correct data from the original oauth callback location hash.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I have set up a public repo loosely based on the Happy Days saas demo but ported to Remix Application Server (Node) and Supabase upgraded to V2. Also all functionality except the login part is removed.

Clone the repo, set up a Supabase environment with Github Oauth and provide the .env with url and anon key. Then you may need to try the Github login multiple (maybe very many) times but I bet you'll eventually skip the SIGNED_IN event.

[Repo here](https://github.com/simpautus/supabase-oauth)

## Expected behavior

The SIGNED_IN event gets fired every time there's a Github login.

## System information

- Remix 1.7.3
- React 18.2
- Supabase 2.0.4
- macOS / iPhone / Chrome / Safari

**Comment by simpautus** [comment]
> Just a sanity check, if you're always on the same tab, does the `SIGNED_IN` event always get fired?

Hi! No it doesn't. When it happens that it doesn't I visit another tab and come back and then it fires. For this to happen I need to stay on the same route of the app. 

Let's say the route of the OAuth redirect is `api/auth/callback`. It returns from the provider to that route with tokens and such after the hashtag. If it works I get signed in and redirected further as expected. When it doesn't work I'm left in `api/auth/callback#` like that, no credentials in the hash anymore. But if I then visit another tab and come back it proceeds with the sign in like there was nothing wrong.

**Comment by kangmingtay** [comment]
@simpautus is there a consistent way to reproduce this? 

> When it doesn't work I'm left in api/auth/callback# like that, no credentials in the hash anymore. But if I then visit another tab and come back it proceeds with the sign in like there was nothing wrong.

This sounds like it doesn't happen all the time but i haven't been able to reproduce this. Also, when this happens, did you manage to check if the query fragments are parsed and saved into local storage?

**Comment by simpautus** [comment]
> Also, when this happens, did you manage to check if the query fragments are parsed and saved into local storage?

Yes, credentials get stored into local storage. They're stored when the redirect lands to the callback route even if it gets stuck there. Then after cycling another tab the `SIGNED_IN` event gets fired and the process proceeds normally.

I deployed the demo repo to Railway [here](https://supabase-oauth.up.railway.app/)

After trying the production version out (so far) successfully in Safari I'm starting to think the issue has something to do with my Chrome browser and/or it's extensions. I'll see if I find something there while troubleshooting.

**Comment by simpautus** [comment]
Here's some results of testing the demo repo and real project with different browsers. I disabled all the extensions from Chrome. The apps have the same login logic but the other project has more meat on the bones like themes, i18n and such. In the demo app there's practically only the OAuth login.

Demo repo app:
- Desktop Chrome 4/10 failed (This was the result of continuous testing but at times it was very difficult to succeed at all)
- Desktop Safari 0/10 failed (Still failed a couple of times before but rarely)
- Desktop Firefox 0/5 failed
- iPhone Chrome (exceeded the github rate limit and have to wait before finishing the tests)
- iPhone Safari (exceeded the github rate limit and have to wait before finishing the tests)

Beefier project:
- Desktop Chrome 5/5 failed
- Desktop Safari 4/5 failed
- Desktop Firefox 5/5 failed
- iPhone Chrome 5/5 failed
- iPhone Safari 5/5 failed

Everytime the process failed, it failed the same way - "got stuck" at the callback route. And everytime when failed it continued to a successful login after visiting another tab.

Any ideas what to do?

**Comment by simpautus** [comment]
I set up a new repo with more meat on the bones. It's a Remix app with themes, i18n, TailwindCSS and Supabase OAuth identical to the previous demo repo. You can find the new one [here](https://github.com/simpautus/remix-supa).

The repo is deployed to Railway and exposed [here](https://remix-supa.up.railway.app).

I user tested the OAuth by alternating FB and Github login total 6 times per client. The live version failed every callback (Mac: Chrome/Safari/Firefox, iPhone: Chrome/Safari) and recovered each time after visiting another tab. Running locally in development mode and using Chrome the login succeeded every time.

<img width="771" alt="Screenshot 2022-10-30 at 9 59 15" src="https://user-images.githubusercontent.com/34986309/198868808-9cdb7b7b-b859-4eb7-973d-d9701ef6a1da.png">

Could you try how this one works for you? To me so far every live request gets stuck in `/api/auth/callback#` and continues after visiting another tab.

**Comment by simpautus** [comment]
> The live version failed every callback

Right after this comment the live version succeeded with one Facebook login but failing again after that.

**Comment by hf** [comment]
Hey @simpautus,

I'm trying to figure out your issue and want to cover all bases.

If you register a callback with `onAuthStateChange` inside `useEffect` you need to realize that `useEffect` _does not run synchronously._ It runs in some future processing cycle. However, when an access and refresh tokens are made available through the URL, the constructor of `supabase.auth` runs very early on. Sometimes it finishes too quick, and fires a callback before your `useEffect` code got a chance to run. In this case, I would suggest moving the callback outside of `useEffect` so that you are able to always catch the `SIGNED_IN` event.

Let me know if this helps.

**Comment by simpautus** [comment]
> I would suggest moving the callback outside of `useEffect` so that you are able to always catch the `SIGNED_IN` event.

Hi and thank you!

Moving the subscription outside the useEffect (to the root component of the Remix application)  seems to help. It's just that now it runs on every render and I can't use the useEffect return to cleanup and unsubscribe. Any opinion what would be the best place for the onAuthStateChange if useEffect is too late?

**Comment by hf** [comment]
> Moving the subscription outside the useEffect (to the root component of the Remix application) seems to help. It's just that now it runs on every render and I can't use the useEffect return to cleanup and unsubscribe. Any opinion what would be the best place for the onAuthStateChange if useEffect is too late?

Actually you should be using it within `useEffect` but be aware that when you do that, there's a high chance that the very first event generated by the library has already been dispatched.

It's best if you don't rely on the event _alone_ to fetch the initial user state. I would register the callback and immediately call [`getSession`](https://supabase.github.io/gotrue-js/v2/classes/GoTrueClient.html#getSession) to inspect the initial state of auth when the component first renders.

We may reconsider this API in a future major revision as it's a common source of confusion.

I'll close the issue for now, please do continue the discussion or re-open if you feel it has not been sufficiently addressed.
