### ISSUE TITLE
Phone auth with textlocal provider not working

### ISSUE THREAD

**Issue by farhan711** [supabase/gotrue-js#519]
# Bug report
While enabling auth with the phone using Textlocal, the sender name cannot update.
While sending OTP to the number it throws an error of the sender name. 

below is the error message

```
{
    "code": 400,
    "msg": "Error sending sms: missing Textlocal sender"
}
```

NOTE: I did all the required setup on textlocal to get the message working, When I test with the API of textlocal directly then its works fine. But not with supabase send OTP.

## Describe the bug
Bug is when auth using phone using textlocal.

## To Reproduce
1. Setup auth with Phone method using textlocal provider 
2. Complete the setup at Textlocal
3. Send phone OTP using phone method
4. The Error will occur

## Expected behavior
While sending the OTP it should be sent directly. Without any error.

While sending the Phone Auth, The OTP should be sent. Even there's a sender name configured at supabase setting. Yet it says 
`missing Textlocal sender` Must be issue with config would not be getting read?

## Screenshots
![Screenshot 2022-10-25 at 10 59 25 AM](https://user-images.githubusercontent.com/13505895/197690509-e6e15e75-b8df-4135-9fcb-6726280d0818.png)

## System information
 OS: macOS
 Version of supabase-js: 2.0.4
 Version of Node.js: 16.17.1

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by kangmingtay** [comment]
Hi @farhan711, can you please contact us at [support](https://app.supabase.com/support/new) so we can investigate the issue with your project?
