### ISSUE TITLE
signOut - improve response if user has been deleted

### ISSUE THREAD

**Issue by MatthewPosgate** [supabase/gotrue-js#520]
At the moment, if you delete a user on the server, and the user then tries to sign out with supabaseClient.auth.signOut(), we get 
AuthApiError: Internal server error.

Can we change this to say something along the lines of 'user does not exist'?
Then if I detect that error I can sign them out anyway in my app

**Comment by cinan** [comment]
I noticed when calling `supabase.auth.signOut()` and server throws an error (500), session won't get cleared. That means I can't log out a user from users' browser.

**Comment by hf** [comment]
Fixed in https://github.com/supabase/gotrue/pull/783. Let us know if you're still facing the same issue.
