### ISSUE TITLE
Calling `getUser(jwt)` with a client auth'd with a service role key, sets the jwt as the client's `auth` headers.

### ISSUE THREAD

**Issue by j4w8n** [supabase/gotrue-js#531]
This is a slightly different issue, but related to auth having its own headers...

.getUser(jwt) if called while using service_role sets the authentication header in auth to the User JWT.
The supabase client header still stays service_role, but if you make further admin auth calls after doing a .getUser call they will be rejected with 401.

If this is desired behavior for getUser(jwt), then this should be documented as users are running into this server side.

This image is of auth's headers in the supabase "object".

![getUser](https://user-images.githubusercontent.com/54564956/199859400-7a18244d-52e3-445f-af16-b1aeceaa2a26.JPG)

_Originally posted by @GaryAustin1 in https://github.com/supabase/gotrue-js/issues/524#issuecomment-1302818732_

I was able to reproduce this. All of the non-auth headers remain the same, but the auth headers get changed to the passed-in jwt. I haven't been able to figure out why it's doing this though.

One workaround is to import a non-service-role supabase client to call `getUser(jwt)`.
      
![jwts](https://user-images.githubusercontent.com/25783093/200324219-35cc4027-49cd-4c56-8d5b-5e755b6e4c37.png)

**Comment by hf** [comment]
Until we get to looking at this, please create a new client each time you call an API on the backend.

**Comment by bobmolgui** [comment]
Do we know until when this will be fixed(ETA)? By "create a new client  each time .." you mean 
`createClient(supabaseUrl, supabaseServiceRole);` right?

**Comment by j4w8n** [comment]
It looks like https://github.com/supabase/gotrue-js/pull/541 also resolved this issue. @GaryAustin1 @hf and/or @kangmingtay can you double-check me?

**Comment by bobmolgui** [comment]
Thx for feedback, at least for me the same issue is still there. Also with updating

**Comment by j4w8n** [comment]
> Thx for feedback, at least for me the same issue is still there. Also with updating

Just to clarify, you installed gotrue-js 2.3.1?

**Comment by bobmolgui** [comment]
I use: "@supabase/supabase-js": "^2.1.0"

**Comment by GaryAustin1** [comment]
@bobmolgui 2.1.0 has not changed yet to incorporate the new gotrue-js 2.3.1.
You would need to install the gotrue-js version separately or wait for a bump in supabase-js.

**Comment by bobmolgui** [comment]
@GaryAustin1 & @j4w8n thanks a lot with gotrue-js 2.3.1 it works! :)

**Comment by j4w8n** [comment]
Closing as resolved, per #541
