### ISSUE TITLE
Randomly, TOKEN_REFRESHED and SIGNED_IN events both fire

### ISSUE THREAD

**Issue by j4w8n** [supabase/gotrue-js#535]
# Bug report

Low priority. Just documenting.

## Describe the bug

Sometimes a SIGNED_IN event is fired along with the TOKEN_REFRESHED event. Both access_token outputs have the same `expires_at` and token value.

This happens randomly - or seems to. During one test, after initial sign in, it didn't happen until the 5th token refresh. Then the 2nd and 3rd after that. But on a second test, it happened on the 2nd token refresh after initial sign in.

## To Reproduce

Currently unsure if this is reproducible. But I have a basic client setup, with no explicit options. In `onAuthStateChange`, log the `event` and `session`. Then login and observe the browser console.

## Expected behavior

Only see TOKEN_REFRESHED event when a token is refreshed.

## Screenshots

![Screen Shot 2022-11-11 at 1 24 29 PM](https://user-images.githubusercontent.com/25783093/201408230-46577e1e-eab8-49c5-ba98-31d73ffac287.png)

## System information

- OS: macOS
- Browser Firefox
- Version of supabase-js: 2.0.5
- Version of Node.js: 16.15.0

## Additional context

Github OAuth, SvelteKit. No auth helpers.

**Comment by j4w8n** [comment]
I just had a case where the `SIGNED_IN` event did the same thing. Although I was doing something else, so I'm not sure if they came in at the same time, or if the 2nd was a few seconds later.

![Screen Shot 2022-11-16 at 9 08 50 AM](https://user-images.githubusercontent.com/25783093/202202407-31d99cd7-1e48-4d88-806f-c40d78705c6d.png)

**Comment by hf** [comment]
Hey I believe this "problem" should be getting addressed with #564.

**Comment by j4w8n** [comment]
This may have also been because my laptop was connected to wired and wireless networks at the same time. I haven't gone back and verified whether that might have been the cause.

**Comment by hf** [comment]
> This may have also been because my laptop was connected to wired and wireless networks at the same time. I haven't gone back and verified whether that might have been the cause.

I don't think that would have any effect. The browser doesn't really know about how many networks you're connected to.

**Comment by kangmingtay** [comment]
i think we can close this one, we only fire either the `TOKEN_REFRESHED` event in `_callRefreshToken()` or the `SIGNED_IN` event: https://github.com/supabase/gotrue-js/blob/7d75c08125cfe7f3904d1b4d68fc868c94510992/src/GoTrueClient.ts#L1064-L1080
