### ISSUE TITLE
AuthApiError: Database error saving new user     

### ISSUE THREAD

**Issue by HeetaeChae** [supabase/gotrue-js#553]
When registering as a member by email method, the following error occurs.

POST https://angyjvlvvkltvpsqkfrx.supabase.co/auth/v1/signup 500
AuthApiError: Database error saving new user     

this is my code.

`
async (values) => {
    const { email, password } = values;
    try {
      const { data, error } = await supabase.auth.signUp({
        email,
        password,
      });
      if (error) throw error;
      if (data) {
        console.log(data);
      }
    } catch (error) {
      console.log(error);
    }
  }
`

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js: 2.1.1
- Version of Node.js: 18.12.1

**Comment by hf** [comment]
Hey please [open a support ticket](https://app.supabase.com/support/new) so we can investigate the issue of your project.

Issues are meant for bugs or feature requests of the client library.
