### ISSUE TITLE
VerifyOTP for type "email_change" returns "user not found" in Safari

### ISSUE THREAD

**Issue by yndotdev** [supabase/gotrue-js#561]
# Bug report

VerifyOTP for type "email_change" returns "user not found" in Safari

## Describe the bug

When running the function, it returns "user not found" in Safari. Works perfectly fine in Chrome.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Try to run this in Safari...

```
 const { data, error } = await locals.sb.auth.verifyOtp({
      email: (await locals.sb.auth.getUser()).data.user?.email!,
      token,
      type: 'email_change'
    });
```

## Expected behavior

I expect it to return data, not an error.

## System information

- OS: macOS
- Browser:  Safari
- Version of supabase-js: ^2.1.0
- Version of Node.js: 18.9.0

## Additional context

I'm using SvelteKit + the Supabase Auth Helper (^0.8.6)

Seems to be quite similar to this: [https://github.com/supabase/gotrue-js/issues/292](https://github.com/supabase/gotrue-js/issues/292)

**Comment by hf** [comment]
Left a new comment on the #292: https://github.com/supabase/gotrue-js/issues/292#issuecomment-1367942132

Can you also please give us a reproducible example otherwise we're not able to help out much. There's nothing Safari specific that the library is doing.
