### ISSUE TITLE
How to login as admin

### ISSUE THREAD

**Issue by dkyeremeh** [supabase/gotrue-js#565]
Sorry if this question has been asked, but I can't seem to find an answer anywhere. 

I am trying to setup `supabase/gotrue` as an independent auth provider without using the other supabase services.
However, I can't seem to find a way to make requests as an admin.

Attempting to do anything under the `auth.admin` namespace triggers an error that the request needs a token.
I understand that I can set the token in the header while initiating the client, but I can't seem to find any documentation on how to set or generate the admin token in the first place.

**Comment by j4w8n** [comment]
The admin token you want to use is the supabase service role key.

**Comment by j4w8n** [comment]
Also, be mindful of the auth options, as that link example shows. persistSession needs to be false if you're gonna call methods like `getSession` on the server-side. This is true even for the non-admin client.

**Comment by dkyeremeh** [comment]
@j4w8n Thanks for the response.





My concern is how I'm going to generate the service role key

**Comment by j4w8n** [comment]
Ah, self hosted. I didn't catch that.
