### ISSUE TITLE
Option to prevent redirect in 'signInWithOAuth'

### ISSUE THREAD

**Issue by martinboksa** [supabase/gotrue-js#584]
# Feature request
It would be nice to add an option to disable automatic redirect in `signInWithOAuth`. 

## Is your feature request related to a problem? Please describe.
We use electron and now it redirects user to same window. It's much better to open a new default browser (because user has stored usernames/password in his browser)

## Describe the solution you'd like
Add `if` :)
https://github.com/supabase/gotrue-js/blob/b7b66fef9e5dc8db755a589ed5a404720832f666/src/GoTrueClient.ts#L944

**Comment by j4w8n** [comment]
It's coming soon.

https://github.com/supabase/gotrue-js/pull/575
