### ISSUE TITLE
getUserByEmail

### ISSUE THREAD

**Issue by Samsonov0** [supabase/gotrue-js#592]
# Feature request

## Is your feature request related to a problem? Please describe.

We have getUserById but needed also getUserByEmail("email")

## Describe the solution you'd like

I need getting users record on email field

## Describe alternatives you've considered

Add email field in Profile table, but this bad decision

**Comment by j4w8n** [comment]
Hey @Samsonov0 what's your use-case here? I'm not part of the team, but they usually try to get some clarification on why someone wants to add new functionality like this.
