### ISSUE TITLE
Authentication causing page reload

### ISSUE THREAD

**Issue by Benjamin-Dobell** [supabase/gotrue-js#593]
# Bug report

## Describe the bug

https://github.com/supabase/gotrue-js/pull/574 introduced a redirect instead of simply removing the sensitive hash from the browser URL & history.

## To Reproduce

1. In Chrome (or another browser), enable network log persistence.
2. Login to any site using the latest gotrue-js (by any auth strategy).
3. Notice that in the network tab the callback page is reloaded. In Chrome, the initiator column will point to the culprit line of code within gotrue-js.

## Expected behavior

No redirect.

## Screenshots

![image](https://user-images.githubusercontent.com/482276/214823775-047cef01-dab8-4b91-8cd2-7e502297eba4.png)

![image](https://user-images.githubusercontent.com/482276/214823931-17dcb8ee-dade-47aa-902c-746ab24c080a.png)

## System information

- OS: macOS
- Browser (if applies) Screenshots from Chrome. Observed in Firefox also.
- Version of supabase-js: 2.4.1

**Comment by Benjamin-Dobell** [comment]
Although `history.replaceState()` is the correct solution in that that's what should ultimately be called. I don't think supabase should be calling it directly, since consumers may be using their own router e.g. react-router will the history messed with without its knowledge.

There's two options:

1. Roll back the fix and leave this to consumers i.e. Consumers callbacks should already be replacing the URL in the history anyway. I guess just document that.
2. Alternatively, we could pass a navigateTo function into Supabase then through to GoTrue. However, that seems pretty heavy handed.

**Comment by j4w8n** [comment]
This change was reverted. Should be working as before, in 2.5.0

**Comment by hf** [comment]
> Although history.replaceState() is the correct solution in that that's what should ultimately be called. I don't think supabase should be calling it directly, since consumers may be using their own router e.g. react-router will not like the history being messed with without its knowledge.

This is the exact reason why I didn't use `replaceState` for this... anyway I don't think this makes sense to be fixed any more as we are working towards PKCE support in which case going "back" won't cause the same side effect it does today.

I'll close this as it was fixed with #596.
