### ISSUE TITLE
Can't pass additional data to backend with sign in function

### ISSUE THREAD

**Issue by Anulo2** [supabase/gotrue-js#594]
# Bug report

## Description

It looks like the sign in with password function does not pass the metadata to the backend.

## To Reproduce

on the client call:
`
 supabase.auth.signInWithPassword({
    email,
    password,
    options:{
        data:{
            my_data
        }
    }
})
`

and on the backend try to access the metadata in a function:
`
begin
    RAISE EXCEPTION 'Debug %', new;
end;
`

## Expected behavior

On the backend I should be able to access the raw_user_metadata with my data

## Additional info

Everything started with this thread on discord:
https://discord.com/channels/839993398554656828/1067713541366353941

**Comment by J0** [comment]
Hey @Anulo2,

Thanks for flagging this - this is actually a bug on our end - passing metadata isn't supported on email/password sign-ins. We only support passing through metadata on Sign Ups.

We'll be filing a PR to amend this. Sorry for the confusion caused
