### ISSUE TITLE
chore: Add "Remember me" to the example

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue-js#6]
# Chore

## Describe the chore

- Add `Remember Me` functionality to the example: https://github.com/supabase/gotrue-js/blob/6d2ef91f738b8ee5339e4b3724f432acc1665ad2/example/src/App.js#L33

## Additional context

We should give a basic example of how to use enable/disable storing of sessions

**Comment by niits** [comment]
@kiwicopple Awesome project. Would you mind if I pull this up for Hacktoberfest?

**Comment by kiwicopple** [comment]
Of course! 

You're early for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) though:

![image](https://user-images.githubusercontent.com/10214025/94216445-ec2b2980-ff11-11ea-8663-758b5e941757.png)

Unfortunately we don't make the rules here, so if you want to earn the free t-shirt from DO you might want to wait until October 1. We are also trying to organize our swag. If we can manage the logistics, we will get you some swag even if it's outside of October.

**Comment by niits** [comment]
@kiwicopple Thank you :smile:

**Comment by niits** [comment]
@kiwicopple I has some questions. When I run `npm install`, npm has created new package-lock.jon. As I have read on StackOverflow, package.json can override package-lock.json whenever a newer version is found for a dependency in package.json. So, would you mind if I commit  package.json change?

**Comment by kiwicopple** [comment]
Yep! you can commit both the `package.json` changes and the `package-lock.json` - that's fine :)
