### ISSUE TITLE
autoRefreshToken doesn't work

### ISSUE THREAD

**Issue by nuurcodes** [supabase/gotrue-js#620]

**Comment by uze** [comment]
> Hey everyone, we're investigating this issue and it would be great if yall can provide the supabase-js / gotrue-js versions that you experience this error on.

Version: ` "@supabase/supabase-js": "^2.1.3"`

**Comment by optinforce** [comment]
Experiencing this with these versions:

supabase-js: 2.10.0
gotrue-js: 2.13.0

**Comment by ivorpad** [comment]
Experiencing this with these versions:

supabase-js: 2.11.0
supabase/auth-helpers-remix: 0.1.5

**Comment by shimi-chans-tree** [comment]
When I left the app running on the iOS simulator for a while and reloaded Metro, I encountered the error 
``` Invalid Refresh Token: Already Used ```

 @supabase/supabase-js": "^2.22.0"
expo": "^48.0.10" (bare workflow)

**Comment by huksley** [comment]
I am also getting "Invalid Refresh Token: Already Used"

I don't see previous invocations which might have used the token.

And btw, isn't refresh token supposed to be constant and used only to reissue access tokens as needed?

**Comment by lewisd1996** [comment]
Also getting this in my RN project, constantly being signed out in a matter of minutes, anything we can do here?

**Comment by vbylen** [comment]
something that may help here is setting the `jwt_expiry` to the maximum in `config.toml`

```toml
jwt_expiry = 604800
```

**Comment by kangmingtay** [comment]
Hey everyone, i'm attempt to reproduce this issue using the expo user management example (https://github.com/supabase/supabase/tree/master/examples/user-management/expo-user-management) but i haven't been able to reproduce this. It would be great if someone has a repo to share or can outline the reproducible steps.

I'm running on `"@supabase/supabase-js": "^2.24.0"`, and this is how i'm initialising the supabase client:

```js
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: ExpoSecureStoreAdapter as any,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});
```

**Comment by claycoleman** [comment]
> Yeah this seems to still be happening, at least when running Supabase locally for development, working on a React Native app using Expo ->
> 
> ```
> LOG  SB Res --> {"data": {"session": null}, "error": [AuthApiError: Invalid Refresh Token]}
> ```
> 
> Trying to figure out how long before it expires, and `supabase.auth.refreshToken()` also throws an error once it has expired.

This response describes the issue pretty similarly to me – I'm running supabase locally using `npx supabase start`, my client is initialized just like yours is @kangmingtay but with local supabase url and anon key. 

I have a `supabase.auth.onAuthStateChange` which runs on app init and whenever the auth state changes. typically the repro case is logging in then waiting until the token expires, usually this happens while the app simulator / the app is in the background on my mac. in this case, my `onAuthStateChange` fires and receives a session with a jwt and refresh token. This triggers a fetch from my `profiles` table, but that request fails with `{"code": "PGRST301", "details": null, "hint": null, "message": "JWT expired"}`. subsequent reloads of the app also fire `onAuthStateChange` with what looks like a valid session but the same error occurs when trying to fetch data from supabase. my guess is that this session is coming from the secure store.

cc @lewisd1996 @b2m9 @edgarsilva @uze for your repro cases?

**Comment by claycoleman** [comment]
fwiw, the refresh token that is the session with the expired jwt is still valid according to my local db. i looked this up using the `auth.refresh_tokens` table. so my issue is slightly different from some of the above responses where even calling `refreshToken()` errors out. my client is being inited with `autoRefreshToken: true` though, so also confused why supabase isn't refreshing it automatically! supabase version `2.25.0`

**Comment by swyxio** [comment]
getting `AuthApiError: Invalid Refresh Token: Refresh Token Not Found` right now as well

**Comment by MilesV64** [comment]
We're also getting the Refresh Token: Refresh Token Not Found issue every time we try to refresh.

**Comment by JeremyMees** [comment]
The issue was resolved after I updated the Supabase Nuxt package to **^0.3.1**. Additionally, I had to clear my existing Supabase cookies, which allowed the functionality to work as intended.

**Comment by lorsk** [comment]
Only way I am able to resolve this issue is uninstalling the app and installing it again. This occurs in local development and not in production. 

Using React native with @supabase/supabase-js: ^2.37.0

**Comment by sebastiangrebe** [comment]
Same happening for me.

Here my supabase client setup:

```
import { Database } from '../../../../supabase/types'
import { createClient } from '@supabase/supabase-js'
import * as SecureStore from 'expo-secure-store'
import AsyncStorage from "@react-native-async-storage/async-storage";

import * as aesjs from 'aes-js';
import 'react-native-get-random-values';

import { replaceLocalhost } from '../getLocalhost.native'

if (!process.env.EXPO_PUBLIC_SUPABASE_URL) {
  throw new Error(
    `EXPO_PUBLIC_SUPABASE_URL is not set. Please update the root .env.local and restart the server.`
  )
}

if (!process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY) {
  throw new Error(
    `EXPO_PUBLIC_SUPABASE_ANON_KEY is not set. Please update the root .env.local and restart the server.`
  )
}

const supabaseUrl = replaceLocalhost(process.env.EXPO_PUBLIC_SUPABASE_URL)

// As Expo's SecureStore does not support values larger than 2048
// bytes, an AES-256 key is generated and stored in SecureStore, while
// it is used to encrypt/decrypt values stored in AsyncStorage.
class LargeSecureStore {
  private async _encrypt(key: string, value: string) {
    const encryptionKey = crypto.getRandomValues(new Uint8Array(256 / 8));

    const cipher = new aesjs.ModeOfOperation.ctr(encryptionKey, new aesjs.Counter(1));
    const encryptedBytes = cipher.encrypt(aesjs.utils.utf8.toBytes(value));

    await SecureStore.setItemAsync(key, aesjs.utils.hex.fromBytes(encryptionKey));

    return aesjs.utils.hex.fromBytes(encryptedBytes);
  }

  private async _decrypt(key: string, value: string) {
    const encryptionKeyHex = await SecureStore.getItemAsync(key);
    if (!encryptionKeyHex) {
      return encryptionKeyHex;
    }

    const cipher = new aesjs.ModeOfOperation.ctr(aesjs.utils.hex.toBytes(encryptionKeyHex), new aesjs.Counter(1));
    const decryptedBytes = cipher.decrypt(aesjs.utils.hex.toBytes(value));

    return aesjs.utils.utf8.fromBytes(decryptedBytes);
  }

  async getItem(key: string) {
    const encrypted = await AsyncStorage.getItem(key);
    if (!encrypted) { return encrypted; }

    return await this._decrypt(key, encrypted);
  }

  async removeItem(key: string) {
    await AsyncStorage.removeItem(key);
    await SecureStore.deleteItemAsync(key);
  }

  async setItem(key: string, value: string) {
    const encrypted = await this._encrypt(key, value);

    await AsyncStorage.setItem(key, encrypted);
  }
}

export const supabase = createClient<Database>(
  supabaseUrl,
  process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY,
  {
    auth: {
      storage: new LargeSecureStore(),
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false,
    },
  }
)
```

Plus this one for handling foreground / background handling but even with or without no difference:
```
AppState.addEventListener('change', (state) => {
  if (state === 'active') {
    supabase.auth.startAutoRefresh()
  } else {
    supabase.auth.stopAutoRefresh()
  }
})
```

Majorly I dont see any events or tries of refreshing the token.

Moreover default 1 hour of course stays longer logged in but setting 50, 60 or 120 seconds mostly logs me out after good 20 seconds.
Can someone official have a look into this as it seems to be a big UX blocker?

**Comment by xl0** [comment]
I'm getting the same thing. To reproduce more easily, I set the token to 10 seconds.
I'm running with supabase/ssr server-only with SvelteKit, a single supabase client in locals that is used throughout the request:
```
export const handle: Handle = async ({ event, resolve }) => {
	event.locals.supabase = createServerClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
		auth: { debug: true },
		cookies: {
			get: (key) => {
				const value = event.cookies.get(key);
				// debug('cookies get', { key, value });
				return value;
			},
			set: (key, value, options) => {
				// debug('cookies set', { key, value, options });
				event.cookies.set(key, value, { ...options, path: options.path ?? '/' });
			},
			remove: (key, options) => {
				// debug('cookies remove', { key, options });
				event.cookies.delete(key, { ...options, path: options.path ?? '/' });
			}
		}
	});


	event.locals.safeGetSession = async () => {
		const {
			data: { session }
		} = await event.locals.supabase.auth.getSession();
		if (!session) {
			debug('No session found');
			return { session: null, user: null };
		}

		const {
			data: { user },
			error
		} = await event.locals.supabase.auth.getUser();
		if (error) {
			debug('Error getting user: ', error);
			// JWT validation has failed
			return { session: null, user: null };
		}

		return { session, user };
	};

	const { session, user } = await event.locals.safeGetSession();
	event.locals.session = session ?? undefined;
	event.locals.user = user ?? undefined;

        [ ... ]
```

Here is the traceback:
```
  app:hooks:supabase Error getting user: AuthApiError: invalid JWT: unable to parse or verify signature, token has invalid claims: token is expired
    at handleError (/home/xl0/work/projects/llms/assistant/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:63:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (/home/xl0/work/projects/llms/assistant/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:108:9)
    at async _request (/home/xl0/work/projects/llms/assistant/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:89:18)
    at async /home/xl0/work/projects/llms/assistant/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:874:24
    at async SupabaseAuthClient._useSession (/home/xl0/work/projects/llms/assistant/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:774:20)
    at async SupabaseAuthClient._getUser (/home/xl0/work/projects/llms/assistant/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:864:20)
    at async /home/xl0/work/projects/llms/assistant/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:851:20 {
  __isAuthError: true,
  status: 403,
  code: 'bad_jwt'
} +8m
```

I turned on auth: {debug: true}, will see if I can catch another one.

**Comment by xl0** [comment]
Ok, I think I know what's going on, at least in my case. There is a race condition between the check for the session expiration and when the session is used to get the user:
node_modules/@supabase/auth-js/src/GoTrueClient.ts:
```
      const hasExpired = currentSession.expires_at
        ? currentSession.expires_at <= Date.now() / 1000
        : false

      this._debug(
        '#__loadSession()',
        `session has${hasExpired ? '' : ' not'} expired`,
        'expires_at',
        currentSession.expires_at
      )

      if (!hasExpired) {
              [ return the session ]
      [ refresh the session ]
```

If the session is expiring in the new milliseconds, this causes the exception. I think an easy workaround would be to add an arbitrary or configurable offset to the session expiration check and refresh a session that expires very soon.

@kiwicopple @awalias

**Comment by walmon** [comment]
This is still happening with `@supabase/supabase-js: 2.46.1`

Exactly the same, if the user doesn't use the app for more than 3600s then API returns 400 "Invalid Refresh Token: Refresh Token Not Found"

It basically looks like there's no refresh token anywhere.
