### ISSUE TITLE
Losing provider_token and provider_refresh_token - Azure

### ISSUE THREAD

**Issue by chadsmith12** [supabase/gotrue-js#622]
# Bug report

## Describe the bug

This is using Azure as the Authentication Provider. After successfully setting up Azure as a provider and creating a test application and successfully authenticating with Azure I am able to retrieve my session and see the `provider_token` and also `provider_refresh_token`. After about 1 hour both the `provider_token` AND `provider_refresh_token` disappear for the users session and they are no longer able to retrieved. They are not set to `null` so my thought is they are `undefined` and that is why they don't show up in the session returned for the user. The user is still logged in and successfully able to retrieve the users session, the `provider_token` and `provider_refresh_token` just no longer appear and it becomes impossible to retrieve these and preform further API Requests to Azure on behalf of the user.

My thought is that maybe the token that Azure sends back, that is stored in `provider_token`, is expiring which is also why it just disappears. Though I'm not entirely sure if gotrue-js is even checking for expired `provider_tokens` and removing them from the session? My thought would be even if it was expired I should still able to use the `provider_refresh_token` that I am able to retrieve to attempt to get another one on my own. Below is an example:

```js
supabase.auth.signInWithOAuth({
    provider: 'azure',
    options: {
      scopes: 'email, User.Read, offline_access' // including offline_access to retrieve refresh_token
    }
  })
```

## To Reproduce

* Setup Azure as an Authentication Provider
* Successfully authenticate using Azure
* Session returns correct information `provider_token` and `provider_refresh_token`
* Wait about an hour, and you will see session no longer has `provider_token` and `provider_refresh_token` inside of it. It only includes: `access_token`, `expires_at`, `expires_in`, `refresh_token`, `token_type`, and the `user` object.

## Expected behavior

I would believe that I should still be able to at least access the `provider_refresh_token` so that way I keep trying to authenticate  with the Microsoft API on behalf of the user. 

If this is expected behavior because the token might be expiring, then should I storing my `provider_refresh_token` on my own since there doesn't seem to be a way to ever get it back?

**Comment by kangmingtay** [comment]
Hey @chadsmith12, this happens because when the current session is refreshed, gotrue-js clears out the old session stored in local storage and replaces it with the new session. The new session wouldn't have the `provider_token` and `provider_refresh_token` because  we don't persist them in gotrue. You should store the `provider_refresh_token` when the user logs in so that you can continue to interact with the OAuth provider's API even if the existing session is refreshed.

**Comment by chadsmith12** [comment]
@kangmingtay I appreciate the response and the knowledge of how it works. That is what I was starting to think was going on and that is what I was starting to implement anyway. Thanks again for the knowledge!  I can close this as I believe that answers everything.
