### ISSUE TITLE
redirectTo is not used in GoTrueApi

### ISSUE THREAD

**Issue by laurentS** [supabase/gotrue-js#63]
# Bug report

## Describe the bug

If I call `supabase.auth.signIn({email}, {redirectTo: "someurl"})` the `redirectTo` argument is passed down to https://github.com/supabase/gotrue-js/blob/6332b080c8a50a7120106288303c043a0abf8334/src/GoTrueApi.ts#L90 but then on https://github.com/supabase/gotrue-js/blob/6332b080c8a50a7120106288303c043a0abf8334/src/GoTrueApi.ts#L94 it's not actually used.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. call `supabase.auth.signIn({email}, {redirectTo: "someurl"})`
2. See that the browser calls `/magiclink` on supabase, but the `redirectTo` parameter is not there.

Note that there is also something weird with the `Referer` header that is not set correctly for me (I'm just seeing the hostname), which means that the auth flow is completely broken: the configured site URL is not used, Referer is wrong and `redirectTo` is lost in the call stack. I'll open a separate issue about the referer.
Edit: I'm trying to figure out where this referer issue is coming from, I seem to only see it on localhost, so it might be related to the dev server (I'm using svelte and sapper) somehow.

## Expected behavior

It should be there, if we want to get it back out on the other end :)

**Comment by kiwicopple** [comment]
Thanks @laurentS 👍 added to the missing routes
