### ISSUE TITLE
v2.16.0 Causing continuous reload of page when logging out

### ISSUE THREAD

**Issue by EliBates** [supabase/gotrue-js#633]
# Bug report
When using v2.16.0 of gotrue we are experiencing issues with logging out of the application. 

Please refer to this issue for the auth-helpers package which I believe is the same issue. [https://github.com/supabase/auth-helpers/issues/477](https://github.com/supabase/auth-helpers/issues/477)

## Describe the bug
Continuous reloading of page when logging out of the application

## To Reproduce

1. Implement the following tutorial from the supabase website. [https://supabase.com/docs/guides/auth/auth-helpers/remix](https://supabase.com/docs/guides/auth/auth-helpers/remix)
2. Attempt to logout

## Expected behavior

Should log out properly and not have a continuous reload of page.

## System information

- OS: macOS
- "@supabase/auth-helpers-remix": "^0.1.5",
- "@supabase/supabase-js": "^2.12.1",
- Version of Node.js: 16.14.0

## Additional context

Adding a module resolution to 2.15.0 makes the issue go away.

**Comment by wayne-o** [comment]
I am seeing this - is there any kind of work-around?

**Comment by wayne-o** [comment]
Although I am also seeing this on logins too - it's making quite the blocker for me

**Comment by EliBates** [comment]
@wayne-o 
If you are using yarn, you can specify this in your package.json to tell it to use an older version. There is a similar format for npm etc..

`  "resolutions": {
    "@supabase/gotrue-js": "2.15.0"
  }`

**Comment by eba8** [comment]
Any chance this is getting fixed soon?

**Comment by silentworks** [comment]
I think solutions to this was mentioned in this PR as it's an app code issue https://github.com/supabase/auth-helpers/pull/486

**Comment by kangmingtay** [comment]
closing this issue since the solution seems to have fixed this - please reopen the issue if it doesn't work for you @eba8 @EliBates @wayne-o
