### ISSUE TITLE
INITIAL_SESSION fires after an OAuth login

### ISSUE THREAD

**Issue by j4w8n** [supabase/gotrue-js#639]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When logging in with OAuth, the `INITIAL_SESSION` event is fired.

## To Reproduce

1. Follow instructions at [this repo](https://github.com/j4w8n/sb-min) to setup the app
2. Click the `OAuth Login` button, authorize if needed, observe the browser console logs

## Expected behavior

Only a `SIGNED_IN` event should fire.

## System information

- OS: Windows
- Browser: I see the same behavior on Firefox and Chrome
- Version of supabase-js: 2.13.1
- Version of Node.js: 18.12.1

## Additional Context

This behavior does not happen when using  `signInWithPassword()`

**Comment by silentworks** [comment]
This behaviour sounds correct as the `INITIAL_SESSION` gets fired when the page first load, an OAuth sign in would bring you to the provider's page and then redirect you back to the origin website after which would trigger an `INITIAL_SESSION` as this would be the user revisiting this page after being redirected away.

**Comment by j4w8n** [comment]
Roger. I think I have programmed around it now. Was trying to make sure things behaved the same way in my app, for OAuth and email/password logins; and the extra event was throwing me off for a bit.
