### ISSUE TITLE
VerifyOtp (6digit) fails with pkce enabled.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/gotrue-js#662]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Testing the new pkce feature on an instance with it enabled.

With no flowType, verifyOtp ({email,6digitoken,type:'magiclink'}) works.

Enabling flowType:'pkce' fails with `"code":401,"msg":"Token has expired or is invalid"`.
I see code verifier in local storage and the magic link comes back as 
`https://ugccccccccccccccbq.supabase.co/auth/v1/verify?token=pkce_2e1exxxxxxxxxx2f1&type=magiclink&redirect_to=http://mytestsite`
I also have a 6 digit Token in the email template with {{.Token}}.

Tried 3 times toggling flowType on and off and consistent fails with flowtype:'pkce' so not a timing or bad token issue.

Note:  I'm not sure how this is supposed to work as there is a pkce token in the URL and not clear if that is required with the flow.  If so the 6 digit token method will not work for magiclink.  

## To Reproduce
Set the tokenFlow:'pkce' option.
Do signInWithOtp with a 6digit token in the template.
Get email with correct looking redirect link but use the 6 digit token.
Use verifyOtp with the 6 digit token.

## Expected behavior
The OTP code should work either with or without pkce enabled even if it is not supposed to support pkce as users may have a variety of log in methods.
At a minimum it should be documented this will break.

## System information
Instance with pkce on.
Supabase 2.20.0

**Comment by GaryAustin1** [comment]
I can confirm on same system the magic link with pkce works with clicking the link in the email.

**Comment by J0** [comment]
Hey @GaryAustin1,

Thanks for flagging this and also for taking the time to test the pkce flows 🙏 We're looking into this and will get back to you with a fix soon

**Comment by GaryAustin1** [comment]
Hey, I'm just helping test and learn enough to answer early dev questions.
So no worries from me as far as my project goes.

**Comment by silentworks** [comment]
@GaryAustin1 can you confirm this is now fixed on your project please? I've tested it on mine and its now working as intended. Sorry for this issue being auto-closed.

**Comment by GaryAustin1** [comment]
It is fixed.

**Comment by kangmingtay** [comment]
@GaryAustin1 thanks for catching this gary!
