### ISSUE TITLE
`inviteUserByEmail` doesn't use the correct type for `options`

### ISSUE THREAD

**Issue by shellscape** [supabase/gotrue-js#668]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

As can be seen below, `inviteUserByEmail` doesn't use the correct typing for the `options` parameter: https://github.com/supabase/gotrue-js/blob/1217825583e26eebe005b83f37bad54deefd4ab1/src/GoTrueAdminApi.ts#L82-L88

The correct, matching type can be found here: https://github.com/supabase/gotrue-js/blob/1217825583e26eebe005b83f37bad54deefd4ab1/src/lib/types.ts#L534-L543

I initially found this discrepency as I was researching how to use an invite link and also inject data into `user_metadata`. The [documentation](https://supabase.com/docs/reference/javascript/auth-admin-inviteuserbyemail) doesn't mention what `data` is used for, so I started source diving and found the apt description of what `data` is used for on the [`GenerateLinkOptions`](https://github.com/supabase/gotrue-js/blob/1217825583e26eebe005b83f37bad54deefd4ab1/src/lib/types.ts#L536) interface. _(Which raises another question of why are the TS types more descriptive than the documentation?)_

## To Reproduce

No need for reproduction, this is a typing error

## Expected behavior

`options` is typed to `GenerateLinkOptions`

## Screenshots

n/a

## System information

- OS: all
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: latest
- Version of Node.js: n/a

**Comment by J0** [comment]
Hey @shellscape,

Thanks for flagging this! You are right that that `GenerateLinkOptions` are structurally similar and have the same properties. However, I'm not sure they perform the same purpose semantically as `generateLink` and `inviteUserByEmail` are two separate functions. Another alternative would be to create a separate `Options` type for user invites but that might not be as helpful unless we have additional `invite` functions which use. As such, I'd personally prefer to keep the function as is.

We'll take note of the feedback around the data property and see if there's any way we can make it clearer as well.

Let me know if there are any concerns/issues that I've missed.

Thanks!

**Comment by shellscape** [comment]
>As such, I'd personally prefer to keep the function as is.

You'd rather have inconsistent typing in a codebase that ships to many thousands of developers? Odd choice, but OK. FWIW that's not something that the community would let us get away with in Rollup.
