### ISSUE TITLE
Invalid parameter value for code_challenge_method: 's256' with PCKE & Google

### ISSUE THREAD

**Issue by imownbey** [supabase/gotrue-js#669]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Trying to use the new pkce auth flow with Google sign in based on the blog post:
https://supabase.com/blog/supabase-auth-sso-pkce#server-side-and-mobile-auth
I get the following error when showing the google login screen:

Invalid parameter value for code_challenge_method: 's256' is not a valid CodeChallengeMethod [Learn more about this error](https://developers.google.com/identity/protocols/oauth2)

Error 400: invalid_request

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by J0** [comment]
Hey @imownbey,

Thanks for the issue report - we've since put in a fix. Could we trouble you to check and see if you're still facing the issue?
