### ISSUE TITLE
add method to delete users

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue-js#69]
on the backend you can:

[`DELETE /admin/users/{user_id}`](https://github.com/supabase/gotrue/blob/8cb3d71a8c3fcbd9fd0e23586f1203d5861a56a5/api/api.go#L157) but the JWT role needs to be `service_role` or `supabase_admin`

perhaps we should add it as a method here

linked: https://github.com/supabase/gotrue/issues/79

**Comment by marcelobarreto** [comment]
Is anyone working at this? Otherwise, you can assign it to me @awalias :call_me_hand:

**Comment by marcelobarreto** [comment]
```js
const { GoTrueClient } = require('./dist/main');

const auth = new GoTrueClient({
  url: 'https://uedcsccyuwzjvimjgprm.supabase.co/auth/v1',
  headers: {
    apikey: 'my_service_role_JWT',
  },
});

async function main() {
  // I've created this .destroyUser
  let { data, user, error } = await auth.destroyUser({ userUID: '1bd282ce-3735-472f-a55f-8745ef79551d' });
  console.log(data, user, error);

  process.exit(0)
};

main();

// null null { message: 'User not allowed', status: 401 }
```

@awalias can you help to see what I'm doing wrong?

**Comment by awalias** [comment]
ah this also needs the backend change mentioned here: supabase/gotrue#79 in order to work

**Comment by awalias** [comment]
this comment: https://github.com/supabase/gotrue/issues/79#issuecomment-808719524

**Comment by awalias** [comment]
oh sorry you're already using the `service_role` 🤔

**Comment by awalias** [comment]
it should be being permitted by this: https://github.com/supabase/gotrue/blob/08c7a29fd40bd40ab337f31710c0345ff2970798/conf/configuration.go#L194

**Comment by awalias** [comment]
oh! can you try:
```
const auth = new GoTrueClient({
  url: 'https://uedcsccyuwzjvimjgprm.supabase.co/auth/v1',
  headers: {
    apikey: 'my_service_role_JWT',
    Authorization: `Bearer ${my_service_role_JWT}` <---- this is required
  },
});
```

**Comment by marcelobarreto** [comment]
Interesting... I decoded my JWT payload:

![image](https://user-images.githubusercontent.com/1276556/117454544-a2310a00-af1c-11eb-825b-eacc739f1f50.png)

:thinking: :thinking: :thinking:

**Comment by marcelobarreto** [comment]
Thanks for the explanation @awalias, I'll try as you suggested :rocket:

**Comment by marcelobarreto** [comment]
Hey @awalias I could reproduce it, and I'm creating the PR for this, I just need to write some specs now :wink: 

`auth.setAuth(token)` did the trick :joy:
