### ISSUE TITLE
Auth.verifyOtp removes the session

### ISSUE THREAD

**Issue by ruskid** [supabase/gotrue-js#696]
## Describe the bug

OTP verification removes the session and logs out the user. I want authenticated users to be able to update their emails. Is there any workaround to this issue?

```
const { error } = await supabase.auth.verifyOtp({
              email,
              token: code,
              type: 'email_change',
            })
            
            ...
            
async verifyOtp(params: VerifyOtpParams): Promise<AuthResponse> {
    try {
      await this._removeSession()
      ...

```
## Expected behavior

`verifyOtp` shouldn't automatically renew the session

**Comment by kangmingtay** [comment]
Hi @ruskid, if `verifyOtp()` returns a successful response, the user should be authenticated. Can you please elaborate on how you're using `verifyOtp()`? 

Are you saying that when the user attempts to change their email, they are getting logged out if they enter the wrong verification code?
