### ISSUE TITLE
Can’t update a users phone number more than once

### ISSUE THREAD

**Issue by nuurcodes** [supabase/gotrue-js#704]
Hey,

Here are the steps to reproduce the issue:
1. Create a user with email and password
2. Call auth.updateUser to update the users phone number 
3. Do not verify the OTP
4. Repeat step 2, an error will be thrown (duplicate key value violates unique constraint "identities_pkey)

A user might of entered his phone number incorrectly the first time, it would be good to allow them to update it again otherwise they will be stuck with a number that they cannot verify.

Note: Should a row in the identities table only be added once the phone number change is verified via OTP code? Seems that it would solve the issue.

**Comment by bombillazo** [comment]
Also interested, commenting to get notified.

**Comment by kangmingtay** [comment]
hi @nuurcodes and @bombillazo, we've fixed this issue in https://github.com/supabase/gotrue/pull/1141 and the fix has already been deployed to your projects.

**Comment by Cali93** [comment]
@kangmingtay I'm facing a very similar issue but when the email is empty. Any chance you could apply the same logic for emails ?
Here's our use case:
1. User signs up with his ethereum address (custom integration that creates an identity, the user and issues access_token etc)
2. User adds his email address to receive email notifications, makes a mistake on the email provided or change email confirmation link expires. He tries to update the email again and gets `duplicate key value violates unique constraint "identities_pkey"`
