### ISSUE TITLE
Bug:  logging out of one session removes all auth.refresh_tokens from all sessions

### ISSUE THREAD

**Issue by burggraf** [supabase/gotrue-js#75]
# Bug report

## Describe the bug

- If I log into my app, I see a record in auth.refresh_tokens.
- If I log into my app again in a new (incognito) browser window, I now see two records in auth.refresh_tokens.
- If I log out of ONE of the browser windows, both auth.refresh_tokens records are removed, but one of the sessions is still logged in.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Log into your app from multiple locations using the same email address and password (multiple incognito browser windows works for this)
2. Look at the auth.refresh_tokens entries table for the given user.  There should be one entry per login.
3. Now logout one of the sessions
4. Look at auth.refresh_tokens entries again -- there should now be none.
5. The remaining logged-on sessions still work fine

## Expected behavior

I believe (and I may be wrong about this) that there should be auth.refresh_tokens records for each logged-in user instance.

## System information

Tested using an Angular Ionic PWA on MacOS
- OS: MacOS
- Browser: Chrome
- Version of supabase-js: 1.9.0
- Version of Node.js: 14.16.0

**Comment by burggraf** [comment]
If this bug is resolved, you could get real-time analytics about who is logged in at the current moment, and how many times each user is logged in (with multiple browsers, devices, etc.)

**Comment by kiwicopple** [comment]
Thanks @burggraf 

> I now see two records in auth.refresh_tokens

Can you clarify where you see these? In your database or in your localstorage

> If I log out of ONE of the browser windows, both auth.refresh_tokens records are removed

This sounds like a bug (although perhaps it was engineered this way by Netlify for security). If i have 2 windows open on GitHub (firefox and chrome), and I log out of one of them (firefox), my chrome session should still be valid.

**Comment by burggraf** [comment]
I see the records in the database by doing this:
```select * from auth.refresh_tokens;```

I can test this, but I'm pretty sure if I log in via an iPhone app, or on an iPhone using a PWA and also on my desktop, then log out, both tokens will be deleted.

**Comment by burggraf** [comment]
If you have a better way to query for "logged on users", this whole thing may be moot.  But this seems to me to be the most concise way to get current user analytics.  With a trigger or a realtime watch on the table you could get a pretty cool-looking dashboard showing live usage.

**Comment by bnjmnt4n** [comment]
This can be closed as it's better addressed by https://github.com/supabase/gotrue/issues/248 in the gotrue repository.

**Comment by J0** [comment]
Cool, thanks for flagging this @bnjmnt4n  Let's close this and address this server side. If anyone has concerns/additional points to add feel free to re-open.
