### ISSUE TITLE
`update` allows users to set empty or otherwise invalid passwords

### ISSUE THREAD

**Issue by SamyDjemai** [supabase/gotrue-js#77]
# Bug report

## Describe the bug

When logged in, the user can update its password to an empty or invalid password, which would've been rejected at sign up.

## To Reproduce

Using this code:
```javascript
async function changePassword(alertData: any) {
  const { error } = await supabase.auth.update({
    password: alertData.password,
  });
  if (error) {
    setErrorMessage(error.message);
    setShowErrorAlert(true);
  }
}
```
1. Call `changePassword(alertData)` with `alertData.password = ""`
2. Check the network request in Dev Tools
3. See a successful PUT request

## Expected behavior

When using an empty or invalid password, either the client library or the server should return an error.

## System information

- OS: Pop_OS! 20.10
- Browser (if applies): Firefox 87.0
- Version of supabase-js: 1.6.0
- Version of Node.js: 14.0.0

**Comment by kangmingtay** [comment]
Hey @SamyDjemai, this has been fixed sometime back and shouldn't be possible now! Thanks!
