### ISSUE TITLE
Access Token not set properly as Authorization header after signInWithPassword 

### ISSUE THREAD

**Issue by NiroHaim** [supabase/gotrue-js#771]
# Bug report

## Describe the bug
**NOTE that RLS is active in my usage.
When creating client in a standard login process (using signInWithPassword function), access token is updated only in supabase.auth but not in request headers and is not used.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create supa client
```js
const { createClient } = require('@supabase/supabase-js');

const url = '...';
const apikey = '...'; 

const supabase = createClient(url, apikey);
```
2. Sign in using an existing user' credentials
```js
const { data, error } = await supabase.auth.signInWithPassword(
  {
    "email": "...",
    "password": "..."
  }
);
```
3. After the last step, when inspecting our  supabase object, we can see that it has a new access token and appropriate headers are also set **but only** in the auth object.
4. Try executing any sql query using the signed in client
```jsx
await supabase.from('table').select('*')
```
Response is empty data as the client does not pass the RLS.

Even when using the setSession function there is no change and the requests return empty.
```jsx
await supabase.auth.setSession(data.session);
```
**NOTE that when manually setting the headers in the following client objects: rest, realtime, headers (supabase.headers) after the login step, everything works fine and the requests return with the expected data.
## Expected behavior

All headers objects in supabase that have any access token application to them are updated after using the signInWithPassword/setSession function just like the auth object is updated so that any consequential request works properly with the access token.

## System information

- OS: windows
- Version of supabase-js: 2.0.5
- Version of Node.js: 16.16.0

## Additional context

For now my workaround is as follows:
```jsx
const { createClient } = require('@supabase/supabase-js');

const url = '...';
const apikey = '...';

const supabase_init_client = createClient(url, apikey)
const {data, error} = await supabase_init_client.auth.signInWithPassword(
  {
    "email": "...",
    "password": "..."
  }
)

const supabase = createClient(url, apikey, {
  'global': {
    'headers': {
      'Authorization': `Bearer ${a.data.session.access_token}`
    },
  },
})
```
In order to use these sessions properly with a refresh token, I need to refresh the session in supabase_init_client on each token timeout and create a new supabase client with the proper headers from the new session which is pretty annoying.

Thank you very much for the help and thanks for the awesome product!

**Comment by hf** [comment]
Closing as there's no further activity on this issue. Please re-open it or comment if you think this needs more attention.
