### ISSUE TITLE
Possible bfcache / BroadcastChannel issue

### ISSUE THREAD

**Issue by JPVRS** [supabase/gotrue-js#779]
# Bug report

- [?] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In Lighthouse testing, I'm getting an error that bfcache is disabled because the page has a registered BroadcastChannel with listeners. In searching my project files, I found a BroadcastChannel being created in this library.

## System information

- OS: Windows
- Browser: Chrome (up to date)
- node.js 18.12.1
- next.js 13.0.5 using pages directory
- supabase-js 9.1.3

## Additional context

I'm not certain the cause is this library. I'm just looking at all possibilities because a solution hasn't been forthcoming after a significant amount of effort to find one.

**Comment by abrorAbdullaev** [comment]
Apparently the core of NextJs is overriding headers at some point by setting `no-cache, must-revalidate` to header `Cache-Control` on page requests, thought for assets requests it sets some cache on response headers. Lighthouse complains based on that header.

![image](https://github.com/supabase/gotrue-js/assets/21175366/2d1edeb3-c303-4050-b439-04a559ddc36d)

**Comment by samternent** [comment]
I've patched this locally to give the option to disable the creation of the `BroadcastChannel`, which has fixed the issue in my project.

[@supabase/gotrue-js@patch](https://github.com/samternent/home/blob/main/patches/%40supabase__gotrue-js%402.55.0.patch)
[@supabase/supabase-js@patch](https://github.com/samternent/home/blob/main/patches/%40supabase__supabase-js%402.38.0.patch)

I couldn't see any behavioural changes when disabling this, but I'm also only running a very small project and don't have any reliance on cross-tab events. The sessions are stored in `localStorage` and persist just fine between tabs. A refresh is required to sync the tab state either way, both with this enabled and disabled.

I'd be interested to hear what implications this change might have.

**Comment by hf** [comment]
BroadcastChannel is used to send messages between tabs. So for example, imagine your user clicks Sign Out in tab B, you want to get the `SIGNED_OUT` event in tab A too.

If that's fine with you, sure, disable it. I believe most developers find cross-tab events more useful than not.

Will be closing the issue now. Please re-open or continue to comment if you think this needs more attention still.
