### ISSUE TITLE
Click on Magic Link triggers spam link protection in uBlock Origin Ad Blocker

### ISSUE THREAD

**Issue by actraiser** [supabase/gotrue-js#792]
Clicking a Magic Link redirects to .eu-west-1.awstrack.me before they hit Supabase to authorize the login. This unfortunately triggers the popular uBlock Origin browser ad blocker with the (default) Peter Lowe's Filter List which you can check out here by the way: https://pgl.yoyo.org/adservers/serverlist.php

Anyway, so clicking the Magic Link in an email will show the following warning first which is of course not optimal and a problematic user experience.

![Bildschirmfoto 2023-10-10 um 08 37 14](https://github.com/supabase/supabase/assets/5455/63350bfd-2a78-4ab7-862f-775c353229b1)

Is it possible for you guys to use a supabase-owned domain to track the clicks instead of awstrack.me? In general it seems that awstrack.me is not a good choice as it is blocked in some firewalls as well. 

Greets
-act

**Comment by kangmingtay** [comment]
hey @actraiser, we don't track the clicks for auth emails sent from your project. This seems like something you installed on your email client / in your browser.

**Comment by actraiser** [comment]
Thank you @kangmingtay for this hint! With that I figured out that resend.com with activated "tracking links" setting is the actual cause of the problem. When Supabase passes the email content to resend which I configured in Supabase dashboard as smtp provider, links in the content get replaced. I disabled that option now on resend.com and everything works as expected. Thanks again! 

Greets
-act
