### ISSUE TITLE
Unable to refresh provider_token

### ISSUE THREAD

**Issue by ferrannp** [supabase/gotrue-js#806]
# Bug report

Notice that I am reporting this as a bug because I do not want to refresh the token on my own (create my own server and secure Google Client Id and Google Secret <-- that is one of the whole point of using Supabase behind the scenes).

I use this to sign in with Google:

```js
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: {
        scopes: [
          'https://www.googleapis.com/auth/userinfo.email',
          'https://www.googleapis.com/auth/userinfo.profile',
          'https://www.googleapis.com/auth/drive.file',
        ],
        redirectTo: 'myRedirectUrlHere',
        queryParams: {
          access_type: 'offline',
          prompt: 'consent',
        },
      },
    });
```

I can extract the following from the returned url: `access_token`, `refresh_token`, `provider_token` and `provider_refresh_token`.

## Describe the bug

Unable to refresh `provider_token` using `provider_refresh_token` using Supabase. Should we use an edge function? I feel it is probs something Supabase can help with?

## To Reproduce

Sign in to Google using `signInWithOAuth`, extract from url returned the `provider_token` and `provider_refresh_token`. No way to refresh it using Supabase after it expires (1 hour).

## Expected behavior

Being able to handle that token refresh?

## Screenshots

N/A

## System information

- React Native: 0.70.7
- Version of supabase-js: ^2.10.0

**Comment by xEverth** [comment]
Chiming in to ask - is the internal endpoint for refreshing the token /auth/v1/token with parameter grant_type=refresh_token ?
I am trying to hit it directly to attempt refreshing the access token, but I get:

`{"component":"api","error":"unsupported_grant_type: ","level":"info","method":"POST","msg":"unsupported_grant_type: ","path":"/token","referer":"myawesomesite","remote_addr":"ip","time":"2023-10-24T08:23:35Z","timestamp":"2023-10-24T08:23:35Z"}`

**Comment by kangmingtay** [comment]
@ferrannp We don't handle refreshing the `provider_token` using the `provider_refresh_token` yet. You will need to call the 3rd party provider's API to refresh the `provider_token` 

@xEverth can you please provide the full request url you are calling? also, as a sanity check, have you tried making a curl request to see if it works:

```bash
curl -X POST 'https://project_ref.supabase.co/auth/v1/token?grant_type=refresh_token' -H 'apikey: YOUR_ANON_KEY' -H 'Content-Type: application/json' -d '{"refresh_token": "your_token"}'
```

**Comment by ferrannp** [comment]
> @ferrannp We don't handle refreshing the provider_token using the provider_refresh_token yet. You will need to call the 3rd party provider's API to refresh the provider_token

Got it. We can close the issue I guess unless you plan to add it in the future?

For anybody else trying to do this, I did in a Supabase edge function. It is a bit strange because when you set up Google Provider in Supabase, you already set the Google Client ID and Secret, so I had to set it up twice for the Supabase edge function. Here it goes:

```js
import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1';

async function refreshGoogleToken(req) {
  try {
    const clientSecret = Deno.env.get('GOOGLE_CLIENT_SECRET');
    const clientId = Deno.env.get('GOOGLE_CLIENT_ID');
    const { providerRefreshToken } = await req.json();

    const refreshToken = decodeURIComponent(providerRefreshToken);

    const params = new URLSearchParams();
    params.append('refresh_token', refreshToken);
    params.append('client_id', clientId);
    params.append('client_secret', clientSecret);
    params.append('grant_type', 'refresh_token');

    const response = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: params.toString(),
    });

    const data = await response.json();

    return new Response(JSON.stringify(data), {
      headers: { 'Content-Type': 'application/json' },
      status: 200,
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: 'Failed to refresh token' }), {
      headers: { 'Content-Type': 'application/json' },
      status: 400,
    });
  }
}

serve(async (req) => {
  const { method } = req;

  if (method === 'POST') {
    return refreshGoogleToken(req);
  }

  return new Response('Not Found', { status: 404 });
});
```

And this is how I call it (my edge function is called `refresh-google-token`:

```js
const { data, error } = await supabase.functions.invoke(
  'refresh-google-token',
  {
    body: {
      providerRefreshToken,
    },
  }
);
```

**Comment by xEverth** [comment]
@kangmingtay Thank you, I was not correctly sending the "Content-Type" header, now works alright 👍

**Comment by kangmingtay** [comment]
@xEverth nice! @ferrannp yeah i'll close this issue for now since we don't plan to add this to Supabase Auth for now
