### ISSUE TITLE
{   "code": 500,   "message": "An error has occurred: fetch failed",   "requestId": "ca5520d8-5cc6-40e3-9f27-ce1ae6227025" }

### ISSUE THREAD

**Issue by Quintas0658** [supabase/gotrue-js#837]
Hello everyone! 😊

I hope you're all doing well. I've recently encountered a puzzling issue with the authentication part of our application. Up until today, it was working smoothly, but suddenly, I'm facing some errors. Has anyone else experienced something similar or knows what might be causing this? Any insights or advice would be greatly appreciated!

Thank you in advance for your help! 🙏🌟

![image](https://github.com/supabase/gotrue-js/assets/136250826/b01247bf-c477-48e4-bec3-c1937e42cd6f)
![image](https://github.com/supabase/gotrue-js/assets/136250826/67dce6c8-969d-415f-bc98-bdb6bfeeacb1)

and 

<img width="528" alt="image" src="https://github.com/supabase/gotrue-js/assets/136250826/8a928da7-d9fa-414a-8617-ccd1b9b3728c">

**Comment by kangmingtay** [comment]
hi @Quintas0658, can you please reach out to us through support at https://supabase.help ? we'll need to access your project logs in order to investigate this further
