### ISSUE TITLE
React Native magic link sign in

### ISSUE THREAD

**Issue by quicksnap** [supabase/gotrue-js#84]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm building a React Native app, and I'd like the email magic link sign in to work. I can forward the query params over to the application, but the API for initializing the session seems limited

## Describe the solution you'd like

There is a method `getSessionFromUrl`: https://github.com/supabase/gotrue-js/blob/0c75bf9e33f5e19403c57113a7a5d27359dd9492/src/GoTrueClient.ts#L258-L262`

It could be extended or refactored to allow a user like myself to pass in the auth query param data manually.

## Describe alternatives you've considered

I could technically do this right now in userland by copying some of this logic manually and calling the "private" methods such as `this._saveSession(session)`. But that seems nasty :)

## Additional context

I'm happy to help out with a PR if there's not already a solution I'm missing. Thanks!

**Comment by quicksnap** [comment]
A little more info: I have the magic link first pointing to a web server. Currently It's just displaying a link (`exp://my-expo-app/yadda/ACCESS_TOKEN` etc.) which echos the JWT query params

**Comment by quicksnap** [comment]
Perhaps this recent PR is relevant.. https://github.com/supabase/gotrue-js/pull/83

**Comment by awalias** [comment]
I think this is now fixed by https://github.com/supabase/gotrue-js/pull/80 ?
