### ISSUE TITLE
User session recovery fails on react-native

### ISSUE THREAD

**Issue by phamhieu** [supabase/gotrue-js#92]
# Bug report

## Describe the bug

> I have everything wrapped in a user context provider. When there is a crash or you open the app after closing it, or even when you go back to it sometimes, it logs you out and you have to log in again. I tried a lot of things, including specifying options and double checking the code. Most of it is adapted from the Expo example. Please let me know your thoughts from the gist below:
https://gist.github.com/rodjoseph/ec6b511ea6ab0a2354b231e31121f736

## Expected behavior

User session should be recovered when user comes back to the app

**Comment by hf** [comment]
Hey @phamhieu is this still an issue for you? Since this ticket has not seen activity since May 28th, 2021 I'll close it as stale but do re-open it if you are still facing the same.
