### ISSUE TITLE
Signup error type Error does not include a "status" property

### ISSUE THREAD

**Issue by thebetternewt** [supabase/gotrue-js#96]
# Bug report

## Describe the bug

```typescript
// when calling...
const { user, session, error } = await supabase.auth.signUp({
	email: userInput.email,
	password: userInput.password
});

// and error is:
error: {
    message: 'A user with this email address has already been registered',
    status: 400
}
```

`error` type is JS `Error`, which does not include the `status` property, so trying to access `error.status` results in ESLint warning `Property 'status' does not exist on type 'Error'.ts(2339)`

## To Reproduce

I do not have working hosted project yet.

## Expected behavior

`error` type (`AuthError`?) should include `status` property.

## Screenshots

<img width="614" alt="Screen Shot 2021-06-03 at 1 57 39 PM" src="https://user-images.githubusercontent.com/8032577/120697833-d3e1b600-c473-11eb-8190-f0059c17082a.png">

**Comment by kangmingtay** [comment]
hey @thebetternewt, we have better type support for errors in supabase-js/v2 (`rc` branch) - do check that out and let us know if it solves your issue!
